### ISSUE TITLE
hbasereader导出遇到问题

### ISSUE THREAD

**Issue by zhaojungithub** [alibaba/DataX#10]
[hadoop@IT-INT-9961 bin]$ python ./datax.py ../job/datax2_test_hbase2m.json

DataX (UNKNOWN_DATAX_VERSION), From Alibaba !
Copyright (C) 2010-2015, Alibaba Group. All Rights Reserved.

2016-01-14 11:01:27.105 [main] ERROR Engine - -mode_________________main_______________________standalone
2016-01-14 11:01:27.112 [main] ERROR Engine - /data/datax/datax_2.0/job/datax2_test_hbase2m.json___________________________jobPath_____________________________
2016-01-14 11:01:27.112 [main] ERROR Engine - -1_____________________________jobIdString___________________________
2016-01-14 11:01:27.258 [main] ERROR Engine - {"common":{"column":{"dateFormat":"yyyy-MM-dd","datetimeFormat":"yyyy-MM-dd HH:mm:ss","encoding":"utf-8","extraFormats":["yyyyMMdd"],"timeFormat":"HH:mm:ss","timeZone":"GMT+8"}},"core":{"container":{"job":{"reportInterval":10000},"taskGroup":{"channel":5},"trace":{"enable":"true"}},"dataXServer":{"address":"http://localhost:7001/api","reportDataxLog":false,"reportPerfLog":false,"timeout":10000},"statistics":{"collector":{"plugin":{"maxDirtyNumber":10,"taskClass":"com.alibaba.datax.core.statistics.plugin.task.StdoutPluginCollector"}}},"transport":{"channel":{"byteCapacity":67108864,"capacity":512,"class":"com.alibaba.datax.core.transport.channel.memory.MemoryChannel","flowControlInterval":20,"speed":{"byte":1048576,"record":10000}},"exchanger":{"bufferSize":32,"class":"com.alibaba.datax.core.plugin.BufferedRecordExchanger"}}},"entry":{"jvm":"-Xms1G -Xmx1G"},"job":{"content":[{"reader":{"name":"hbasereader","parameter":{"column":[{"name":"rowkey","type":"string"},{"name":"info:name","type":"string"},{"name":"info:age","type":"string"}],"encoding":"utf-8","hbaseConfig":{"hbase.zookeeper.property.clientPort":"2181","hbase.zookeeper.quorum":"IT-INT-9961,IT-INT-9962,IT-INT-9963"},"mode":"normal","range":{"endRowkey":"","startRowkey":""},"table":"hytest_person"}},"writer":{"name":"mysqlwriter","parameter":{"batchSize":"10240","column":["rowkey,name,age"],"connection":[{"jdbcUrl":"jdbc:mysql://10.168.0.148:3306/datax_writer?useUnicode=true&characterEncoding=utf8","table":["hbase2mysql_02"]}],"password":"root","preSql":["delete from @table"],"username":"root","writeMode":"insert"}}}],"setting":{"speed":{"channel":"3"}}},"plugin":{"reader":{"hbasereader":{"class":"com.alibaba.datax.plugin.reader.hbasereader.HbaseReader","description":"useScene: prod. mechanism: Scan to read data.","developer":"alibaba","name":"hbasereader","path":"/data/datax/datax_2.0/plugin/reader/hbasereader"}},"writer":{"mysqlwriter":{"class":"com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter","description":"useScene: prod. mechanism: Jdbc connection using the database, execute insert sql. warn: The more you know about the database, the less problems you encounter.","developer":"alibaba","name":"mysqlwriter","path":"/data/datax/datax_2.0/plugin/writer/mysqlwriter"}}}}___________________________toJSON_____________________________
2016-01-14 11:01:27.267 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2016-01-14 11:01:27.271 [main] INFO  Engine - the machine info  => 

        osInfo: Oracle Corporation 1.8 25.60-b23
        jvmInfo:        Linux amd64 2.6.32-431.el6.x86_64
        cpu num:        8

        totalPhysicalMemory:    -0.00G
        freePhysicalMemory:     -0.00G
        maxFileDescriptorCount: -1
        currentOpenFileDescriptorCount: -1

        GC Names        [PS MarkSweep, PS Scavenge]

        MEMORY_NAME                    | allocation_size                | init_size                      
        PS Eden Space                  | 256.00MB                       | 256.00MB                       
        Code Cache                     | 240.00MB                       | 2.44MB                         
        Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
        PS Survivor Space              | 42.50MB                        | 42.50MB                        
        PS Old Gen                     | 683.00MB                       | 683.00MB                       
        Metaspace                      | -0.00MB                        | 0.00MB                         

2016-01-14 11:01:27.275 [main] INFO  Engine - 
{
        "content":[
                {
                        "reader":{
                                "name":"hbasereader",
                                "parameter":{
                                        "column":[
                                                {
                                                        "name":"rowkey",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"info:name",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"info:age",
                                                        "type":"string"
                                                }
                                        ],
                                        "encoding":"utf-8",
                                        "hbaseConfig":{
                                                "hbase.zookeeper.property.clientPort":"2181",
                                                "hbase.zookeeper.quorum":"IT-INT-9961,IT-INT-9962,IT-INT-9963"
                                        },
                                        "mode":"normal",
                                        "range":{
                                                "endRowkey":"",
                                                "startRowkey":""
                                        },
                                        "table":"hytest_person"
                                }
                        },
                        "writer":{
                                "name":"mysqlwriter",
                                "parameter":{
                                        "batchSize":"10240",
                                        "column":[
                                                "rowkey,name,age"
                                        ],
                                        "connection":[
                                                {
                                                        "jdbcUrl":"jdbc:mysql://10.168.0.148:3306/datax_writer?useUnicode=true&characterEncoding=utf8",
                                                        "table":[
                                                                "hbase2mysql_02"
                                                        ]
                                                }
                                        ],
                                        "password":"****",
                                        "preSql":[
                                                "delete from @table"
                                        ],
                                        "username":"root",
                                        "writeMode":"insert"
                                }
                        }
                }
        ],
        "setting":{
                "speed":{
                        "channel":"3"
                }
        }
}

2016-01-14 11:01:27.276 [main] ERROR Engine - ___________________________start_____________________________
2016-01-14 11:01:27.290 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2016-01-14 11:01:27.290 [main] ERROR Engine - null___________________________jobInfoConfig_____________________________
2016-01-14 11:01:27.291 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=true, priority=0
2016-01-14 11:01:27.291 [main] ERROR Engine - com.alibaba.datax.common.statistics.PerfTrace@1fc2b765___________________________perfTrace_____________________________
2016-01-14 11:01:27.291 [main] INFO  JobContainer - DataX jobContainer starts job.
2016-01-14 11:01:27.292 [main] INFO  JobContainer - Set jobId = 0
2016-01-14 11:01:27.617 [job-0] INFO  OriginalConfPretreatmentUtil - table:[hbase2mysql_02] all columns:[
rowkey,name,age
].
2016-01-14 11:01:27.625 [job-0] INFO  OriginalConfPretreatmentUtil - Write data [
insert INTO %s (rowkey,name,age) VALUES(?)
], which jdbcUrl like:[jdbc:mysql://10.168.0.148:3306/datax_writer?useUnicode=true&characterEncoding=utf8&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true]
2016-01-14 11:01:27.626 [job-0] INFO  JobContainer - DataX Reader.Job [hbasereader] do prepare work .
2016-01-14 11:01:27.626 [job-0] INFO  JobContainer - DataX Writer.Job [mysqlwriter] do prepare work .
2016-01-14 11:01:27.631 [job-0] INFO  CommonRdbmsWriter$Job - Begin to execute preSqls:[delete from hbase2mysql_02]. context info:jdbc:mysql://10.168.0.148:3306/datax_writer?useUnicode=true&characterEncoding=utf8&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.
2016-01-14 11:01:27.632 [job-0] INFO  JobContainer - Job set Channel-Number to 3 channels.
Jan 14, 2016 11:01:27 AM org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper <init>
INFO: The identifier of this process is 28255@IT-INT-9961
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.3.2-1031432, built on 11/05/2010 05:32 GMT
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:host.name=IT-INT-9961
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.version=1.8.0_60
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.home=/soft/jdk1.8.0_60/jre
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/data/datax/datax_2.0/lib/commons-codec-1.9.jar:/data/datax/datax_2.0/lib/commons-cli-1.2.jar:/data/datax/datax_2.0/lib/slf4j-api-1.7.10.jar:/data/datax/datax_2.0/lib/commons-logging-1.1.1.jar:/data/datax/datax_2.0/lib/logback-core-1.0.13.jar:/data/datax/datax_2.0/lib/fastjson-1.1.43.jar:/data/datax/datax_2.0/lib/datax-common-0.0.1-SNAPSHOT.jar:/data/datax/datax_2.0/lib/commons-io-2.4.jar:/data/datax/datax_2.0/lib/guava-18.0.jar:/data/datax/datax_2.0/lib/commons-lang-2.6.jar:/data/datax/datax_2.0/lib/httpcore-4.4.jar:/data/datax/datax_2.0/lib/datax-core-0.0.1-SNAPSHOT.jar:/data/datax/datax_2.0/lib/commons-collections-3.2.1.jar:/data/datax/datax_2.0/lib/httpclient-4.4.jar:/data/datax/datax_2.0/lib/logback-classic-1.0.13.jar:/data/datax/datax_2.0/lib/commons-configuration-1.10.jar:/data/datax/datax_2.0/lib/janino-2.5.16.jar:/data/datax/datax_2.0/lib/commons-beanutils-1.9.2.jar:/data/datax/datax_2.0/lib/hamcrest-core-1.3.jar:/data/datax/datax_2.0/lib/commons-lang3-3.3.2.jar:/data/datax/datax_2.0/lib/fluent-hc-4.4.jar:/data/datax/datax_2.0/lib/commons-math3-3.1.1.jar:.
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:os.version=2.6.32-431.el6.x86_64
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Client environment:user.dir=/data/datax/datax_2.0/bin
16/01/14 11:01:27 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=IT-INT-9962:2181,IT-INT-9961:2181,IT-INT-9963:2181 sessionTimeout=180000 watcher=hconnection0x0
16/01/14 11:01:27 INFO zookeeper.ClientCnxn: Opening socket connection to server IT-INT-9962/10.168.99.62:2181
16/01/14 11:01:27 INFO zookeeper.ClientCnxn: Socket connection established to IT-INT-9962/10.168.99.62:2181, initiating session
16/01/14 11:01:27 INFO zookeeper.ClientCnxn: Session establishment complete on server IT-INT-9962/10.168.99.62:2181, sessionid = 0x251d30b50e90007, negotiated timeout = 40000

上面是我的执行时输出的日志，然后就一直卡在这里不动了。
我想问下，是因为hbase的版本问题吗？ 我的hbase为0.98.16.1-hadoop2版本

**Comment by zhaojungithub** [comment]
这个问题困扰我好久了，还请大神帮忙解答下，感激不尽...

**Comment by zhaojungithub** [comment]
下面是连接超时以后的错误信息

2016-01-14 11:19:55.739 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[HbaseReader-04], Description:[初始化 Hbase 抽取表时出错.].  - Unable to find region for hytest_person,,99999999999999 after 10 tries. - Unable to find region for hytest_person,,99999999999999 after 10 tries.
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseUtil.initHtable(HbaseUtil.java:281) ~[hbasereader-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseSplitUtil.split(HbaseSplitUtil.java:32) ~[hbasereader-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.reader.hbasereader.HbaseReader$Job.split(HbaseReader.java:38) ~[hbasereader-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:696) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:116) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:87) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:168) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:202) [datax-core-0.0.1-SNAPSHOT.jar:na]
Caused by: org.apache.hadoop.hbase.client.NoServerForRegionException: Unable to find region for hytest_person,,99999999999999 after 10 tries.
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1092) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:997) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1099) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1001) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:958) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:251) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:155) ~[hbase-0.94.27.jar:0.94.27]
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:129) ~[hbase-0.94.27.jar:0.94.27]
        at com.alibaba.datax.plugin.reader.hbasereader.HTableManager.createHTable(HTableManager.java:14) ~[hbasereader-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseUtil.initHtable(HbaseUtil.java:275) ~[hbasereader-0.0.1-SNAPSHOT.jar:na]
        ... 8 common frames omitted
2016-01-14 11:19:55.744 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2016-01-14 11:19:55.745 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[HbaseReader-04], Description:[初始化 Hbase 抽取表时出错.].  - Unable to find region for hytest_person,,99999999999999 after 10 tries. - Unable to find region for hytest_person,,99999999999999 after 10 tries.
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseUtil.initHtable(HbaseUtil.java:281)
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseSplitUtil.split(HbaseSplitUtil.java:32)
        at com.alibaba.datax.plugin.reader.hbasereader.HbaseReader$Job.split(HbaseReader.java:38)
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:696)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:116)
        at com.alibaba.datax.core.Engine.start(Engine.java:87)
        at com.alibaba.datax.core.Engine.entry(Engine.java:168)
        at com.alibaba.datax.core.Engine.main(Engine.java:202)
Caused by: org.apache.hadoop.hbase.client.NoServerForRegionException: Unable to find region for hytest_person,,99999999999999 after 10 tries.
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1092)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:997)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1099)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1001)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:958)
        at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:251)
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:155)
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:129)
        at com.alibaba.datax.plugin.reader.hbasereader.HTableManager.createHTable(HTableManager.java:14)
        at com.alibaba.datax.plugin.reader.hbasereader.util.HbaseUtil.initHtable(HbaseUtil.java:275)
        ... 8 more

**Comment by binaryWorld** [comment]
@zhaojungithub  看日志是找不到你的region，你自己debug下吧

**Comment by zhaojungithub** [comment]
我猜测是不是由于datax不支持hadoop HA的配置, hbasereader的配置中并没有指定fs.defaultFS的地方。 这个怎么解决呢，hbase和hadoop为都不太懂
