### ISSUE TITLE
任务运行一段时间后speed变为0，程序不退出，变成假死状态

### ISSUE THREAD

**Issue by hanyu100** [alibaba/DataX#1005]
2021-04-26 11:02:52 CST INFO - 2021-04-26 11:02:52.972 [job-0] INFO  StandAloneJobContainerCommunicator - Total 70237120 records, 11200894994 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 532.685s |  All Task WaitReaderTime 3.271s | Percentage 0.00%
2021-04-26 11:03:02 CST INFO - 2021-04-26 11:03:02.973 [job-0] INFO  StandAloneJobContainerCommunicator - Total 70237120 records, 11200894994 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 532.685s |  All Task WaitReaderTime 3.271s | Percentage 0.00%
2021-04-26 11:03:22 CST INFO - 2021-04-26 11:03:22.974 [job-0] INFO  StandAloneJobContainerCommunicator - Total 70237120 records, 11200894994 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 532.685s |  All Task WaitReaderTime 3.271s | Percentage 0.00%

**Comment by hanyu100** [comment]
花了3个多小时问题终于解决了，将问题解决过程和原因分析给大家。
由于程序日志一切正常所以我们通过jstack查看堆栈信息，内容如下：
`"0-0-0-reader" #32 prio=5 os_prio=0 tid=0x00007f3000009800 nid=0x1572b runnable [0x00007f30c53d3000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:170)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:100)
at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:143)
at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:173)

locked <0x00000000c0efd720> (a com.mysql.jdbc.util.ReadAheadInputStream)
at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2911)
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3337)
at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1928)
at com.mysql.jdbc.RowDataDynamic.nextRecord(RowDataDynamic.java:378)
at com.mysql.jdbc.RowDataDynamic.next(RowDataDynamic.java:358)
at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:158)
locked <0x00000000c0ee8ff8> (a com.mysql.jdbc.JDBC4Connection)
at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6702)
locked <0x00000000c0ee8ff8> (a com.mysql.jdbc.JDBC4Connection)
at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:842)
at com.mysql.jdbc.StatementImpl.realClose(StatementImpl.java:2354)
locked <0x00000000c0ee8ff8> (a com.mysql.jdbc.JDBC4Connection)
at com.mysql.jdbc.ConnectionImpl.closeAllOpenStatements(ConnectionImpl.java:1536)
at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4262)
at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1510)
locked <0x00000000c0ee8ff8> (a com.mysql.jdbc.JDBC4Connection)
at com.alibaba.datax.plugin.rdbms.util.DBUtil.closeDBResources(DBUtil.java:502)
at com.alibaba.datax.plugin.rdbms.util.DBUtil.closeDBResources(DBUtil.java:509)
at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:233)
at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:81)
at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:

None
"0-0-0-writer" #31 prio=5 os_prio=0 tid=0x00007f3000009000 nid=0x1572a waiting on condition [0x00007f30c54d5000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)

parking to wait for <0x00000000c12c0938> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at com.alibaba.datax.core.transport.channel.memory.MemoryChannel.doPullAll(MemoryChannel.java:114)
at com.alibaba.datax.core.transport.channel.Channel.pullAll(Channel.java:150)
at com.alibaba.datax.core.transport.exchanger.BufferedRecordExchanger.receive(BufferedRecordExchanger.java:152)
at com.alibaba.datax.core.transport.exchanger.BufferedRecordExchanger.getFromReader(BufferedRecordExchanger.java:130)
at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.textFileStartWrite(HdfsHelper.java:321)
at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:454)
at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:

None`
可以看出0-0-0-writer正在等待pull数据，0-0-0-reader 在执行closeDBResources()方法时夯住了。此时程序日志已表现为: 0 records/s 。

问题原因：由于拉取数据过大，且sql语句未走索引，导致每次拉取数据都要全表扫描导致数据库性能达到瓶颈，最终无法响应closeDBResources()方法。
解决方案：
优化sql语句走索引，分段拉取

**Comment by duxiaojiao** [comment]
我也遇到了，同步一张2000万数据表的就这样了

**Comment by Ink00Bamboo** [comment]
走索引的话，就是增量同步的方式。 分段拉取用datax怎么做啊，任务拆分?

**Comment by zhu1147212910** [comment]
源库是别人的没法优化怎么解决
