### ISSUE TITLE
MongoDB中的文档类型转换失败

### ISSUE THREAD

**Issue by codejianhongxie** [alibaba/DataX#101]
报如下错误：
com.mongodb.util.JSONParseException: 
Document{{name=张, age=25}}
^
	at com.mongodb.util.JSONParser.parse(JSON.java:230) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.util.JSONParser.parse(JSON.java:155) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.util.JSON.parse(JSON.java:92) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.util.JSON.parse(JSON.java:73) ~[mongo-java-driver-3.2.2.jar:na]
	at com.alibaba.datax.plugin.writer.mongodbwriter.MongoDBWriter$Task.doBatchInsert(MongoDBWriter.java:232) [mongodbwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.mongodbwriter.MongoDBWriter$Task.startWrite(MongoDBWriter.java:144) [mongodbwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

[问题原因]
mongodbreader使用Document对文档类型进行存储，而mongodbwriter使用BasicBSONObject对象来进行存储，Document对象的toString()方法会输出类似Document{}的结构，导致mongodbwriter使用JSON.parse解析时失败。应统一存储格式为BSONObject

**Comment by strive-kun** [comment]
先把Document .toJson() ,再用JSON.parse解析试试

**Comment by kaihekaihe** [comment]
gg

**Comment by qujinqiang** [comment]
mongo的文档类型不支持读取，写入吧？

**Comment by qujinqiang** [comment]
@codejianhongxie json字符串写入到文档类型有思路吗？
