### ISSUE TITLE
mongodbReader读取报错列数不匹配

### ISSUE THREAD

**Issue by ljl0303** [alibaba/DataX#1017]
```
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 列配置信息有错误. 因为您配置的 任务中，源头读取字段数:0 与 目的表要写入的字段数:1 不相等. 请检查您的配置并作出修改.
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:278)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
        at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Unknown Source)
```
是否是因为mongo内该字段不存在或者为null？但是我已经在query加了条件限制字段非null且存在，求大佬指导一下

**Comment by ljl0303** [comment]
目前用的方法是给字段加默认值。
db.collection.updateMany(
    {
        "$or": [
            { "name": { "$exists": false } }, 
            { "name": null }
        ]
    }, 
    { "$set": { "name": "test" } }
)
