### ISSUE TITLE
Java调用ES的写插件报错

### ISSUE THREAD

**Issue by cml26** [alibaba/DataX#1050]
用源码编译了ES的写插件，放在dataX的工具包里面可以正常运行，但是放在Java项目里面会报错：
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.copyOf(Ljava/util/Collection;)Lcom/google/common/collect/ImmutableSet;
	at io.searchbox.client.AbstractJestClient$ServerPool.getServers(AbstractJestClient.java:114)
	at io.searchbox.client.AbstractJestClient.setServers(AbstractJestClient.java:48)
	at io.searchbox.client.JestClientFactory.getObject(JestClientFactory.java:60)
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESClient.createClient(ESClient.java:67)
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Job.prepare(ESWriter.java:49)
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.example.demo.DataXTestApplication.main(DataXTestApplication.java:18)
想问下这个报错原因是什么？怎么解决？

**Comment by PorcupineBoy** [comment]
刚刚发生了你这个问题；
原因：
 es 的这个客户端版本含有guava  ， 是因为其他依赖包中引入了比 该版本低的缘故，统一一下版本就可以了。
    <dependency>
            <groupId>io.searchbox</groupId>
            <artifactId>jest-common</artifactId>
            <version>6.3.1</version>
    </dependency>

 <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
