### ISSUE TITLE
java.lang.RuntimeException: No enum constant com.aliyun.odps.OdpsType.TINYINT

### ISSUE THREAD

**Issue by liujunfei2230** [alibaba/DataX#1051]
maxcompute已开启setproject odps.sql.type.system.odps2=true
maxcompute中表的数据类型有tinyint
使用开源datax同步数据，报错如下
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[OdpsWriter-01], Description:[您配置的值不合法.].  - 加载 ODPS 目的表:ods_call_log_ptn 失败. 请检查您配置的 ODPS 目的表的 project,table,accessId,accessKey,odpsServer等值. - java.lang.RuntimeException: No enum constant com.aliyun.odps.OdpsType.TINYINT
	at com.aliyun.odps.Table.loadSchemaFromJson(Table.java:567)
	at com.aliyun.odps.Table.reload(Table.java:130)
	at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil$1.call(OdpsUtil.java:109)
	at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil$1.call(OdpsUtil.java:106)
	at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164)
	at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111)
	at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30)
	at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil.getTable(OdpsUtil.java:106)
	at com.alibaba.datax.plugin.writer.odpswriter.OdpsWriter$Job.prepare(OdpsWriter.java:152)
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.IllegalArgumentException: No enum constant com.aliyun.odps.OdpsType.TINYINT
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.aliyun.odps.OdpsType.valueOf(OdpsType.java:27)
	at com.aliyun.odps.Table.parseColumn(Table.java:846)
	at com.aliyun.odps.Table.loadSchemaFromJson(Table.java:555)
	... 14 more

**Comment by TrafalgarLuo** [comment]
odps 2.0的类型已经支持了：
可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz
在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
