### ISSUE TITLE
增加transformer 报错

### ISSUE THREAD

**Issue by PeterLau2019** [alibaba/DataX#1070]
增加以下源码报错，去掉正常执行
 "transformer":[
                                {
                                        "name":"dx_groovy",
                                        "parameter":{
                                                "code":"Column column=record.getColumn(2); \n String oriValue=column.asString(); \n String newValue=\"\";\n  if(oriValue){newValue=oriValue.replaceAll('\\s','')}; \n record.setColumn(0,new StringColuns(newValue)); \n return record; ",
                                                "extraPackage":[]
                                        }
                                }
                        ],

报错提示如下：
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
        at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
        at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:84)
        at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:59)
        at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
        at com.alibaba.datax.plugin.reader.sqlserverreader.SqlServerReader$Job.init(SqlServerReader.java:40)
        at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)

**Comment by XuDaojie** [comment]
groovy代码里的字符串用 `'xxx'`，不然就和json的`"`冲突了
