### ISSUE TITLE
datax 数据过大时 报类型转换异常

### ISSUE THREAD

**Issue by zhangqh01** [alibaba/DataX#1077]
在全量同步 pg数据到hive时 ， 数据已经同步完成，最后却提示数据转换异常。
信息如下：
    ```
2021-08-11 01:05:21 [AnalysisStatistics.analysisStatisticsLog-53] 2021-08-11 01:05:21.956 [job-0] INFO  StandAloneJobContainerCommunicator - Total 4229060636 records, 192399758715 bytes | Speed 8.81MB/s, 203007 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 3,260.711s |  All Task WaitReaderTime 2,777.373s | Percentage 100.00% 
2021-08-11 01:05:21 [ExecutorJobHandler.execute-83] java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "4229060636"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.wugui.datax.executor.service.jobhandler.ExecutorJobHandler.execute(ExecutorJobHandler.java:76)
	at com.wugui.datatx.core.thread.JobThread.run(JobThread.java:153)
Caused by: java.lang.NumberFormatException: For input string: "4229060636"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.wugui.datax.executor.service.logparse.AnalysisStatistics.analysisStatisticsLog(AnalysisStatistics.java:49)
	at com.wugui.datax.executor.service.jobhandler.ExecutorJobHandler.lambda$execute$0(ExecutorJobHandler.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zhangqh01** [comment]
datax-web 导致 最后获取datax 读取记录总数   datax-web使用了int类型导致。修改下LogStatistics 类 taskRecordReaderNum 属性为long 即可
