### ISSUE TITLE
大佬们，我想知道datax支不支持华为的Gaussdb啊

### ISSUE THREAD

**Issue by 420668580** [alibaba/DataX#1083]

**Comment by zhbdesign** [comment]
> _No description provided._

https://pan.baidu.com/s/1iAAX3MXjNjV8KwJpw5MM8w 
提取码：9wi3,我打包好的Gaussdb读写插件，你下载使用，有问题可以反馈

**Comment by cristoyu** [comment]
为什么不提个pr 到master分支？ @zhbdesign

**Comment by Riefu** [comment]
支持，用的pg的writer插件即可。

**Comment by zhbdesign** [comment]
链接：https://pan.baidu.com/s/1MQykqNUKlrQIf45b3yrizg 
提取码：6ld3，支持pg和guass的更新模式

**Comment by devhh** [comment]
可自行开发插件实现

**Comment by sulon007** [comment]
> 链接：https://pan.baidu.com/s/1MQykqNUKlrQIf45b3yrizg 提取码：6ld3，支持pg和guass的更新模式

下载这个执行后，报如下错误，请问是什么原因呢？
2024-05-17 17:22:23.568 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-03], Description:[DataX引擎配置错误，该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 在有总bps限速条件下，单个channel的bps值不能为空，也不能为非正数
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:430)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:387)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2024-05-17 17:22:23.574 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2024-05-17 17:22:23.575 [job-0] ERROR Engine -
