### ISSUE TITLE
使用DataX从oracle迁移clickhouse报错求解

### ISSUE THREAD

**Issue by dragon1102** [alibaba/DataX#1086]
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:176)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
	... 7 more

**Comment by zhbdesign** [comment]
> 经DataX智能分析,该任务最可能的错误原因是:
> com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息 .]. - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
> at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
> at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
> at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
> at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
> at com.alibaba.datax.core.Engine.start(Engine.java:92)
> at com.alibaba.datax.core.Engine.entry(Engine.java:171)
> at com.alibaba.datax.core.Engine.main(Engine.java:204)
> 
> * java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
>   at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
>   at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
>   at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
>   at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
>   at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
>   at com.alibaba.datax.core.Engine.start(Engine.java:92)
>   at com.alibaba.datax.core.Engine.entry(Engine.java:171)
>   at com.alibaba.datax.core.Engine.main(Engine.java:204)
>   at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
>   at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:176)
>   at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
>   at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
>   at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
>   at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
>   at com.alibaba.datax.core.Engine.start(Engine.java:92)
>   at com.alibaba.datax.core.Engine.entry(Engine.java:171)
>   at com.alibaba.datax.core.Engine.main(Engine.java:204)
>   Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
>   at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
>   ... 7 more

https://pan.baidu.com/s/1iAAX3MXjNjV8KwJpw5MM8w 
提取码：9wi3，我打包好的，你试一下

**Comment by xxh2000** [comment]
@dragon1102 你这个错应该还是打包的问题，缺少oracle类，或者plugin_json配置文件有问题

**Comment by dragon1102** [comment]
> @dragon1102 你这个错应该还是打包的问题，缺少oracle类，或者plugin_json配置文件有问题

https://github.com/kuangye098/DataX 使用这个分支编译成功了

**Comment by zhbdesign** [comment]
> > @dragon1102 你这个错应该还是打包的问题，缺少oracle类，或者plugin_json配置文件有问题
> 
> https://github.com/kuangye098/DataX 使用这个分支编译成功了

没用我的吗，
