### ISSUE TITLE
mysql2elasticsearch

### ISSUE THREAD

**Issue by lx18379612615** [alibaba/DataX#1100]
**java.lang.String cannot be cast to java.util.List**这个是问题出在哪呀？

2021-09-17 12:19:05.192 [job-0] ERROR JobContainer - Exception when job run
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49) ~[mysqlreader-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2021-09-17 12:19:05.196 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-09-17 12:19:05.198 [job-0] ERROR Engine -

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
        at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
        at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
        at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
        at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
        at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
        at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
        at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        ... 3 more

**Comment by zhbdesign** [comment]
> **java.lang.String cannot be cast to java.util.List**这个是问题出在哪呀？
> 
> 2021-09-17 12:19:05.192 [job-0] ERROR JobContainer - Exception when job run
> java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49) ~[mysqlreader-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
> at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
> 2021-09-17 12:19:05.196 [job-0] INFO StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes | All Task WaitWriterTime 0.000s | All Task WaitReaderTime 0.000s | Percentage 0.00%
> 2021-09-17 12:19:05.198 [job-0] ERROR Engine -
> 
> 经DataX智能分析,该任务最可能的错误原因是:
> com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息 .]. - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
> at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
> at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
> at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
> at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
> at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
> at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
> at com.alibaba.datax.core.Engine.start(Engine.java:92)
> at com.alibaba.datax.core.Engine.entry(Engine.java:171)
> at com.alibaba.datax.core.Engine.main(Engine.java:204)
> 
> * java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
>   at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
>   at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
>   at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
>   at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
>   at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
>   at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
>   at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
>   at com.alibaba.datax.core.Engine.start(Engine.java:92)
>   at com.alibaba.datax.core.Engine.entry(Engine.java:171)
>   at com.alibaba.datax.core.Engine.main(Engine.java:204)
>   ```
>    at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
>    at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
>    at com.alibaba.datax.core.Engine.start(Engine.java:92)
>    at com.alibaba.datax.core.Engine.entry(Engine.java:171)
>    at com.alibaba.datax.core.Engine.main(Engine.java:204)
>   ```
> 
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
> at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
> at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
> at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
> at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
> at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
> at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
> ... 3 more

把你json贴出来，你json写错了

**Comment by lx18379612615** [comment]
> > **java.lang.String cannot be cast to java.util.List**这个是问题出在哪呀？
> > 2021-09-17 12:19:05.192 [job-0] ERROR JobContainer - Exception when job run
> > java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> > at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49) ~[mysqlreader-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
> > at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
> > 2021-09-17 12:19:05.196 [job-0] INFO StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes | All Task WaitWriterTime 0.000s | All Task WaitReaderTime 0.000s | Percentage 0.00%
> > 2021-09-17 12:19:05.198 [job-0] ERROR Engine -
> > 经DataX智能分析,该任务最可能的错误原因是:
> > com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息 .]. - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> > at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
> > at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
> > at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
> > at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
> > at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
> > at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
> > at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
> > at com.alibaba.datax.core.Engine.start(Engine.java:92)
> > at com.alibaba.datax.core.Engine.entry(Engine.java:171)
> > at com.alibaba.datax.core.Engine.main(Engine.java:204)
> > 
> > * java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> >   at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
> >   at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
> >   at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
> >   at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
> >   at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
> >   at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
> >   at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
> >   at com.alibaba.datax.core.Engine.start(Engine.java:92)
> >   at com.alibaba.datax.core.Engine.entry(Engine.java:171)
> >   at com.alibaba.datax.core.Engine.main(Engine.java:204)
> >   ```
> >    at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
> >    at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
> >    at com.alibaba.datax.core.Engine.start(Engine.java:92)
> >    at com.alibaba.datax.core.Engine.entry(Engine.java:171)
> >    at com.alibaba.datax.core.Engine.main(Engine.java:204)
> >   ```
> > 
> > Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
> > at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
> > at com.alibaba.datax.plugin.rdbms.reader.util.ReaderSplitUtil.doSplit(ReaderSplitUtil.java:94)
> > at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.split(CommonRdbmsReader.java:103)
> > at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.split(MysqlReader.java:49)
> > at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
> > at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
> > at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
> > ... 3 more
> 
> 把你json贴出来，你json写错了

确实是json写错了；
"connection": [{
              "querySql": "select c_tag_english_name, use_count, operator_no from cluster_tag_use;", //这里应该为[select * ...]
              "jdbcUrl": ["jdbc:mysql://10.20.35.85:33061/gy_dmp"]
            }]
querySql的value应该是List类型的；
非常感谢回答；
