### ISSUE TITLE
【mongoReader】When I read mongodb data, Fields with null values were discarded, resulting in inconsistent field order

### ISSUE THREAD

**Issue by zjw-zjw** [alibaba/DataX#1101]
When I read mongodb data, Fields with null values were discarded, resulting in inconsistent field order

here is the mongo data
![image](https://user-images.githubusercontent.com/48348786/133878674-ba350949-6010-4789-9ea2-afbad9a3aa8d.png)

the follow is the json file:
![image](https://user-images.githubusercontent.com/48348786/133878704-28fbe6f8-4dde-4682-88e2-a6b94b45e56f.png)

You can see the index 4【PackageCode】is null。 The error log does not report this field
![image](https://user-images.githubusercontent.com/48348786/133878782-1fc22d69-11f9-489f-a8cd-17439b079ae6.png)

**Comment by zhbdesign** [comment]
链接：https://pan.baidu.com/s/1uoHeSk42F3wwTaFrtqH-FA 
提取码：nnoq
可以使用我打包的，

**Comment by zjw-zjw** [comment]
谢谢你，不过我看文件好像是KuduReader，不是MongoReader。请问是否发错了呢
| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/18/2021 ***@***.***> wrote：

链接：https://pan.baidu.com/s/1uoHeSk42F3wwTaFrtqH-FA
提取码：nnoq
可以使用我打包的，

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhbdesign** [comment]
> 谢谢你，不过我看文件好像是KuduReader，不是MongoReader。请问是否发错了呢 | | 郑杰文 | | ***@***.*** | 签名由网易邮箱大师定制 On 9/18/2021 ***@***.***> wrote： 链接：https://pan.baidu.com/s/1uoHeSk42F3wwTaFrtqH-FA 提取码：nnoq 可以使用我打包的， — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

链接：https://pan.baidu.com/s/16t2SDevyRzmGoleuI6kJvQ 
提取码：5x5d
刚才发发错了，现在是正确的，尴尬了

**Comment by zjw-zjw** [comment]
谢谢！我看看


| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/18/2021 ***@***.***> wrote：

谢谢你，不过我看文件好像是KuduReader，不是MongoReader。请问是否发错了呢 | | 郑杰文 | | @.*** | 签名由网易邮箱大师定制 On 9/18/2021 @.***> wrote： 链接：https://pan.baidu.com/s/1uoHeSk42F3wwTaFrtqH-FA 提取码：nnoq 可以使用我打包的， — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

链接：https://pan.baidu.com/s/16t2SDevyRzmGoleuI6kJvQ
提取码：5x5d
刚才发发错了，现在是正确的，尴尬了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhbdesign** [comment]
你这个是很早的bug，我发的包已经修复了

**Comment by zhbdesign** [comment]
如果有问题，下载我的全量包，
链接：https://pan.baidu.com/s/1g0s41jslF2e4bu9siZBDHw 
提取码：6j9r

**Comment by zjw-zjw** [comment]
收到，我先单独替换这个mongodbreader 的试试。感谢


| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/18/2021 ***@***.***> wrote：

如果有问题，下载我的全量包，
链接：https://pan.baidu.com/s/1g0s41jslF2e4bu9siZBDHw
提取码：6j9r

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjw-zjw** [comment]
你好，我替换之后，出现了这个方法找不到的问题：

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NoSuchMethodError: com.google.common.base.Platform.stringIsNullOrEmpty(Ljava/lang/String;)Z

请问是否需要全部替换呢


| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/18/2021 ***@***.***> wrote：

如果有问题，下载我的全量包，
链接：https://pan.baidu.com/s/1g0s41jslF2e4bu9siZBDHw
提取码：6j9r

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjw-zjw** [comment]
这是报错信息： 
java.lang.NoSuchMethodError: com.google.common.base.Platform.stringIsNullOrEmpty(Ljava/lang/String;)Z
at com.google.common.base.Strings.isNullOrEmpty(Strings.java:68) ~[guava-29.0-jre.jar:na]
at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.init(MongoDBReader.java:72) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]


| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/18/2021 ***@***.***> wrote：

如果有问题，下载我的全量包，
链接：https://pan.baidu.com/s/1g0s41jslF2e4bu9siZBDHw
提取码：6j9r

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhbdesign** [comment]
链接：https://pan.baidu.com/s/151vHKZLS6I8PVXyb_Shp6Q 
提取码：38zn，这是mongoreader的包

链接：https://pan.baidu.com/s/1yDMnuXnn0Y7qH6cGf4M_xA 
提取码：ssup，这是dataX全量包，

之前出现的问题已解决，是包冲突问题
你直接使用，有问题反馈

**Comment by zjw-zjw** [comment]
非常感谢，这次可以了。单独替换的mongoreader插件。


| |
郑杰文
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/22/2021 ***@***.***> wrote：

链接：https://pan.baidu.com/s/151vHKZLS6I8PVXyb_Shp6Q
提取码：38zn，这是mongoreader的包

链接：https://pan.baidu.com/s/1yDMnuXnn0Y7qH6cGf4M_xA
提取码：ssup，这是dataX全量包，

之前出现的问题已解决，是包冲突问题
你直接使用，有问题反馈

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
