### ISSUE TITLE
整表同步oracle报如下错误，该如何解决

### ISSUE THREAD

**Issue by hlzhu1983** [alibaba/DataX#125]
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-07], Description:[读取数据库数据失败. 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from table 具体错误信息为：java.sql.SQLException: ORA-01427: single-row subquery returns more than one row

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:93) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:220) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:110) ~[oraclereader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by zhangzaki** [comment]
sql写的有问题，标量只查询返回多行了吧

**Comment by wangbaosun** [comment]
请教个问题啊，datax oracle到oracle同步的 一个job中怎样配置多表同步啊？，文档说支持配置多表，但是我没有同步成功啊
