### ISSUE TITLE
关于ftpreader的getinputstream的异常

### ISSUE THREAD

**Issue by zhaowwwjian** [alibaba/DataX#1279]
我的写法：
1、在配置文件中追加了索引文件
2、在task的prepare进行索引读取
3、在recordsender进行数据文件的读取。

目前问题在于ftpHelper.getInputStream(fileName) 有缺陷。
会导致在步骤3中。
```
 Description:[出现运行时异常, 请联系我们]. - 运行时错误, 请联系我们 - java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.readIndexFromStream(UnstructuredStorageReaderUtil.java:262)
        at com.alibaba.datax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:266)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:748)

```

sftp不受影响。

**Comment by kaxiwa** [comment]
有解决方法嘛 大佬
