### ISSUE TITLE
web登录报错

### ISSUE THREAD

**Issue by Myshiner** [alibaba/DataX#1304]
服务器配置2C 2.5GB
datax和datax-web安装完了，登录web用的账号密码是admin/123456，直接提示密码错误，看了日志报错如下：
2022-02-11 10:36:59,565 INFO [datax-web, executor ExecutorRegistryThread] c.w.d.c.t.ExecutorRegistryThread [ExecutorRegistryThread.java : 53] >>>>>>>>>>> datax-web registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='datax-executor', registryValue='192.168.56.10:9999', cpuUsage='2.94', memoryUsage='76.7', loadAverage='0.03'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Connection refused (Connection refused)), for url : http://192.168.56.10:8080/api/registry, content=null]
2022-02-11 10:37:29,569 ERROR [datax-web, executor ExecutorRegistryThread] c.w.d.c.u.JobRemotingUtil [JobRemotingUtil.java : 106] Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at com.wugui.datatx.core.util.JobRemotingUtil.postBody(JobRemotingUtil.java:54)
        at com.wugui.datatx.core.biz.client.AdminBizClient.registry(AdminBizClient.java:47)
        at com.wugui.datatx.core.thread.ExecutorRegistryThread.lambda$start$0(ExecutorRegistryThread.java:47)
        at java.lang.Thread.run(Thread.java:748)

**Comment by TrafalgarLuo** [comment]
并非这里模块的问题
