### ISSUE TITLE
【pref】是否可以在打包的时候过滤掉/datax/plugin目录及子目录下面的以._开头的隐藏文件？

### ISSUE THREAD

**Issue by liqiquan** [alibaba/DataX#1317]
Download the release package of datax, and run it in the Linux environment after unpacking, and the following error will be reported. Delete the files starting with ._ in the /datax/plugin directory and subdirectories, and then it can be executed normally. Is it possible to filter out these hidden files starting with ._ when packaging?
下载datax的release包，解包后在linux环境执行运行，会报下面的错误。把/datax/plugin目录及子目录下面的以._开头的文件删除，删除后即可正常执行。是否可以在打包的时候就过滤掉这些._开头的隐藏文件？

1. The error is as follows：
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/datax/plugin/reader/._postgresqlreader/plugin.json]不存在. 请检查您的配置文件.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.common.util.Configuration.from(Configuration.java:95)
	at com.alibaba.datax.core.util.ConfigParser.parseOnePluginConfig(ConfigParser.java:153)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:125)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

2. The delete command is as follows:
    rm -rf datax/plugin/._reader
    rm -rf datax/plugin/._writer
    
    rm -rf datax/plugin/reader/._*
    rm -rf datax/plugin/writer/._*

**Comment by TrafalgarLuo** [comment]
没有问题，近期的更新中会解决这个问题

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
