### ISSUE TITLE
下载安装包后，linux执行报错

### ISSUE THREAD

**Issue by zhilinLiu** [alibaba/DataX#1347]
[root@bigdata-3 bin]# ./datax.py ../job/job.json 

DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.

2022-04-20 12:14:44.698 [main] WARN  ConfigParser - 插件[streamreader,streamwriter]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/home/datax/plugin/reader/._cassandrareader/plugin.json]不存在. 请检查您的配置文件. 
2022-04-20 12:14:45.704 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/home/datax/plugin/reader/._cassandrareader/plugin.json]不存在. 请检查您的配置文件.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.common.util.Configuration.from(Configuration.java:95)
	at com.alibaba.datax.core.util.ConfigParser.parseOnePluginConfig(ConfigParser.java:153)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:125)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by liushuainudt** [comment]
Delete the macos files by rm -rf .* in directory reader and writer

**Comment by AllinProgram** [comment]
如果你使用的是ob，本地打包吧

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
