### ISSUE TITLE
adswriter Column ''erp'' cannot be resolved

### ISSUE THREAD

**Issue by zhuweijin** [alibaba/DataX#1350]
mysql 5.6
python 3.8

"writer": {
                "name": "adswriter",
                "parameter": {
                    "writeMode": "insert",
                    "url": "***.ads.aliyuncs.com:3306",
                    "schema": "erp",
                    "table": "***",
                    "column": ["*"],
                    "username": "***",
                    "password": "***",
                    "lifeCycle": 2
                }
            }

报错信息：
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[AdsWriter-11], Description:[获取ADS table原信息失败].  - com.alibaba.datax.plugin.writer.adswriter.AdsException: Code=-999 Message=[20038, 2022042117001319216811904003453127484] : line 0:1: Column ''erp'' cannot be resolved
	at com.alibaba.datax.plugin.writer.adswriter.load.AdsHelper.getTableInfo(AdsHelper.java:172)
	at com.alibaba.datax.plugin.writer.adswriter.insert.AdsInsertUtil.getAdsTableColumnNames(AdsInsertUtil.java:53)
	at com.alibaba.datax.plugin.writer.adswriter.AdsWriter$Job.init(AdsWriter.java:83)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.sql.SQLException: [20038, 2022042117001319216811904003453127484] : line 0:1: Column ''erp'' cannot be resolved
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2783)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1569)
	at com.alibaba.datax.plugin.writer.adswriter.load.AdsHelper.getTableInfo(AdsHelper.java:126)
	... 8 more
 - com.alibaba.datax.plugin.writer.adswriter.AdsException: Code=-999 Message=[20038, 2022042117001319216811904003453127484] : line 0:1: Column ''erp'' cannot be resolved
	at com.alibaba.datax.plugin.writer.adswriter.load.AdsHelper.getTableInfo(AdsHelper.java:172)
	at com.alibaba.datax.plugin.writer.adswriter.insert.AdsInsertUtil.getAdsTableColumnNames(AdsInsertUtil.java:53)
	at com.alibaba.datax.plugin.writer.adswriter.AdsWriter$Job.init(AdsWriter.java:83)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by zhuweijin** [comment]
INFO  AdsHelper - 检查列信息sql语句:select ordinal_position,column_name,data_type,type_name,column_comment from information_schema.columns where lower(table_schema) = `'erp'` and lower(table_name) = `'ods_brand'` order by ordinal_position
 
 配置文件中"schema": "erp",
 这里执行日志里面转成了lower(table_schema) = `'erp'`
 这个sql在adb里面也是无法执行的，lower(table_schema) = 'erp' 就可以执行了，
是不是哪个配置文件不对

**Comment by zhuweijin** [comment]
adswriter/src/main/java/com/alibaba/datax/plugin/writer/adswriter/load/AdsHelper.java 124行，直接改代码
"select ordinal_position,column_name,data_type,column_comment from information_schema.columns where table_schema = '%s' and table_name = '%s' order by ordinal_position"
