### ISSUE TITLE
DataX同步单表数据到Doris，写入时报错内存溢出

### ISSUE THREAD

**Issue by libra612** [alibaba/DataX#1376]
2022-05-24 17:39:22.738 [job-0] INFO  StandAloneJobContainerCommunicator - Total 119648 records, 37126013 bytes | Speed 400.76KB/s, 1216 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.676s |  All Task WaitReaderTime 127.162s | Percentage 0.00%
2022-05-24 17:39:22.750 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding$StringEncoder.encode(Unknown Source) ~[na:1.8.0_331]
	at java.lang.StringCoding.encode(Unknown Source) ~[na:1.8.0_331]
	at java.lang.StringCoding.encode(Unknown Source) ~[na:1.8.0_331]
	at java.lang.String.getBytes(Unknown Source) ~[na:1.8.0_331]
	at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterEmitter.doHttpPut(DorisWriterEmitter.java:206) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterEmitter.doStreamLoad(DorisWriterEmitter.java:105) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.flush(DorisWriter.java:108) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.startWrite(DorisWriter.java:92) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_331]
2022-05-24 17:39:32.744 [job-0] INFO  StandAloneJobContainerCommunicator - Total 119648 records, 37126013 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.676s |  All Task WaitReaderTime 127.162s | Percentage 0.00%
2022-05-24 17:39:32.746 [job-0] ERROR JobContainer - 运行scheduler 模式[standalone]出错.
2022-05-24 17:39:32.752 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-13], Description:[DataX插件运行时出错, 具体原因请参看DataX运行结束时的错误诊断信息 .].  - java.lang.OutOfMemoryError: Java heap space

**Comment by TrafalgarLuo** [comment]
./bin/datax.py  job.json  --jvm="-Xmx1g -Xms1g"

可以在命令行指定jvm参数，jvm参数中可以控制进程对内存的占用，比如 -Xmx、-Xms等

另外，写目标端可以看下 batchSize 大小，过大的batchSize会占用更多内存
