### ISSUE TITLE
dataxweb 运行报 ava.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job

### ISSUE THREAD

**Issue by yangtiezhu** [alibaba/DataX#1389]
022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:57.989 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:57.990 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:57.990 [main] INFO  JobContainer - DataX jobContainer starts job.
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:57.992 [main] INFO  JobContainer - Set jobId = 0
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:57.998 [job-0] ERROR JobContainer - Exception when job run
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] java.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.clickhousereader.ClickHouseReader$Job.init(ClickHouseReader.java:30) ~[clickhousereader-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_211]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_211]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_211]
2022-06-07 12:28:57 [AnalysisStatistics.analysisStatisticsLog-53] 	... 7 common frames omitted
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:58.001 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 2022-06-07 12:28:58.003 [job-0] ERROR Engine - 
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 经DataX智能分析,该任务最可能的错误原因是:
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.clickhousereader.ClickHouseReader$Job.init(ClickHouseReader.java:30)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	... 7 more
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53]  - java.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.clickhousereader.ClickHouseReader$Job.init(ClickHouseReader.java:30)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	... 7 more
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.clickhousereader.ClickHouseReader$Job.init(ClickHouseReader.java:30)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	... 3 more
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 	... 7 more
2022-06-07 12:28:58 [AnalysisStatistics.analysisStatisticsLog-53] 
2022-06-07 12:28:58 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null]
2022-06-07 12:28:58 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish

**Comment by TrafalgarLuo** [comment]
尝试下最近的datax 构建源码，或者首页下周安装包，尝试下
