### ISSUE TITLE
Oracle 19c -> Oracle 19c，数据库断开链接

### ISSUE THREAD

**Issue by tongYuSir** [alibaba/DataX#1452]
`[INFO] 2022-07-12 20:11:27.046 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.datax.DataxTask:[66] - -> 2022-07-12 20:11:26.429 [0-0-0-writer] WARN CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:IO Error: Connection timed out (Read failed)
2022-07-12 20:11:26.436 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.]. - java.sql.SQLRecoverableException: Closed Connection
at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3921)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:377)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:309)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:337)
at com.alibaba.datax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:80)
at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
at java.lang.Thread.run(Thread.java:748)
- java.sql.SQLRecoverableException: Closed Connection
at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3921)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:377)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:309)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:337)
at com.alibaba.datax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:80)
at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
at java.lang.Thread.run(Thread.java:748)`

**Comment by tongYuSir** [comment]
不知道是什么问题导致的，在11g下面就没问题，一开始以为是网络问题，可是batchsize改成10也不行，有没有大佬遇到过，求解

**Comment by daibowen0718** [comment]
换高版本的oracle驱动试试

**Comment by tongYuSir** [comment]
> 换高版本的oracle驱动试试

好的，谢谢，我试一下

**Comment by stupidxian** [comment]
> > 换高版本的oracle驱动试试
> 
> 好的，谢谢，我试一下

请问成功了吗

**Comment by tongYuSir** [comment]
> > > 换高版本的oracle驱动试试
> > 
> > 
> > 好的，谢谢，我试一下
> 
> 请问成功了吗

没有，我调整了i下思路，改了下源码，从datax报错的地方加了个trucatch ，从catch里面又重新创建了一下链接。
