### ISSUE TITLE
releases 202205 有bug ?

### ISSUE THREAD

**Issue by EminemJK** [alibaba/DataX#1465]
https://github.com/alibaba/DataX/releases/tag/datax_v202205
下载releases datax_v202205 后打包，不支持clickhousewrite，发生错误：
```
2022-08-05 09:01:45.133 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库写入这种字段类型. 字段名:[CreateTime], 字段类型:[1111], 字段Java类型:[DateTime64(0, 'Asia/Shanghai')]. 请修改表中该字段的类型或者不同步该字段.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:541) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:353) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315) ~[clickhousewriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库写入这种字段类型. 字段名:[CreateTime], 字段类型:[1111], 字段Java类型:[DateTime64(0, 'Asia/Shanghai')]. 请修改表中该字段的类型或者不同步该字段.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:541)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:353)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
	at java.lang.Thread.run(Thread.java:748)
^C[Error] DataX receive unexpected signal 2, starts to suicide.
```
之前的版本是可以

**Comment by zhaoyvli** [comment]
请问之前的那个版本可以，我也遇到了这个问题

**Comment by EminemJK** [comment]
> 请问之前的那个版本可以，我也遇到了这个问题

没有区别版本，之前可以的版本是在21年4月1号下载main版本的代码直接编译了。

**Comment by zhaoyvli** [comment]
您那保留的还有旧版本的代码，可否分享参考一下

**Comment by dingxiaobo** [comment]
@MrZhao1024B @EminemJK 

感谢反馈，问题已修复： #1540 

在下一个release之前，可以先自行从 master 打包使用

**Comment by MrZhao1024B** [comment]
@dingxiaobo 我测试发现，同步数据到clickhouse的datetime64类型，会丢失时间经度

**Comment by zhaoyvli** [comment]
@dingxiaobo 同步数据到clickhouse的datetime64类型，会丢失精度
sqlserver原表字段类型：datetime(3)
![image](https://user-images.githubusercontent.com/60651981/195486370-7e7ffb3f-3c1b-458b-bf14-ec4dbcbc35ce.png)
clickhouse字段类型：datetime64
![image](https://user-images.githubusercontent.com/60651981/195486907-e21dab59-46f7-4ec2-bf82-d0781295cca0.png)
