### ISSUE TITLE
请问ftpreader读取目录下zip压缩文件报错问题

### ISSUE THREAD

**Issue by ankerzhu** [alibaba/DataX#1468]
用ftpreader读取目录下zip文件列表报以下错误，是什么问题，可以解决吗？（即使是可以跳过这些有问题的文件也行）
com.alibaba.datax.common.exception.DataXException: Code:[UnstructuredStorageReader-09], Description:[您配置的文件在读取时出现IO异常.]. - 
读取文件错误 : [xxx.zip] - 
java.util.zip.ZipException: invalid entry size (expected 4294967295 but got 4391222286 bytes)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:384)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.ZipCycleInputStream.read(ZipCycleInputStream.java:44)
	at java.io.InputStream.read(InputStream.java:170)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at com.csvreader.CsvReader.checkDataLength(Unknown Source)
	at com.csvreader.CsvReader.readRecord(Unknown Source)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.splitBufferedReader(UnstructuredStorageReaderUtil.java:72)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:288)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.readFromStream(UnstructuredStorageReaderUtil.java:214)
	at com.alibaba.datax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:244)
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dingxiaobo** [comment]
jdk8 暂不支持4GB以上的压缩文件
