### ISSUE TITLE
datax_v202205版本 clickhousewriter问题

### ISSUE THREAD

**Issue by EminemJK** [alibaba/DataX#1474]
从SQL Server抽取数据到clickhouse，发现之前的版本没有问题，最新的版本v202205提示 如下信息：
sql server的ID 字段为： uniqueidentifier
clickhouse对应为：UUID

具体报错内容：
```
2022-08-09 16:54:59.324 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库写入这种字段类型. 字段名:[ID], 字段类型:[1111], 字段Java类型:[UUID]. 请修改表中该字段的类型或者不同步该字段.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:541) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:353) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:291) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315) ~[clickhousewriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_281]
2022-08-09 16:55:03.752 [job-0] INFO  StandAloneJobContainerCommunicator - Total 50688 records, 44031300 bytes | Speed 4.20MB/s, 5068 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.007s |  All Task WaitReaderTime 5.513s | Percentage 0.00%
2022-08-09 16:55:03.752 [job-0] ERROR JobContainer - 运行scheduler 模式[standalone]出错.
2022-08-09 16:55:03.753 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库写入这种字段类型. 字段名:[ID], 字段类型:[1111], 字段Java类型:[UUID]. 请修改表中该字段的类型或者不同步该字段.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:541) ~[na:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406) ~[na:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:353) ~[na:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:291) ~[na:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) ~[na:na]
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315) ~[na:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_281]
2022-08-09 16:55:03.753 [job-0] INFO  StandAloneJobContainerCommunicator - Total 50688 records, 44031300 bytes | Speed 41.99MB/s, 50688 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.007s |  All Task WaitReaderTime 5.513s | Percentage 0.00%
2022-08-09 16:55:03.754 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库写入这种字段类型. 字段名:[ID], 字段类型:[1111], 字段Java类型:[UUID]. 请修改表中该字段的类型或者不同步该字段.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:541)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:353)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:291)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by dingxiaobo** [comment]
@EminemJK

感谢反馈，问题已修复： https://github.com/alibaba/DataX/pull/1540

在下一个release之前，可以先自行从 master 打包使用
