### ISSUE TITLE
mysql读取，写入clickhouse报错

### ISSUE THREAD

**Issue by ChrisBamaofan** [alibaba/DataX#1484]
2022-08-19 06:30:13.744 [58-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:Transactions are not supported
2022-08-19 06:30:13.749 [58-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLException: Cannot rollback when auto-commit is enabled
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:234)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:361)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
        at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:750)
 - java.sql.SQLException: Cannot rollback when auto-commit is enabled
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:234)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:361)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
        at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:750)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:302) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315) ~[clickhousewriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_322]
Caused by: java.sql.SQLException: Cannot rollback when auto-commit is enabled
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:234) ~[clickhouse-jdbc-0.3.2.jar:clickhouse-jdbc 0.3.2 (revision: 567e14d)]
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:361) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        ... 4 common frames omitted
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLException: Cannot rollback when auto-commit is enabled
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:234)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:361)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
        at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Task.startWrite(ClickhouseWriter.java:315)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:750)
 - java.sql.SQLException: Cannot rollback when auto-commit is enabled

**Comment by dingxiaobo** [comment]
@ChrisBamaofan 

感谢反馈，问题已修复： #1540

在下一个release之前，可以先自行从 master 打包使用
