### ISSUE TITLE
python3.10.x执行python xxx\datax\bin\datax.py xxx\job\job.json自检报错

### ISSUE THREAD

**Issue by Ryoui** [alibaba/DataX#1498]
直接用工具和自己编译都报：
`2022-08-29 18:11:55.995 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-03], Description:[DataX寮曟搸閰嶇疆閿欒锛岃闂閫氬父鏄敱浜嶥ataX瀹夎閿欒寮曡捣锛岃鑱旂郴鎮ㄧ殑杩愮淮瑙ｅ喅 .].  - 鍦ㄦ湁鎬籦ps闄愰€熸潯浠朵笅锛屽崟涓猚hannel鐨刡ps鍊 间笉鑳戒负绌猴紝涔熶笉鑳戒负闈炴鏁?
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:430) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:387) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:93) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:175) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:208) [datax-core-0.0.1-SNAPSHOT.jar:na]

2022-08-29 18:11:56.003 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-08-29 18:11:56.004 [job-0] ERROR Engine -

缁廌ataX鏅鸿兘鍒嗘瀽,璇ヤ换鍔℃渶鍙兘鐨勯敊璇師鍥犳槸:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-03], Description:[DataX寮曟搸閰嶇疆閿欒锛岃闂閫氬父鏄敱浜嶥ataX瀹夎閿欒寮曡捣锛岃鑱旂郴鎮ㄧ殑杩愮淮瑙ｅ喅 .].  - 鍦ㄦ湁鎬籦ps闄愰€熸潯浠朵笅锛屽崟涓猚hannel鐨刡ps鍊 间笉鑳戒负绌猴紝涔熶笉鑳戒负闈炴鏁?
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30)
        at com.alibaba.datax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:430)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:387)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:93)
        at com.alibaba.datax.core.Engine.entry(Engine.java:175)
        at com.alibaba.datax.core.Engine.main(Engine.java:208)`

**Comment by daice3** [comment]
datax.py 里print的用法太老了
