### ISSUE TITLE
mysql读取，写入doris报错

### ISSUE THREAD

**Issue by echobigdata** [alibaba/DataX#1501]
2022-09-05 17:17:05.545 [job-0] INFO  StandAloneJobContainerCommunicator - Total 1079 records, 103279 bytes | Speed 10.08KB/s, 107 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.060s |  All Task WaitReaderTime 0.028s | Percentage 0.00%
2022-09-05 17:17:05.545 [job-0] ERROR JobContainer - 运行scheduler 模式[standalone]出错.
2022-09-05 17:17:05.546 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterEmitter.doHttpPut(DorisWriterEmitter.java:219)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterEmitter.doStreamLoad(DorisWriterEmitter.java:105)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.flush(DorisWriter.java:121)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.startWrite(DorisWriter.java:111)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.ProtocolException: Content-Length header already present
        at org.apache.http.protocol.RequestContent.process(RequestContent.java:96)
        at org.apache.
![38E4EF6D-E8FF-43b2-A598-E7DFB9FF69D8](https://user-images.githubusercontent.com/97231854/188415817-692363cd-a5d0-469e-9f68-54f291fb8d34.png)
http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 8 more

**Comment by echobigdata** [comment]
doris中http协议和datax的有冲突，改一致就好了

**Comment by ppooii123** [comment]
> doris中http协议和datax的有冲突，改一致就好了

兄弟这个怎么修改

**Comment by subs-sun** [comment]
兄弟，这个怎么解决的
