### ISSUE TITLE
定时任务调用mysqlwrite同步数据,出现大量线程TIMED_WAITING,直至内存溢出

### ISSUE THREAD

**Issue by junhc** [alibaba/DataX#1516]
3904 threads with same stack trace
0-0-0-writer
PRIORITY : 5

THREAD ID : 0X00007FB0380B4000

NATIVE ID : 0X4A3C3

NATIVE ID (DECIMAL) : 304067

STATE : TIMED_WAITING

stackTrace:
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000beb5ef48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at com.alibaba.datax.core.transport.channel.memory.MemoryChannel.doPullAll(MemoryChannel.java:114)
at com.alibaba.datax.core.transport.channel.Channel.pullAll(Channel.java:150)
at com.alibaba.datax.core.transport.exchanger.BufferedRecordExchanger.receive(BufferedRecordExchanger.java:152)
at com.alibaba.datax.core.transport.exchanger.BufferedRecordExchanger.getFromReader(BufferedRecordExchanger.java:130)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:275)
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78)
at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
at java.lang.Thread.run(Thread.java:748)
Locked ownable synchronizers:
- None

**Comment by dingxiaobo** [comment]
reader把数据放入`MemoryChannel`，

writer从`MemoryChannel` 中获取数据。

当`MemoryChannel` 为空时，就会出现TIMED_WAITING的线程。

从现象上来看，是reader读到的数据比较大，堆内存中放不下，导致OOM，可以酌情调大堆内存参数

**Comment by junhc** [comment]
嗯..问题已解决了..由于reader线程发生异常..就没有往MemoryChannel写入数据..导致writer线程一直在等待...稍微修改了一下源码..

com.alibaba.datax.core.taskgroup.runner.ReaderRunner#run 方法的finally中加了一段逻辑..
// 新增标识..
boolean isTerminated = false;
try {
...
isTerminated = true;
...
} finally {
    // 如果Reader没有被终止, 需要手动终止, 否则Writer会一直等待..
    if (!isTerminated) {
        recordSender.terminate();
    }
}

> reader把数据放入`MemoryChannel`，
> 
> writer从`MemoryChannel` 中获取数据。
> 
> 当`MemoryChannel` 为空时，就会出现TIMED_WAITING的线程。
> 
> 从现象上来看，是reader读到的数据比较大，堆内存中放不下，导致OOM，可以酌情调大堆内存参数

**Comment by dingxiaobo** [comment]
> 嗯..问题已解决了..由于reader线程发生异常..就没有往MemoryChannel写入数据..导致writer线程一直在等待...稍微修改了一下源码..
> 
> com.alibaba.datax.core.taskgroup.runner.ReaderRunner#run 方法的finally中加了一段逻辑.. // 新增标识.. boolean isTerminated = false; try { ... isTerminated = true; ... } finally { // 如果Reader没有被终止, 需要手动终止, 否则Writer会一直等待.. if (!isTerminated) { recordSender.terminate(); } }
> 
> > reader把数据放入`MemoryChannel`，
> > writer从`MemoryChannel` 中获取数据。
> > 当`MemoryChannel` 为空时，就会出现TIMED_WAITING的线程。
> > 从现象上来看，是reader读到的数据比较大，堆内存中放不下，导致OOM，可以酌情调大堆内存参数

方便分享一下日志、jstack看看吗？

**Comment by junhc** [comment]
> 3904 threads with same stack trace

jstack统计后的日志已经贴了..主要是因为reader配置中的脚本有报错,产生的问题..
3904多个写线程TIMED_WAITING...
3904 threads with same stack trace....
0-0-0-writer...
