### ISSUE TITLE
同步sqlserver数据源报错

### ISSUE THREAD

**Issue by mingtu930** [alibaba/DataX#1573]
用datax从sqlserver查询数据源，大致SQL语句：
begin
 declare  @sd=cast(concat(convert(varchar(7),dateadd(day,-1,getdate()),120),'-01') as datetime);
 declare  @ed=cast(convert(varchar(10),dateadd(day,-1,getdate()),120) as datetime);
 CREATE TABLE #acc(
		subcom_code VARCHAR(10),
		acc_water INT
 )
.......
select * from #acc;
DROP TABLE #acc;
end

该sql语句段zai sqlserver客户端可以正常执行，并返回数据，使用datax执行报错信息如下：
com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'BEGIN' 附近有语法错误....

去掉begin和end后，也会提示关键字declare也会报错，可能是语法检查的问题

**Comment by mingtu930** [comment]
BEGIN
	SET NOCOUNT ON

	CREATE TABLE #acc(
		price_code INT ,
		price_list_id INT ,
		subcom_code VARCHAR(10),
		acc_check_money NUMERIC(18, 2),
		acc_water INT,
		acc_amount INT,
		acc_money NUMERIC(18, 2),
		balance_money NUMERIC(18, 2)
	)

	DECLARE @date_start DATETIME=concat(convert(varchar(4),dateadd(day,-1,getdate()),120),'-01-01'); --起始月份
	DECLARE @date_end DATETIME=concat(convert(varchar(7),dateadd(day,-1,getdate()),120),'-01');      --截止月份
	-- DECLARE @zhandian VARCHAR(300)=N'TQYY';	                                                         --站点
	DECLARE @is_zd VARCHAR(10)='true';
	DECLARE @is_fzd varchar(10)='true';
	
	DECLARE @date_now INT = CONVERT(INT,SUBSTRING(CONVERT(VARCHAR(10),dateadd(day,-1,getdate()),112),1,6));  --当前年月

	DECLARE @ycfs VARCHAR(10) ;
	
	IF(@is_zd='true')
	begin
	   set @ycfs='1';
	end
	
	IF(@is_fzd='true')
	begin
		set @ycfs='2';
	end
	
	IF(@is_fzd='true' and @is_zd='true')
	begin
		set @ycfs ='1,2';
	end

	IF SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6) >= @date_now --结束年月 = 当前年月
	BEGIN
		------------------ 查询当月汇总 ------------------
		DECLARE @billing_month_start VARCHAR(6) = SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6),
			@billing_month_end VARCHAR(6) = SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6)
	
		INSERT INTO #acc
		SELECT
			kf.PRICE_CODE,kf.PRICE_LIST_ID,kf.SUBCOM_CODE
			,kf.金额+ISNULL(hh.money,0) 金额
			,kf.水量+ISNULL(hh.water,0) 水量
			,kf.户数+ISNULL(hh.people,0) 户数
			,kf.账单金额+ISNULL(hh.ACC_MONEY,0) 账单金额,
			 kf.抵扣余额+ISNULL(hh.BALANCE_MONEY,0) 抵扣余额
		FROM 
		(
			SELECT 
				kz.PRICE_CODE,kz.PRICE_LIST_ID,kz.SUBCOM_CODE 
				,SUM(kz.ACC_CHECK_MONEY) 金额
				,SUM(kz.ACC_WATER) 水量
				,COUNT(kz.FEE_ID) 户数,
				SUM(kz.ACC_MONEY) 账单金额,
			    SUM(kz.BALANCE_MONEY) 抵扣余额
			FROM 
			(
				----------------- 开账、复核 -----------------
				SELECT ac.FEE_ID,ac.PRICE_CODE,ac.PRICE_LIST_ID,ac.SUBCOM_CODE,ac.CHECK_TIME,ac.ACC_CHECK_MONEY,ac.ACC_WATER,ac.MRECORD_ID,ac.METER_ID,ac.card_id,ex.METER_METHOD,
				ac.ACC_MONEY,ac.BALANCE-ac.LAST_BALANCE BALANCE_MONEY
				FROM CSM_BM..ACC_CHARGES ac (NOLOCK)
				left join csm_bm..CM_METERCARDS_EXTRA ex (nolock) on ex.card_id=ac.card_id
				WHERE ac.FEE_STATE = 0
					AND ac.LAST_FEE_ID = 0 --原账
					AND ac.BILLING_MONTH BETWEEN @billing_month_start AND @billing_month_end	
					AND ac.FEE_ID NOT IN (SELECT FEE_ID FROM CSM_BM..ACC_CHARGES(NOLOCK) WHERE SUBCOM_CODE = 'kkyy' AND  READ_DATE = '2020-07-01 00:00:00.000' AND BILLING_MONTH=202007)
				UNION ALL
				SELECT ac.FEE_ID,ac.PRICE_CODE,ac.PRICE_LIST_ID,ac.SUBCOM_CODE,ac.CHECK_TIME,ac.ACC_CHECK_MONEY,ac.ACC_WATER,ac.MRECORD_ID,ac.METER_ID,ac.card_id,ex.METER_METHOD
				,ac.ACC_MONEY,ac.BALANCE-ac.LAST_BALANCE BALANCE_MONEY
				FROM CSM_BM..ACC_CHARGES_TEMP ac (NOLOCK)
				left join csm_bm..CM_METERCARDS_EXTRA ex (nolock) on ex.card_id=ac.card_id
				WHERE ac.FEE_STATE = 0
					AND ac.LAST_FEE_ID = 0 --原账
					AND ac.BILLING_MONTH BETWEEN @billing_month_start AND @billing_month_end	
			)kz  
			
			
			LEFT JOIN CSM_BM..MR_RECORD mr (NOLOCK) ON mr.RECORD_ID = kz.MRECORD_ID
			WHERE mr.RECORD_TYPE <> 1 --去除加抄数据
			AND EXISTS(select 1 from (select SUBCOM_CODE from CSM_BM..CSM_SUBCOMPANIES where SUBCOM_PARENT_ID NOT IN(0,4)) s WHERE s.SUBCOM_CODE = kz.SUBCOM_CODE)
			and exists(select * from dbo.split(@ycfs,',') yc where yc.item=kz.METER_METHOD)
			GROUP BY kz.PRICE_CODE,kz.PRICE_LIST_ID,kz.SUBCOM_CODE 
			HAVING kz.PRICE_CODE <> 99999 AND kz.PRICE_CODE <> 221  
		)kf
		LEFT JOIN (
			SELECT 
				s.PRICE_CODE,s.PRICE_LIST_ID,s.SUBCOM_CODE,SUM(s.money) money,SUM(s.water) water,MAX(s.people) people,
				 SUM(acc.ACC_MONEY) ACC_MONEY,
				 SUM(acc.BALANCE-acc.LAST_BALANCE) BALANCE_MONEY
			FROM 
			(
				----------------- 混合用水的站点、用水性质、户数 -----------------
				SELECT 
					a.PRICE_CODE,a.PRICE_LIST_ID,b.SUBCOM_CODE,SUM(a.MONEY) money,MAX(a.WATER) water,COUNT(DISTINCT b.CARD_ID) people
					,b.FEE_ID,ROW_NUMBER() OVER(PARTITION BY b.FEE_ID ORDER BY a.PRICE_CODE desc) rn
				FROM CSM_BM.dbo.ACC_CHARGE_DETAIL_TEMP a  (NOLOCK)
				JOIN CSM_BM.dbo.ACC_CHARGES_TEMP b ON a.FEE_ID=b.FEE_ID
				LEFT JOIN CSM_BM..MR_RECORD mr (NOLOCK) ON mr.RECORD_ID = b.MRECORD_ID
				WHERE b.PRICE_CODE=99999 
					AND b.FEE_STATE = 0
					AND b.BILLING_MONTH BETWEEN @billing_month_start AND @billing_month_end
					AND mr.RECORD_TYPE <> 1 --去除加抄
				GROUP BY b.CARD_ID,a.PRICE_CODE,a.PRICE_LIST_ID,b.SUBCOM_CODE,b.FEE_ID
				UNION ALL
				SELECT 
					a.PRICE_CODE,a.PRICE_LIST_ID,b.SUBCOM_CODE,SUM(a.MONEY) money,MAX(a.WATER) water,COUNT(DISTINCT b.CARD_ID) people
					,b.FEE_ID,ROW_NUMBER() OVER(PARTITION BY b.FEE_ID ORDER BY a.PRICE_CODE desc) rn
				FROM CSM_BM.dbo.ACC_CHARGE_DETAIL a (NOLOCK) 
				JOIN CSM_BM.dbo.ACC_CHARGES b (NOLOCK) ON a.FEE_ID=b.FEE_ID
				LEFT JOIN CSM_BM..MR_RECORD mr (NOLOCK) ON mr.RECORD_ID = b.MRECORD_ID
				WHERE b.PRICE_CODE=99999 
					AND b.FEE_STATE = 0
					AND b.BILLING_MONTH BETWEEN @billing_month_start AND @billing_month_end
					AND mr.RECORD_TYPE <> 1 --去除加抄
					AND b.FEE_ID NOT IN (SELECT FEE_ID FROM CSM_BM..ACC_CHARGES(NOLOCK) WHERE SUBCOM_CODE = 'kkyy' AND  READ_DATE = '2020-07-01 00:00:00.000' AND BILLING_MONTH=202007)--剔除坑口塘2020-07-01抄表开账的数据
				GROUP BY b.CARD_ID ,a.PRICE_CODE,a.PRICE_LIST_ID,b.SUBCOM_CODE,b.FEE_ID
			) s 
			INNER JOIN CSM_BM..ACC_CHARGES acc(NOLOCK) ON acc.FEE_ID = s.FEE_ID AND s.rn=1
			GROUP BY s.PRICE_CODE,s.PRICE_LIST_ID,s.SUBCOM_CODE
		) hh ON hh.PRICE_CODE = kf.PRICE_CODE AND hh.PRICE_LIST_ID = kf.PRICE_LIST_ID AND hh.subcom_code = kf.SUBCOM_CODE
		
	END


	DECLARE @start_month VARCHAR(10) = SUBSTRING(CONVERT(VARCHAR(10),@date_start,112),1,6)
	DECLARE @end_month VARCHAR(10)  

	IF (SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6) >= @date_now AND @date_start < @date_end)
	BEGIN
		SET @end_month = SUBSTRING(CONVERT(VARCHAR(10),DATEADD(mm,-1,@date_end),112),1,6)
	END

	IF SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6) < @date_now
	BEGIN
		SET @end_month = SUBSTRING(CONVERT(VARCHAR(10),@date_end,112),1,6)
	END

	-------------------- 包含历史月份 --------------------
	INSERT INTO #acc
	SELECT 
		rs.PRICE_CODE,rs.PRICE_LIST_ID,
		rs.SUBCOM_CODE,
		MAX(rs.金额) 金额,
		MAX(rs.水量) 水量,			
		MAX(rs.户数) 户数,
		MAX(rs.账单金额) 账单金额,
		MAX(rs.抵扣余额) 抵扣余额
	FROM 
	(
		SELECT 
			rs.SUBCOM_CODE,rs.PRICE_CODE,rs.PRICE_LIST_ID,
			 SUM(rs.ACC_WATER +   IIF(RS.BILLING_MONTH >= 202001,ABS(ISNULL(rs.ADJUST_WATER,0)),0))     水量,
			 SUM(rs.ACC_CHECK_MONEY +   IIF(RS.BILLING_MONTH >= 202001,ABS(ISNULL(rs.ADJUST_MONEY,0)),0))     金额,
			SUM(rs.COUNTBS) 户数 ,
			SUM(rs.ACC_MONEY +   IIF(RS.BILLING_MONTH >= 202001,ABS(ISNULL(rs.ADJUST_MONEY,0)),0))    账单金额,
			SUM(ISNULL(rs.BALANCE_MONEY,0)) 抵扣余额
		FROM CSM_BM_REPORT.dbo.RPT_SumFeeWater rs
		WHERE rs.RECORD_TYPE <> 1 --去除加抄
			AND rs.PRICE_CODE <> 221 --去除区域流量计		
			AND RS.BILLING_MONTH BETWEEN @start_month AND @end_month
			AND EXISTS(select 1 from (select SUBCOM_CODE from CSM_BM..CSM_SUBCOMPANIES where SUBCOM_PARENT_ID NOT IN(0,4)) s WHERE s.SUBCOM_CODE = rs.SUBCOM_CODE)
		GROUP BY rs.SUBCOM_CODE,rs.PRICE_CODE,rs.PRICE_LIST_ID
	) rs 
	GROUP BY rs.PRICE_CODE,rs.PRICE_LIST_ID,rs.SUBCOM_CODE

------------------ 结果结算 ------------------
	SELECT convert(varchar(7),dateadd(day,-1,getdate()),120) month_id,
	acc.subcom_code,
	-- SUM(acc.acc_check_money) money,
	SUM(acc.acc_water) sl
	-- SUM(acc.acc_amount) amount,
	-- SUM(acc.acc_money) 账单金额,
	-- SUM(acc.balance_money) 抵扣余额
	FROM #acc acc
	LEFT JOIN (
		SELECT  pd.PRICE_CODE ,pd.PRICE_LIST_ID ,
		CASE WHEN SUM(pd.LEVEL_INDEX) <= 1 THEN CONVERT(VARCHAR(20), SUM(pd.PRICE)) ELSE '阶梯' END AS PRICE
		FROM CSM_BM..PRICE_DETAIL pd
		GROUP BY pd.PRICE_CODE ,pd.PRICE_LIST_ID
	) jg ON jg.PRICE_CODE = acc.price_code AND jg.PRICE_LIST_ID = acc.price_list_id
	GROUP BY acc.subcom_code
	ORDER BY convert(varchar(7),dateadd(day,-1,getdate()),120),acc.subcom_code

	DROP TABLE #acc

END

**Comment by mingtu930** [comment]
报错信息补充下：
[WARN] 2022-10-26 16:02:51.887 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.datax.DataxTask:[528] - syntax error, error in :'RGES ac (NOLOCK)
				left join csm_', expect ), actual (, pos 2067, line 68, column 34, token (
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'RGES ac (NOLOCK)
				left join csm_', expect ), actual (, pos 2067, line 68, column 34, token (
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:558)
	at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:566)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1003)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:993)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:161)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:368)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:48)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseTableSource(SQLSelectParser.java:1002)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseFrom(SQLSelectParser.java:993)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.query(SQLServerSelectParser.java:161)
	at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:368)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerSelectParser.select(SQLServerSelectParser.java:48)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:785)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerExprParser.primary(SQLServerExprParser.java:90)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:95)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseInsert0(SQLServerStatementParser.java:302)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseInsert0(SQLStatementParser.java:2912)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseInsert(SQLServerStatementParser.java:238)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:255)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:124)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseBlock(SQLServerStatementParser.java:499)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseStatementListDialect(SQLServerStatementParser.java:95)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:587)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseIf(SQLServerStatementParser.java:466)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseIf(SQLServerStatementParser.java:32)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:364)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:124)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseBlock(SQLServerStatementParser.java:499)
	at com.alibaba.druid.sql.dialect.sqlserver.parser.SQLServerStatementParser.parseStatementListDialect(SQLServerStatementParser.java:95)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:587)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:4469)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.tryGrammaticalAnalysisSqlColumnNames(DataxTask.java:482)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.parsingSqlColumnNames(DataxTask.java:452)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildDataxJobContentJson(DataxTask.java:277)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildDataxJsonFile(DataxTask.java:208)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:159)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2022-10-26 16:02:51.888 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.datax.DataxTask:[455] - try to execute sql analysis query column name
[WARN] 2022-10-26 16:02:51.901 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.datax.DataxTask:[559] - 关键字 'BEGIN' 附近有语法错误。
com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'BEGIN' 附近有语法错误。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:460)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:405)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:317)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.tryExecuteSqlResolveColumnNames(DataxTask.java:550)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.parsingSqlColumnNames(DataxTask.java:456)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildDataxJobContentJson(DataxTask.java:277)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildDataxJsonFile(DataxTask.java:208)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:159)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dingxiaobo** [comment]
sqlserver jdbc 不支持begin
