### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again 是什么原因

### ISSUE THREAD

**Issue by Jerryzhzy** [alibaba/DataX#1580]
2022-10-31 11:11:01.394 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(750) | task is now running, taskId = 107244, logId = 9674, PID = 31214, status = running.
2022-10-31 11:11:01.394 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(895) |
2022-10-31 11:11:01.394 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(896) | ##################### SHELL LOG BEGIN #######################
2022-10-31 11:11:01.445 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) |
2022-10-31 11:11:01.445 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
2022-10-31 11:11:01.445 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
2022-10-31 11:11:01.445 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) |
2022-10-31 11:11:01.445 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) |
2022-10-31 11:11:01.582 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | Error: A JNI error has occurred, please check your installation and try again
2022-10-31 11:11:01.583 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/datax/common/spi/ErrorCode
2022-10-31 11:11:01.583 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.Class.getDeclaredMethods0(Native Method)
2022-10-31 11:11:01.583 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2022-10-31 11:11:01.583 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.Class.getMethod0(Class.java:3018)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.Class.getMethod(Class.java:1784)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.common.spi.ErrorCode
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-10-31 11:11:01.584 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(899) | ... 7 more
2022-10-31 11:11:01.593 | INFO | c.c.a.c.w.s.t.e.TaskExecuteService(901) | ###################### SHELL LOG END ########################

**Comment by dingxiaobo** [comment]
看看是不是包编译的有问题，包不完整，jdk版本不是1.8 之类的
