### ISSUE TITLE
otsstreamreader找不到相应的类

### ISSUE THREAD

**Issue by chilishark27** [alibaba/DataX#1585]
这个问题该如何解决？
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.otsstreamreader.internal.OTSStreamReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
        at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.otsstreamreader.internal.OTSStreamReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
        at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:176)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
        at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.otsstreamreader.internal.OTSStreamReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
        ... 7 more

**Comment by dingxiaobo** [comment]
使用的是自己编译的DataX吗？
