### ISSUE TITLE
从starRcoks读取数据到mysql8.0报错

### ISSUE THREAD

**Issue by Horus-K** [alibaba/DataX#1699]
```
2023-03-01 19:03:15 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param:
2023-03-01 19:03:15 [BuildCommand.buildDataXParam-100] ------------------Command parameters:
2023-03-01 19:03:15 [ExecutorJobHandler.execute-57] ------------------DataX process id: 8877
2023-03-01 19:03:15 [ProcessCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.626 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.634 [main] INFO  Engine - the machine info  => 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	osInfo:	Oracle Corporation 1.8 25.333-b02
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	jvmInfo:	Linux amd64 3.10.0-1160.62.1.el7.x86_64
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	cpu num:	4
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	totalPhysicalMemory:	-0.00G
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	freePhysicalMemory:	-0.00G
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	maxFileDescriptorCount:	-1
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	currentOpenFileDescriptorCount:	-1
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	GC Names	[PS MarkSweep, PS Scavenge]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	MEMORY_NAME                    | allocation_size                | init_size                      
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Eden Space                  | 256.00MB                       | 256.00MB                       
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	Code Cache                     | 240.00MB                       | 2.44MB                         
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Survivor Space              | 42.50MB                        | 42.50MB                        
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Old Gen                     | 683.00MB                       | 683.00MB                       
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	Metaspace                      | -0.00MB                        | 0.00MB                         
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.654 [main] INFO  Engine - 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] {
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	"content":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"reader":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mysqlreader",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`id`",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`date`",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`name`"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"database":"test",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"jdbcUrl":"jdbc:mysql://192.168.14.252:9030/test",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"loadProps":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"column_separator":"\\x01",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"row_delimiter":"\\x02"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					},
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"loadUrl":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"192.168.14.252:8030"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"********************",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"splitPk":"",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"table":"starRocks_test1",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"root",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"where":""
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			},
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"writer":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mysqlwriter",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`id`",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`name`",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"`date`"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"connection":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 							"jdbcUrl":"jdbc:mysql://xxx:3306/suosi_dataworks_static?useSSL=false&com.mysql.jdbc.faultInjection.serverCharsetIndex=45",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 							"table":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 								"starrocks_test"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 							]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"****************",
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"preSql":[
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 						"truncate table starrocks_test"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"dataworks_dev"
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 				}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	],
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	"setting":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		"errorLimit":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"percentage":0.02,
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"record":0
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		},
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		"speed":{
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"byte":1048576,
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 			"channel":3
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] }
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.675 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.677 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.677 [main] INFO  JobContainer - DataX jobContainer starts job.
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.679 [main] INFO  JobContainer - Set jobId = 0
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.697 [job-0] ERROR JobContainer - Exception when job run
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] java.lang.NullPointerException: null
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.recognizeTableOrQuerySqlMode(OriginalConfPretreatmentUtil.java:239) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:56) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:37) ~[mysqlreader-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.703 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 2023-03-01 19:03:15.705 [job-0] ERROR Engine - 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 经DataX智能分析,该任务最可能的错误原因是:
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NullPointerException
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.recognizeTableOrQuerySqlMode(OriginalConfPretreatmentUtil.java:239)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:56)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:37)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53]  - java.lang.NullPointerException
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.recognizeTableOrQuerySqlMode(OriginalConfPretreatmentUtil.java:239)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:56)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:37)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.NullPointerException
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.recognizeTableOrQuerySqlMode(OriginalConfPretreatmentUtil.java:239)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:56)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:37)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 	... 3 more
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 测试！！！！！！！
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 测试打印java -server -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/datax/log -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/datax/log -Dloglevel=info -Dfile.encoding=UTF-8 -Dlogback.statusListenerClass=ch.qos.logback.core.status.NopStatusListener -Djava.security.egd=file:///dev/urandom -Ddatax.home=/usr/local/datax -Dlogback.configurationFile=/usr/local/datax/conf/logback.xml -classpath /usr/local/datax/lib/*:.  -Dlog.file.name=2cae8139cb7ab6c_conf com.alibaba.datax.core.Engine -mode standalone -jobid -1 -job /usr/local/datax-web/modules/datax-executor/jsonjobTmp-972e267a52dd4ba2b2cae8139cb7ab6c.conf
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] {'jvmParameters': '-Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/datax/log', 'loglevel': 'info', 'writer': None, 'jobid': '-1', 'remoteDebug': None, 'params': None, 'mode': 'standalone', 'reader': None}
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] ['/usr/local/datax-web/modules/datax-executor/bin/../jsonjobTmp-972e267a52dd4ba2b2cae8139cb7ab6c.conf']
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 1
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 可以从启动参数中获取到具体的
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] None
2023-03-01 19:03:15 [AnalysisStatistics.analysisStatisticsLog-53] 最后一条输出
2023-03-01 19:03:15 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null]
2023-03-01 19:03:15 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.

**Comment by Horus-K** [comment]
从datax -- >  starRcoks（starrockswriter） 是可以的，再写回来就报错了

**Comment by Horus-K** [comment]
starrocks表
CREATE TABLE `starRocks_test1` (
  `id` int(11) NOT NULL COMMENT "主键id",
  `date` datetime NULL COMMENT "",
  `name` varchar(255) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 8 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);
mysql表
CREATE TABLE `starrocks_test` (
  `id` int NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

**Comment by Horus-K** [comment]
已解决，把datax代码升级到master最新版本即可
