### ISSUE TITLE
Elasticsearch  ERROR RetryUtil - Exception when calling callable, 异常Msg:Connection reset java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by fang358229166** [alibaba/DataX#170]
问题如题，Elasticsearch  ERROR RetryUtil - Exception when calling callable, 异常Msg:Connection reset java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_171]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.jar:4.4]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.4.jar:4.4]
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:118) ~[jest-2.4.0.jar:na]
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:57) ~[jest-2.4.0.jar:na]
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESClient.bulkInsert(ESClient.java:220) ~[elasticsearchwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Task$2.call(ESWriter.java:400) ~[elasticsearchwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Task$2.call(ESWriter.java:397) ~[elasticsearchwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30) [datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Task.doBatchInsert(ESWriter.java:397) [elasticsearchwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Task.startWrite(ESWriter.java:283) [elasticsearchwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by Itmonkeyff** [comment]
请问这个问题解决了吗，怎么解决的麻烦讲一下

**Comment by fang358229166** [comment]
> 请问这个问题解决了吗，怎么解决的麻烦讲一下
版本问题，es兼容性做的不太好，我同步到高版本就没问题了

**Comment by Itmonkeyff** [comment]
已经解决了，谢谢了

**Comment by khan299** [comment]
如果不升级es版本，请问下怎么解决的？

**Comment by shanfasheng** [comment]
大佬们，怎么解决的啊，遇到同样的问题，es版本：7.15.1，求赐教
