### ISSUE TITLE
写入Doris失败:JSONObject cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by linggogo** [alibaba/DataX#1712]
1.  DataX最新版
2. Job配置文件如下：
```
{
    "job": {
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
                        "column": ["id",
                                   "schedule_id",
                                   "category",
                                   "match_id",
                                   "round",
                                   "live_round",
                                   "game_second",
                                   "create_time",
                                   "old_race_url",
                                   "match_type",
                                   "schedule_info",
                                   "left_team",
                                   "left_camp",
                                   "left_flags",
                                   "left_score",
                                   "left_gold",
                                   "left_gold_diff",
                                   "left_exp",
                                   "left_player",
                                   "left_banlist",
                                   "left_picklist",
                                   "left_destroy_tower_count",
                                   "left_destroy_barrack_count",
                                   "left_win",
                                   "right_team",
                                   "right_camp",
                                   "right_flags",
                                   "right_score",
                                   "right_gold",
                                   "right_gold_diff",
                                   "right_exp",
                                   "right_player",
                                   "right_banlist",
                                   "right_picklist",
                                   "right_destroy_tower_count",
                                   "right_destroy_barrack_count",
                                   "right_win"
                        
                        ],
                        "connection": [
                            {
                                "jdbcUrl": ["jdbc:mysql://xxx:3306/vp_dota"],
                                "table": ["game_dota_status"]
                            }
                        ],
                        "username": "canal",
                        "password": "xxx",
                        "where": ""
                    }
                },
                "writer": {
                    "name": "doriswriter",
                    "parameter": {
                        "loadUrl": ["192.168.78.101:8030"],
                        "column": [ {
                                                        "name":"id",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"schedule_id",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"category",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"match_id",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"round",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"live_round",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"game_second",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"create_time",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"old_race_url",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"match_type",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"schedule_info",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_team",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_camp",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_flags",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_score",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_gold",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_gold_diff",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_exp",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_player",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_banlist",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_picklist",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"left_destroy_tower_count",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_destroy_barrack_count",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"left_win",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_team",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_camp",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_flags",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_score",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_gold",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_gold_diff",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_exp",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_player",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_banlist",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_picklist",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"right_destroy_tower_count",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_destroy_barrack_count",
                                                        "type":"bigint"
                                                },
                                                {
                                                        "name":"right_win",
                                                        "type":"bigint"
                                                }
                        ],
                        "username": "root",
                        "password": "xxxxx",
                        "flushInterval":30000,
                        "connection": [
                          {
                            "jdbcUrl": "jdbc:mysql://xxxx/test_db",
                            "selectedDatabase": "test_db",
                            "table": ["game_dota_status"]
                          }
                        ],
                        "loadProps": {
                            "format": "json",
                            "strip_outer_array":"true",
                            "line_delimiter": "\\x02"
                        }
                    }
                }
            }
        ],
        "setting": {
            "speed": {
                "channel": "1"
            }
        }
    }
}```
4. 异常信息
2023-03-08 18:22:25.218 [job-0] ERROR JobContainer - Exception when job run
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_321]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_321]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_321]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_321]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_321]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_321]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_321]
        at com.alibaba.datax.plugin.writer.doriswriter.Keys.<init>(Keys.java:52) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Job.init(DorisWriter.java:49) ~[doriswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:93) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:175) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:208) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-03-08 18:22:25.226 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-03-08 18:22:25.228 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.alibaba.datax.plugin.writer.doriswriter.Keys.<init>(Keys.java:52)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Job.init(DorisWriter.java:49)
        at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:93)
        at com.alibaba.datax.core.Engine.entry(Engine.java:175)
        at com.alibaba.datax.core.Engine.main(Engine.java:208)
 - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.alibaba.datax.plugin.writer.doriswriter.Keys.<init>(Keys.java:52)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Job.init(DorisWriter.java:49)
        at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:93)
        at com.alibaba.datax.core.Engine.entry(Engine.java:175)
        at com.alibaba.datax.core.Engine.main(Engine.java:208)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
        at com.alibaba.datax.core.Engine.start(Engine.java:93)
        at com.alibaba.datax.core.Engine.entry(Engine.java:175)
        at com.alibaba.datax.core.Engine.main(Engine.java:208)
Caused by: java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.alibaba.datax.plugin.writer.doriswriter.Keys.<init>(Keys.java:52)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Job.init(DorisWriter.java:49)
        at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        ... 3 more

**Comment by linggogo** [comment]
mysql中text类型中存储的是json字符串  转doris string类型会有问题么

**Comment by liusanp** [comment]
看示例文档好像column里面应该是字段名列表

**Comment by dingxiaobo** [comment]
> 看示例文档好像column里面应该是字段名列表


正解
