### ISSUE TITLE
字段值超出100000字节出错

### ISSUE THREAD

**Issue by lmeroc** [alibaba/DataX#173]
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[UnstructuredStorageReader-09], Description:[您配置的文件在读取时出现IO异常.]. - 读取文件错误 : [/home/admin/cns-onlineroute-server/target/cns-onlineroute-server/db/server_route_db.csv] - java.io.IOException: Maximum column length of 100,000 exceeded in column 10 in record 1,975. Set the SafetySwitch property to false if you're expecting column lengths greater than 100,000 characters to avoid this error.
	at com.csvreader.CsvReader.readRecord(Unknown Source)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.splitBufferedReader(UnstructuredStorageReaderUtil.java:72)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:288)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.readFromStream(UnstructuredStorageReaderUtil.java:214)
	at com.alibaba.datax.plugin.reader.txtfilereader.TxtFileReader$Task.startRead(TxtFileReader.java:403)
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:302)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.readFromStream(UnstructuredStorageReaderUtil.java:214)
	at com.alibaba.datax.plugin.reader.txtfilereader.TxtFileReader$Task.startRead(TxtFileReader.java:403)
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Maximum column length of 100,000 exceeded in column 10 in record 1,975. Set the SafetySwitch property to false if you're expecting column lengths greater than 100,000 characters to avoid this error.
	at com.csvreader.CsvReader.readRecord(Unknown Source)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.splitBufferedReader(UnstructuredStorageReaderUtil.java:72)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:288)

**Comment by lidx246** [comment]
碰到了一样的问题。怎么解决？

**Comment by dataccs** [comment]
如果报java.io.IOException: Maximum column length of 100,000 exceeded in column...异常信息，说明数据源column字段长度超过了100000字符。

 需要在json的reader里增加如下配置
 ```json
 "csvReaderConfig":{
	"safetySwitch": false,
	"skipEmptyRecords": false,
	"useTextQualifier": false
 }
 ```
 safetySwitch = false;//单列长度不限制100000字符
