### ISSUE TITLE
Can't find bundle for base name com.alibaba.datax.common.util.LocalStrings, locale zh_CN

### ISSUE THREAD

**Issue by Sunshinezmh** [alibaba/DataX#1789]
java项目使用datax进行采集的时候，windows本地可以正常采集，部署到linux服务器上（使用docker部署）会报如下错误。datax的jar包是该项目的master分支上的代码。
日志信息：
2023-05-18 15:53:06.010 - INFO classification-grading-service [com.croot.classification.grading.service.controller.SysCollectDataController_lambda$fetchDbCollect$0] - datax采集的配置信息,["-job","datax/datax/mysql_postgre.json","-mode","standalone","-jobid","-1"]
2023-05-18 15:53:06.147 - INFO classification-grading-service [com.alibaba.datax.common.util.MessageSource_init] - JVM TimeZone: GMT+08:00, Locale: zh_CN
2023-05-18 15:53:06.148 - INFO classification-grading-service [com.alibaba.datax.common.util.MessageSource_setEnvironment] - use Locale: zh_CN timeZone: sun.util.calendar.ZoneInfo[id="GMT+08:00",offset=28800000,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]
2023-05-18 15:53:06.152 - ERROR classification-grading-service [com.croot.classification.grading.service.controller.SysCollectDataController_lambda$fetchDbCollect$0] - Can't find bundle for base name com.alibaba.datax.common.util.LocalStrings, locale zh_CN

报错信息：
java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.common.util.LocalStrings, locale zh_CN
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46)
        at com.alibaba.datax.common.util.MessageSource.reloadResourceBundle(MessageSource.java:117)
        at com.alibaba.datax.core.Engine.entry(Engine.java:134)
        at com.croot.classification.grading.service.controller.SysCollectDataController.lambda$fetchDbCollect$0(SysCollectDataController.java:180)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by chengbinghan** [comment]
seem problem

**Comment by simsicon** [comment]
I am experiencing the same issue with 202308 release.

**Comment by xingwubiao** [comment]
![image](https://github.com/alibaba/DataX/assets/47996860/ec9b92ad-dbcf-4580-a112-f4a26e085226)
In the ClickhouseReader class, comment out the useless line:
private static MessageSource MESSAGE_SOURCE = MessageSource.loadResourceBundle(ClickhouseReader.class); 
then recompile,use the new jar  clickhousereader-0.0.1-SNAPSHOT.jar  replace the old :
datax/plugins/reader/clickhousereader/clickhousereader-0.0.1-SNAPSHOT.jar

**Comment by xingwb1** [comment]
In the ClickhouseReader class, comment out the useless line:
private static MessageSource MESSAGE_SOURCE = MessageSource.loadResourceBundle(ClickhouseReader.class); 
then recompile,use the new jar  clickhousereader-0.0.1-SNAPSHOT.jar  replace the old :
datax/plugins/reader/clickhousereader/clickhousereader-0.0.1-SNAPSHOT.jar

**Comment by chengbinghan** [comment]
> In the ClickhouseReader class, comment out the useless line: private static MessageSource MESSAGE_SOURCE = MessageSource.loadResourceBundle(ClickhouseReader.class); then recompile,use the new jar clickhousereader-0.0.1-SNAPSHOT.jar replace the old : datax/plugins/reader/clickhousereader/clickhousereader-0.0.1-SNAPSHOT.jar

thanks for your replay. i will try

**Comment by chengbinghan** [comment]
Anyway i think  office release should fix this issues. @DataX

**Comment by AWei6** [comment]
我也遇见了这个问题，刚下载并解压，执行第一个任务就报这个错（ClickHouse->Doris）

**Comment by fightinggg** [comment]
+1

**Comment by renyineng-tal** [comment]
clikchouse  reader报这个错误，求解决方案
