### ISSUE TITLE
202210版，安装包中无plugin文件夹

### ISSUE THREAD

**Issue by fupengzhou** [alibaba/DataX#1829]
[root@localhost DataX-datax_v202210]# python core/src/main/bin/datax.py  -r mysqlreader -w mysqlwriter

DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.

Please refer to the mysqlreader document:
     https://github.com/alibaba/DataX/blob/master/mysqlreader/doc/mysqlreader.md 

Please refer to the mysqlwriter document:
     https://github.com/alibaba/DataX/blob/master/mysqlwriter/doc/mysqlwriter.md 
 
Please save the following configuration as a json file and  use
     python {DATAX_HOME}/bin/datax.py {JSON_FILE_NAME}.json 
to run the job.

Read reader[mysqlreader] template error: can't find file /home/DataX-datax_v202210/core/src/main/plugin/reader/mysqlreader/plugin_job_template.json
Read writer[mysqlwriter] template error: : can't find file /home/DataX-datax_v202210/core/src/main/plugin/writer/mysqlwriter/plugin_job_template.json
Traceback (most recent call last):
  File "core/src/main/bin/datax.py", line 228, in <module>
    generateJobConfigTemplate(options.reader, options.writer)
  File "core/src/main/bin/datax.py", line 155, in generateJobConfigTemplate
    jobTemplate['job']['content'][0]['reader'] = readerPar
UnboundLocalError: local variable 'readerPar' referenced before assignment

**Comment by fupengzhou** [comment]
手动创建对应路径，并放置对应文件可解决
[root@localhost main]# tree plugin/
plugin/
├── reader
│   └── mysqlreader
│       └── plugin_job_template.json
└── writer
    └── mysqlwriter
        └── plugin_job_template.json
