### ISSUE TITLE
[Bug]判断是否为orc文件类型， 未捕获IndexOutOfBoundsException错误, 导致程序停止运行

### ISSUE THREAD

**Issue by mggger** [alibaba/DataX#1852]
如何复现：

1. 创建一个textfile表
```sql
CREATE TABLE test_hive_1 (
   d_ceshi1 STRING COMMENT '测试ces1',
   vc_birth STRING COMMENT '生日',
   c_cdata21 STRING COMMENT 'C_CDATA21',
   f_test0630_12321321 DECIMAL(38,15) COMMENT 'test063012321321业务分类（）*&……*（）&（）dklasfdsahfasdf3413431243431业务分类（）*&……*（）&（）dklasfdsahfasdf341343124',
   hive111 DECIMAL(38,15) COMMENT 'test07102test07102test07102test07102test07102test07102test07102test071021test07102test07102test07102',
   vc_test070101 STRING COMMENT 'test0701011',
   c_wbv STRING COMMENT '建设',
   l_total BIGINT COMMENT 'total',
   l_total_copy BIGINT COMMENT 'total_copy'
)
PARTITIONED BY (d_cdate1abcd STRING COMMENT '确认日期')
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\u0001'
STORED AS TEXTFILE
LOCATION 'hdfs://nameservice1/user/aresoft/hadoopData/model/ARESOFT/test_hive_1';
```

2. 写入数据
```sql
INSERT INTO TABLE test_hive_1
PARTITION (d_cdate1abcd='your_partition_value')
VALUES
  ('ces1_value', '生日_value', 'C_CDATA21_value', 123.456, 789.012, 'test070101_value', '建设_value', 100, 200);
```

3. 用datax读取
***

报错堆栈：
```
检查文件[hdfs://nameservice1/user/hive/warehouse/aresoft.db/test_hive_1/000000_0_copy_1]类型失败，目前支持ORC,SEQUENCE,RCFile,TEXT,CSV五种格式的文件,请检查您文件类型和文件是否正确。 - java.lang.IndexOutOfBoundsException
at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
at org.apache.hadoop.io.Text.decode(Text.java:389)   
at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.isORCFile(DFSUtil.java:593)        
at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.checkHdfsFileType(DFSUtil.java:534)
...
```

**Comment by FuYouJ** [comment]
你这个错我经常遇到，有时候是空间的问题，IndexOutOfBoundsException 是怎么引起的？

**Comment by FuYouJ** [comment]
你这个错我经常遇到，有时候是空文件的问题，IndexOutOfBoundsException 是怎么引起的？

**Comment by LitteCandy0511** [comment]
会在下个版本修复
