### ISSUE TITLE
数据从pg迁移到ase数据库，表中null值数据迁移的时候报错

### ISSUE THREAD

**Issue by bluee00** [alibaba/DataX#1857]
2023-07-27 18:22:59.753 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:JZ0SE: 为setObject()指定的对象类型无效(或为空对象)。
2023-07-27 18:22:59.775 [0-0-0-writer] ERROR StdoutPluginCollector - 
java.sql.SQLException: JZ0SE: 为setObject()指定的对象类型无效(或为空对象)。
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(ErrorMessage.java:832) ~[jconn4.jar:JDK 1.6/jdbcdev/Tue Jun 23 03:54:56 PDT 2020]
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setObject(SybPreparedStatement.java:1434) ~[jconn4.jar:JDK 1.6/jdbcdev/Tue Jun 23 03:54:56 PDT 2020]
	at com.alibaba.datax.plugin.reader.rdbmswriter.SubCommonRdbmsWriter$Task.fillPreparedStatementColumnType(SubCommonRdbmsWriter.java:45) ~[rdbmswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:406) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:380) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:362) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.rdbmswriter.RdbmsWriter$Task.startWrite(RdbmsWriter.java:86) [rdbmswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]

**Comment by bluee00** [comment]
配置如下所示，info列有null数据，不含info列不报错，包含info列就报如上错误
```
{
    "job": {
        "setting": {
            "speed": {
                "channel": 1
            }
        },
        "content": [
            {
                "reader": {
                    "name": "postgresqlreader",
                    "parameter": {
                        "username": "***",
                        "password": "***",
                        "where": "",
                        "column": ["id","name","info"],
                        "connection": [
                            {
                                "jdbcUrl": [
                                    "jdbc:postgresql://***:***/***"
                                ],
                                "table": ["md_company"]
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "rdbmswriter",
                    "parameter": {
                        "username": "***",
                        "password": "***",
                        "table": "portal_md_company",
                        "connection": [{
                            "jdbcUrl": "jdbc:sybase:Tds:***:***/***",
                            "table": ["portal_md_company"]
                        }],
                        "column": ["id","name","info"]
                    }
                }
            }
        ]
    }
}
```

**Comment by bluee00** [comment]
将rdbmswriter里的SubCommonRdbmsWriter第45行代码
```java
                    case Types.LONGNVARCHAR:
                    if (null == column.getRawData()) {
                        preparedStatement.setObject(columnIndex + 1, null);
                    } else {
                        preparedStatement.setString(columnIndex + 1,
                                column.asString());
                    }
                    break;
``` 
中的
                    preparedStatement.setObject(columnIndex + 1, null);
修改为
                    preparedStatement.setObject(columnIndex + 1, null, columnSqltype);
即可
是否会引入其他问题有待观察
