### ISSUE TITLE
v202306 版本没有打包 clickhousereader

### ISSUE THREAD

**Issue by johnlxi** [alibaba/DataX#1869]
从userGuid.md 中的工具包下载地址 https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/202306/datax.tar.gz 下载的 datax.tar.gz 中， 解压后 plugin/reader 目录中没有包含 clickhousereader 插件
此外，README.md 中的下载地址， 没有更新， 仍为 202303 版本

**Comment by FuYouJ** [comment]
可以试试自己本地编译。
1：打开package.xml，注释掉所有的插件。只留下自己需要的读写插件和datax核心模块[core,common,transform]
2:  pom文件也把那些注释掉。
3：运行  mvn -U clean package assembly:assembly -Dmaven.test.skip=true

**Comment by penglin358** [comment]
已经修复，请从最新的 https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/202308/datax.tar.gz  进行下载

**Comment by tuoluzhe8521** [comment]
打包后报错如下：
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98)
        at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:86)
        at com.alibaba.datax.core.Engine.entry(Engine.java:168)
        at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37)
        at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46)
        at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.<clinit>(ClickhouseReader.java:30)
        ... 12 more

**Comment by tuoluzhe8521** [comment]
> 打包后报错如下： 经DataX智能分析,该任务最可能的错误原因是: com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息 .]. - java.lang.ExceptionInInitializerError at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at java.lang.Class.newInstance(Class.java:442) at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98) at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661) at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) at com.alibaba.datax.core.Engine.start(Engine.java:86) at com.alibaba.datax.core.Engine.entry(Engine.java:168) at com.alibaba.datax.core.Engine.main(Engine.java:201) Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581) at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396) at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091) at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92) at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37) at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46) at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.(ClickhouseReader.java:30) ... 12 more

编译前将其他位置的LocalStrings.properties 复制到clickhousereader包里面即可
cp -R {YOUR_DATAX_HOME}/DataX/otsstreamreader/src/main/java/com/alibaba/datax/plugin/reader/otsstreamreader/internal/LocalStrings.properties {YOUR_DATAX_HOME}/DataX/clickhousereader/src/main/java/com/alibaba/datax/plugin/reader/clickhousereader
