### ISSUE TITLE
neo4jwriter报错，求大佬看看

### ISSUE THREAD

**Issue by aparrow** [alibaba/DataX#1907]
"writer":{
                                "name":"neo4jWriter",
                                "parameter":{
                                        "uri":"neo4j://*.*.*.*:7687",
                                        "username":"neo4j",
                                        "password":"*****",
                                        "database":"neo4j",
                                        "cypher":"unwind $batch as row create(n:Notificaton) set n.id = row.id,n.name = row.name,n.description = row.description",
                                        "batchDataVariableName":"batch",
                                        "batch_size":"20",
                                        "properties":[
                                                {
                                                        "name":"id",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"name",
                                                        "type":"string"
                                                },
                                                {
                                                        "name":"description",
                                                        "type":"string"
                                                }
                                        ]
                                }
                        }
这是writer，报错信息如下
2023-09-11 16:26:54.514 [job-0] ERROR JobContainer - Exception when job run
java.lang.NullPointerException: Cannot invoke "com.alibaba.datax.common.util.Configuration.clone()" because "this.jobConf" is null
        at com.alibaba.datax.plugin.writer.neo4jwriter.Neo4jWriter$Job.split(Neo4jWriter.java:32) ~[neo4jwriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:86) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:168) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:201) ~[datax-core-0.0.1-SNAPSHOT.jar:na]

**Comment by FuYouJ** [comment]
最新版本修复了。你拉下代码。改动就一行。

**Comment by FuYouJ** [comment]
> 最新版本修复了。你拉下代码。改动就一行。

@aparrow

**Comment by FuYouJ** [comment]
还有配置下划线，我检查了下是我的文档写混了，配置都是驼峰的。
batchSize
我后续改一下文档，sorry

**Comment by aparrow** [comment]
> 还有配置下划线，我检查了下是我的文档写混了，配置都是驼峰的。 batchSize 我后续改一下文档，sorry

好的，谢谢哥
