### ISSUE TITLE
使用transformer报错

### ISSUE THREAD

**Issue by yuebaiqaq** [alibaba/DataX#1916]
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
 - java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:284)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
[job-0] INFO com.alibaba.datax.core.statistics.container.communicator.job.StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[job-0] ERROR com.alibaba.datax.core.job.JobContainer - 运行scheduler 模式[standalone]出错.
[job-0] ERROR com.alibaba.datax.core.job.JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-13], Description:[DataX插件运行时出错, 具体原因请参看DataX运行结束时的错误诊断信息 .].  - java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
 - java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
	at com.alibaba.datax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:39)
	at com.alibaba.datax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:99)
	at com.alibaba.datax.core.job.JobContainer.schedule(JobContainer.java:535)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:119)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.asiainfo.Datax.main(Datax.java:35)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
	at com.alibaba.datax.core.transport.transformer.TransformerRegistry.<clinit>(TransformerRegistry.java:39)
	at com.alibaba.datax.core.util.TransformerUtil.buildTransformerInfo(TransformerUtil.java:50)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor.<init>(TaskGroupContainer.java:408)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:228)
	at com.alibaba.datax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilationFailedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
请问有人遇到过吗？怎么解决啊？

**Comment by FuYouJ** [comment]
大概是你写的脚本使用的类超出datax预设的规则了。
源码考虑了这些类
``` 
private String getGroovyRule(String expression, List<String> extraPackagesStrList) {
        StringBuffer sb = new StringBuffer();
        if(extraPackagesStrList!=null) {
            for (String extraPackagesStr : extraPackagesStrList) {
                if (StringUtils.isNotEmpty(extraPackagesStr)) {
                    sb.append(extraPackagesStr);
                }
            }
        }
        sb.append("import static com.alibaba.datax.core.transport.transformer.GroovyTransformerStaticUtil.*;");
        sb.append("import com.alibaba.datax.common.element.*;");
        sb.append("import com.alibaba.datax.common.exception.DataXException;");
        sb.append("import com.alibaba.datax.transformer.Transformer;");
        sb.append("import java.util.*;");
        sb.append("public class RULE extends Transformer").append("{");
        sb.append("public Record evaluate(Record record, Object... paras) {");
        sb.append(expression);
        sb.append("}}");

        return sb.toString();
    }
```java

**Comment by suiquantong** [comment]
我也遇到了这个问题 在找问题
