### ISSUE TITLE
latest version read from clickhouse error

### ISSUE THREAD

**Issue by yangyongyongyong** [alibaba/DataX#1917]
error:
`
(base) thomas990p@thomas990p datax % python ./bin/datax.py ./job/from-clickhouse.json 

DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.

2023-09-15 16:21:43.734 [main] INFO  MessageSource - JVM TimeZone: GMT+08:00, Locale: zh_CN
2023-09-15 16:21:43.735 [main] INFO  MessageSource - use Locale: zh_CN timeZone: sun.util.calendar.ZoneInfo[id="GMT+08:00",offset=28800000,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]
2023-09-15 16:21:43.742 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-09-15 16:21:43.744 [main] INFO  Engine - the machine info  => 

	osInfo:	Mac OS X aarch64 13.4.1
	jvmInfo:	Azul Systems, Inc. 1.8 25.362-b09
	cpu num:	8

	totalPhysicalMemory:	-0.00G
	freePhysicalMemory:	-0.00G
	maxFileDescriptorCount:	-1
	currentOpenFileDescriptorCount:	-1

	GC Names	[PS MarkSweep, PS Scavenge]

	MEMORY_NAME                    | allocation_size                | init_size                      
	PS Eden Space                  | 256.00MB                       | 256.00MB                       
	Code Cache                     | 128.00MB                       | 2.44MB                         
	Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
	PS Survivor Space              | 42.50MB                        | 42.50MB                        
	PS Old Gen                     | 683.00MB                       | 683.00MB                       
	Metaspace                      | -0.00MB                        | 0.00MB                         

2023-09-15 16:21:43.750 [main] INFO  Engine - 
{
	"setting":{
		"speed":{
			"byte":1048576
		},
		"errorLimit":{
			"record":0,
			"percentage":0.02
		}
	},
	"content":[
		{
			"reader":{
				"name":"clickhousereader",
				"parameter":{
					"username":"default",
					"password":"******",
					"column":[
						"device_id",
						"gmtBind"
					],
					"connection":[
						{
							"table":[
								"table1"
							],
							"jdbcUrl":[
								"jdbc:clickhouse://localhost:18123/tuya_basic?serverTimezone=Asia/Shanghai"
							]
						}
					]
				}
			},
			"writer":{
				"name":"streamwriter",
				"parameter":{
					"print":true
				}
			}
		}
	]
}

2023-09-15 16:21:43.759 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false
2023-09-15 16:21:43.759 [main] INFO  JobContainer - DataX jobContainer starts job.
2023-09-15 16:21:43.759 [main] INFO  JobContainer - Set jobId = 0
2023-09-15 16:21:43.783 [job-0] ERROR JobContainer - Exception when job run
java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_362]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_362]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_362]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_362]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_362]
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:86) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:168) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:201) [datax-core-0.0.1-SNAPSHOT.jar:na]
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581) ~[na:1.8.0_362]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396) ~[na:1.8.0_362]
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091) ~[na:1.8.0_362]
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.<clinit>(ClickhouseReader.java:30) ~[clickhousereader-0.0.1-SNAPSHOT.jar:na]
	... 12 common frames omitted
2023-09-15 16:21:43.785 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-15 16:21:43.786 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46)
	at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.<clinit>(ClickhouseReader.java:30)
	... 12 more
 - java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46)
	at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.<clinit>(ClickhouseReader.java:30)
	... 12 more

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:98)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	... 3 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.alibaba.datax.plugin.reader.clickhousereader.LocalStrings, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:92)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:37)
	at com.alibaba.datax.common.util.MessageSource.loadResourceBundle(MessageSource.java:46)
	at com.alibaba.datax.plugin.reader.clickhousereader.ClickhouseReader$Job.<clinit>(ClickhouseReader.java:30)
`

**Comment by FuYouJ** [comment]
看看是不知这个问题
里面有解决方案
https://github.com/alibaba/DataX/issues/1789

**Comment by FuYouJ** [comment]
In the ClickhouseReader class, comment out the useless line:
private static MessageSource MESSAGE_SOURCE = MessageSource.loadResourceBundle(ClickhouseReader.class);
then recompile,use the new jar clickhousereader-0.0.1-SNAPSHOT.jar replace the old :

在 ClickhouseReader 类中，将无用的行注释掉：

java
Copy code
private static MessageSource MESSAGE_SOURCE = MessageSource.loadResourceBundle(ClickhouseReader.class);
然后重新编译，使用新的 JAR 文件 clickhousereader-0.0.1-SNAPSHOT.jar 替换旧的 JAR 文件。

**Comment by FuYouJ** [comment]
你的这个问题最新版本我看历史记录是得到了修复的，你拉下最新代码自己编译打包或者下载最新版本的
