### ISSUE TITLE
oss抽取mysql数据写入oss报错未知

### ISSUE THREAD

**Issue by richardWuec** [alibaba/DataX#1957]
json配置文件为：
"writer": {
                    "name": "osswriter",
                    "parameter": {
                        "endpoint": "oss://aaa.aliyuncs.com",
                        "accessId": "",
                        "accessKey": "",
                        "bucket": "",
                        "object": "",
                        "encoding": "UTF-8",
                        "column": [
                                  {"name":"id", "type": "string"}
                        ],
                       "fileFormat": "text",
                        "path": "/user/aaa",
                        "fieldDelimiter": "\t",
                        "writeMode": "append"
                    }
                }

2023-10-13 17:46:39.967 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[OssWriter-05], Description:[执行相应的OSS操作异常.]. - Unknown
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.osswriter.OssWriter$Job.prepare(OssWriter.java:164) ~[osswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-10-13 17:46:39.971 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-10-13 17:46:39.972 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[OssWriter-05], Description:[执行相应的OSS操作异常.]. - Unknown
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.plugin.writer.osswriter.OssWriter$Job.prepare(OssWriter.java:164)
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by FuYouJ** [comment]
看报错在初始化OSS的prepare工作出问题了，你可以尝试使用example模块来调试你的任务。看看具体是什么错
