### ISSUE TITLE
gaussdbwriter 插件包名问题

### ISSUE THREAD

**Issue by kingronjan** [alibaba/DataX#1962]
在 gaussdbwriter/src/main/java/com/alibaba/datax/plugin/reader/gaussdbwriter/GaussDbWriter.java 第一行：

```java
package com.alibaba.datax.plugin.reader.gaussdbwriter;
```

打包后出现异常：

```
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.gaussdbwriter.GaussDbWriter$Job
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:173)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
        at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
        at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.alibaba.datax.core.Engine.start(Engine.java:93)
        at com.alibaba.datax.core.Engine.entry(Engine.java:175)
        at com.alibaba.datax.core.Engine.main(Engine.java:208)
```

修改为：
```java
package com.alibaba.datax.plugin.writer.gaussdbwriter;
```
后重新打包就可以正常运行

**Comment by kingronjan** [comment]
版本:  v202309
