### ISSUE TITLE
java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by niushaoda** [alibaba/DataX#1970]
2023-10-27 10:38:26.389 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2023-10-27 10:38:26.391 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
java.lang.NoSuchMethodError: com.alibaba.datax.common.statistics.PerfTrace.getInstance(ZJIIZ)Lcom/alibaba/datax/common/statistics/PerfTrace;
	at com.alibaba.datax.core.Engine.start(Engine.java:90)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by niushaoda** [comment]
解压后用自检脚本：    python {YOUR_DATAX_HOME}/bin/datax.py {YOUR_DATAX_HOME}/job/job.json
运行报错

**Comment by FuYouJ** [comment]
原因没分析出来：
解决办法：打开源码 com/alibaba/datax/core/Engine.java
注释掉:
 PerfTrace perfTrace = PerfTrace.getInstance(isJob, instanceId, taskGroupId, traceEnable);
 再打包
