### ISSUE TITLE
neo4j不可用

### ISSUE THREAD

**Issue by zzzrj1121** [alibaba/DataX#1993]
2023-11-13 16:25:22.228 [job-0] INFO  Neo4jWriter$Job - Neo4jWriter Job destroyed
2023-11-13 16:25:22.229 [job-0] ERROR Engine -

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NullPointerException
        at com.alibaba.datax.plugin.writer.neo4jwriter.Neo4jWriter$Job.split(Neo4jWriter.java:32)
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:86)
        at com.alibaba.datax.core.Engine.entry(Engine.java:168)
        at com.alibaba.datax.core.Engine.main(Engine.java:201)
 - java.lang.NullPointerException
        at com.alibaba.datax.plugin.writer.neo4jwriter.Neo4jWriter$Job.split(Neo4jWriter.java:32)
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:86)
        at com.alibaba.datax.core.Engine.entry(Engine.java:168)
        at com.alibaba.datax.core.Engine.main(Engine.java:201)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
        at com.alibaba.datax.core.Engine.start(Engine.java:86)
        at com.alibaba.datax.core.Engine.entry(Engine.java:168)
        at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.lang.NullPointerException
        at com.alibaba.datax.plugin.writer.neo4jwriter.Neo4jWriter$Job.split(Neo4jWriter.java:32)
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        ... 3 more

**Comment by FuYouJ** [comment]
你用的是最初的版本吧，这个问题最新的版本代码修复了

**Comment by zzzrj1121** [comment]
我这个是上周拉取的最新datax的包，就报这个问题。是要重新自己编译吗

**Comment by FuYouJ** [comment]
> 我这个是上周拉取的最新datax的包，就报这个问题。是要重新自己编译吗

应该是官方没编译最新的吧
你打开package文件，注释掉其他的插件，
 mvn -U clean package assembly:assembly -Dmaven.test.skip=true
 这样打包快点

**Comment by zzzrj1121** [comment]
谢谢你，我去试一下，这个问题头疼了我好几天了

**Comment by FuYouJ** [comment]
> 谢谢你，我去试一下，这个问题头疼了我好几天了

https://github.com/alibaba/DataX/issues/1907

**Comment by zzzrj1121** [comment]
> > 谢谢你，我去试一下，这个问题头疼了我好几天了
> 
> #1907

感谢指路

**Comment by lnn0418** [comment]
[WARNING] The POM for com.alibaba.datax:streamwriter:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for datax-all 0.0.1-SNAPSHOT:
[INFO] 
[INFO] datax-all .......................................... SUCCESS [  0.002 s]
[INFO] datax-common ....................................... SUCCESS [  1.846 s]
[INFO] datax-transformer .................................. SUCCESS [  0.507 s]
[INFO] datax-core ......................................... SUCCESS [  1.273 s]
[INFO] plugin-rdbms-util .................................. SUCCESS [  0.834 s]
[INFO] clickhousereader ................................... SUCCESS [  0.515 s]
[INFO] clickhousewriter ................................... SUCCESS [  0.703 s]
[INFO] plugin-unstructured-storage-util ................... SUCCESS [  1.351 s]
[INFO] gaussdbreader ...................................... SUCCESS [  0.357 s]
[INFO] gaussdbwriter ...................................... SUCCESS [  0.399 s]
[INFO] datax-example ...................................... SUCCESS [  0.000 s]
[INFO] datax-example-core ................................. SUCCESS [  1.166 s]
[INFO] datax-example-streamreader ......................... FAILURE [  0.030 s]
[INFO] datax-example-neo4j ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.124 s
[INFO] Finished at: 2024-07-25T13:56:59+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project datax-example-streamreader: Could not resolve dependencies for project com.alibaba.datax:datax-example-streamreader:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.alibaba.datax:streamreader:jar:0.0.1-SNAPSHOT (absent), com.alibaba.datax:streamwriter:jar:0.0.1-SNAPSHOT (absent): com.alibaba.datax:streamreader:jar:0.0.1-SNAPSHOT was not found in http://maven.aliyun.com/nexus/content/repositories/central/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :datax-example-streamreader


单独编译clickhouse 需要datax-example 下的包吗，我编译报错

**Comment by FuYouJ** [comment]
暂时可以在pom文件和package文件注释掉不相关的模块 提高打包速度
