### ISSUE TITLE
使用DataX内置的ossreader读取阿里云中的oss数据，报错：java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by wangmengyang-wmy** [alibaba/DataX#2026]
报错信息如下：
2023-12-26 00:18:46.473 [job-0] ERROR JobContainer - Exception when job run
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:435) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.ossreader.OssReader$Job.prepare(OssReader.java:150) ~[ossreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.prepareJobReader(JobContainer.java:715) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:308) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:86) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:168) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:201) [datax-core-0.0.1-SNAPSHOT.jar:na]
2023-12-26 00:18:46.475 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-12-26 00:18:46.476 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:435)
	at com.alibaba.datax.plugin.reader.ossreader.OssReader$Job.prepare(OssReader.java:150)
	at com.alibaba.datax.core.job.JobContainer.prepareJobReader(JobContainer.java:715)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:308)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)
 - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:435)
	at com.alibaba.datax.plugin.reader.ossreader.OssReader$Job.prepare(OssReader.java:150)
	at com.alibaba.datax.core.job.JobContainer.prepareJobReader(JobContainer.java:715)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:308)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:48)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
	at com.alibaba.datax.core.Engine.start(Engine.java:86)
	at com.alibaba.datax.core.Engine.entry(Engine.java:168)
	at com.alibaba.datax.core.Engine.main(Engine.java:201)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:435)
	at com.alibaba.datax.plugin.reader.ossreader.OssReader$Job.prepare(OssReader.java:150)
	at com.alibaba.datax.core.job.JobContainer.prepareJobReader(JobContainer.java:715)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:308)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	... 3 more

DataX配置文件如下：
{
	"content":[
		{
			"reader":{
				"name":"ossreader",
				"parameter":{
					"endpoint":"http://oss-cn-beijing.aliyuncs.com",
					"accessId":"",
					"accessKey":"",
					"bucket":"my-bucket",
					"object":"/test/datax/*",
					"column":[
						{
							"type":"string",
							"index":0
						},
						{
							"type":"string",
							"index":1
						}
					],
					"fieldDelimiter":",",
					"fileType":"txt",
					"nullFormat":"\\N"
				}
			},
			"writer":{
				"name":"streamwriter",
				"parameter":{
					"encoding":"",
					"print":true
				}
			}
		}
	],
	"setting":{
		"speed":{
			"channel":1
		}
	}
}

保存在oss上的原始数据格式如下：仅两行，使用逗号分隔
name,sex
zs,man

**Comment by wangmengyang-wmy** [comment]
配置文件有问题，object应该设置为jsonArray。如下："object": ["exampledir/test.log"],

**Comment by wangmengyang-wmy** [comment]
原本以为是DataX在读取数据时没有按照指定的fieldDelimiter进行分割，看了源码之后发现会将object读取并强转为List

**Comment by wangmengyang-wmy** [comment]
![image](https://github.com/alibaba/DataX/assets/59007867/27d534f3-0313-4bc5-97d3-aff3cf1dbe15)
