### ISSUE TITLE
JDK11提示找不到class

### ISSUE THREAD

**Issue by SunOneLeo** [alibaba/DataX#2104]
使用的是openjdk version 11 执行datax报如下错误，有支持JDK11版本的datax版本吗？

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
  at com.aliyun.odps.Odps.<init>(Odps.java:101)
  at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil.initOdpsProject(OdpsUtil.java:89)
  at com.alibaba.datax.plugin.writer.odpswriter.OdpsWriter$Job.prepare(OdpsWriter.java:149)
  at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
  at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
  at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
  at com.alibaba.datax.core.Engine.start(Engine.java:92)
  at com.alibaba.datax.core.Engine.entry(Engine.java:171)
  at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
  at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:497)
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:456)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:626)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
  ... 9 more
 - java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
  at com.aliyun.odps.Odps.<init>(Odps.java:101)
  at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil.initOdpsProject(OdpsUtil.java:89)
  at com.alibaba.datax.plugin.writer.odpswriter.OdpsWriter$Job.prepare(OdpsWriter.java:149)
  at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
  at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
  at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
  at com.alibaba.datax.core.Engine.start(Engine.java:92)
  at com.alibaba.datax.core.Engine.entry(Engine.java:171)
  at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
  at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:497)
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:456)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:626)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
  ... 9 more

  at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
  at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
  at com.alibaba.datax.core.Engine.start(Engine.java:92)
  at com.alibaba.datax.core.Engine.entry(Engine.java:171)
  at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
  at com.aliyun.odps.Odps.<init>(Odps.java:101)
  at com.alibaba.datax.plugin.writer.odpswriter.util.OdpsUtil.initOdpsProject(OdpsUtil.java:89)
  at com.alibaba.datax.plugin.writer.odpswriter.OdpsWriter$Job.prepare(OdpsWriter.java:149)
  at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
  at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
  at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
  ... 3 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
  at java.base/java.net.URLClassLoader.findClassInternal(URLClassLoader.java:497)
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:456)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:626)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:558)
  ... 9 more

**Comment by FuYouJ** [comment]
最好是java8,代码都没对高版本jdk做适配改造。问题很多
