### ISSUE TITLE
 java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by geekyouth** [alibaba/DataX#2139]
docker image: huas/datax:x64-20240618
来源：https://registry.hub.docker.com/layers/huas/datax/x64-20240618/images/sha256-933ac4bbce2b68b31bf15987d2a2f28c23b84b95dccfa95c3835e1ffe0ef81b1?context=explore

```
 
 DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
 Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
 
 
 2024-06-19 02:15:53.868 [main] INFO  MessageSource - JVM TimeZone: GMT+08:00, Locale: zh_CN
 2024-06-19 02:15:53.873 [main] INFO  MessageSource - use Locale: zh_CN timeZone: sun.util.calendar.ZoneInfo[id="GMT+08:00",offset=28800000,dstSavings=0,0,lastRule=null]
 2024-06-19 02:15:53.996 [main] INFO  VMInfo - VMInfo# operatingSystem class => com.sun.management.internal.OperatingSystemImpl
 2024-06-19 02:15:54.017 [main] INFO  Engine - the machine info  => 
 
 	osInfo:	Linux amd64 5.15.153.1-microsoft-standard-WSL2
 	jvmInfo:	Oracle Corporation 11 11.0.5+10
 	cpu num:	12
 
 	totalPhysicalMemory:	-0.00G
 	freePhysicalMemory:	-0.00G
 	maxFileDescriptorCount:	-1
 	currentOpenFileDescriptorCount:	-1
 
 	GC Names	[G1 Young Generation, G1 Old Generation]
 
 	MEMORY_NAME                    | allocation_size                | init_size                      
 	CodeHeap 'profiled nmethods'   | 117.21MB                       | 2.44MB                         
 	G1 Old Gen                     | 1,024.00MB                     | 970.00MB                       
 	G1 Survivor Space              | -0.00MB                        | 0.00MB                         
 	CodeHeap 'non-profiled nmethods' | 117.22MB                       | 2.44MB                         
 	Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
 	Metaspace                      | -0.00MB                        | 0.00MB                         
 	G1 Eden Space                  | -0.00MB                        | 54.00MB                        
 	CodeHeap 'non-nmethods'        | 5.57MB                         | 2.44MB                         
 
 
 2024-06-19 02:15:54.048 [main] INFO  Engine - 
 {
 	"setting":{
 		"speed":{
 			"channel":1
 		}
 	},
 	"content":[
 		{
 			"reader":{
 				"name":"hdfsreader",
 				"parameter":{
 					"path":"/origin_data/mysql/medical/user",
 					"defaultFS":"hdfs://namenode:8020",
 					"column":[
 						"*"
 					],
 					"fileType":"text",
 					"encoding":"UTF-8",
 					"fieldDelimiter":"\t",
 					"nullFormat":"\\N"
 				}
 			},
 			"writer":{
 				"name":"mysqlwriter",
 				"parameter":{
 					"writeMode":"replace",
 					"username":"root",
 					"password":"***************",
 					"column":[
 						"id",
 						"create_time",
 						"update_time",
 						"email",
 						"hashed_password",
 						"telephone",
 						"username"
 					],
 					"connection":[
 						{
 							"jdbcUrl":"jdbc:mysql://mysql:3306/medical?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8",
 							"table":[
 								"hdfs_user"
 							]
 						}
 					]
 				}
 			}
 		}
 	]
 }
 
 2024-06-19 02:15:54.110 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false
 2024-06-19 02:15:54.110 [main] INFO  JobContainer - DataX jobContainer starts job.
 2024-06-19 02:15:54.111 [main] INFO  JobContainer - Set jobId = 0
 2024-06-19 02:15:54.145 [job-0] INFO  HdfsReader$Job - init() begin...
 2024-06-19 02:15:54.148 [job-0] INFO  HdfsReader$Job - skipEmptyOrcFile: false, orcFileEmptySize: null
 2024-06-19 02:15:55.191 [job-0] ERROR JobContainer - Exception when job run
 java.lang.StackOverflowError: null
 	at java.base/java.util.stream.SpinedBuffer.ensureCapacity(SpinedBuffer.java:133) ~[na:na]
 	at java.base/java.util.stream.Nodes$SpinedNodeBuilder.begin(Nodes.java:1279) ~[na:na]
 	at java.base/java.util.stream.Sink$ChainedReference.begin(Sink.java:253) ~[na:na]
 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[na:na]
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[na:na]
 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:na]
 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517) ~[na:na]
 	at java.base/java.lang.ClassLoader.getDefinedPackages(ClassLoader.java:2254) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFuncFinal.getFieldValue(FieldWriterObjectFuncFinal.java:26) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:52) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:86) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:81) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:90) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:81) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:90) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:81) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:90) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:81) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:90) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
 	at com.alibaba.fastjson2.writer.FieldWriterObjectFinal.write(FieldWriterObjectFinal.java:81) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.ObjectWriter5.write(ObjectWriter5.java:90) ~[fastjson2-2.0.23.jar:na]
 	at com.alibaba.fastjson2.writer.OWG_4_8_Module.write(Unknown Source) ~[na:na]
```

**Comment by geekyouth** [comment]
使用官方原生版本，不会有上述问题。
