### ISSUE TITLE
datax3.0 连接mysql5.7连不上，连接8.0没问题，URL和账户密码都没问题

### ISSUE THREAD

**Issue by xxd521** [alibaba/DataX#2179]
2024-08-06 16:50:00.193 [main] INFO  JobContainer - Set jobId = 0
	2024-08-06 16:50:00.260 [job-0] WARN  DBUtil - test connection of [${YQ_SOURCE_JDBCURL}] failed, for Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: No suitable driver found for ${YQ_SOURCE_JDBCURL}.
	2024-08-06 16:50:00.264 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
	java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
		at com.alibaba.datax.plugin.rdbms.util.DBUtil$2.call(DBUtil.java:71) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.plugin.rdbms.util.DBUtil$2.call(DBUtil.java:51) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30) [datax-common-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.plugin.rdbms.util.DBUtil.chooseJdbcUrl(DBUtil.java:51) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]

**Comment by cht19463** [comment]
检查一下 mysql-connector-java 的版本

**Comment by yy73** [comment]
解决了吗？账号和密码都没问题，mysql版本5.7.44，mysql-connect-java 8.0.29，和你显示的问题一样

**Comment by xxd521** [comment]
> 解决了吗？账号和密码都没问题，mysql版本5.7.44，mysql-connect-java 8.0.29，和你显示的问题一样

首先ds本身是能连上mysql5.7的，ds加datax的模式，又挨个测试了每个节点的datax，最后发现是有个节点的datax有问题，重新替换安装后就行了
