### ISSUE TITLE
datax在输入多个文件作为输入的时候会导致内存溢出问题

### ISSUE THREAD

**Issue by dsf66zcq** [alibaba/DataX#220]
如题所述，我参照txtfilereader插件写了一个自己的插件，配置了文件路径，在路径下有近60万的文件，在任务切分的时候出错，增加了conf/core.json文件的-Xms1G -Xmx1G也不起效果。错误信息如下：
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /home/elsearch/www/deploy/datax/log/java_pid8319.hprof ...
Heap dump file created [709645887 bytes in 3.592 secs]
2017-06-27 03:43:46.610 [job-0] ERROR JobContainer - Exception when job run
java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:203) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:682) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:605) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1463) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398) ~[fastjson-1.1.43.jar:na]
	at Serializer_1.write1(Unknown Source) ~[na:na]
	at Serializer_1.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:381) ~[fastjson-1.1.43.jar:na]
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:409) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2017-06-27 03:43:46.695 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2017-06-27 03:43:46.765 [job-0] ERROR Engine -

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:203)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:682)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:605)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1463)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:381)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:409)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:203)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:682)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:605)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1463)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:381)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:409)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:203)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:682)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:605)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1463)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:49)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:34)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:188)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:398)
	at Serializer_1.write1(Unknown Source)
	at Serializer_1.write(Unknown Source)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:127)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:369)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:393)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:381)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:409)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)

**Comment by wwek** [comment]
有可能是字段不匹配,你把数据量减少后验证,找到出问题的脏数据
