### ISSUE TITLE
MongoDBReader ,timeout exception

### ISSUE THREAD

**Issue by 2efPer** [alibaba/DataX#227]
2017-07-10 14:44:48.689 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2017-07-10 14:44:48.690 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2017-07-10 14:44:48.691 [main] INFO  JobContainer - DataX jobContainer starts job.
2017-07-10 14:44:48.693 [main] INFO  JobContainer - Set jobId = 0
2017-07-10 14:44:48.816 [job-0] INFO  cluster - Cluster created with settings {hosts=[114.115.147.192:30000], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-07-10 14:44:48.817 [job-0] INFO  cluster - Adding discovered server 114.115.147.192:30000 to client view of cluster
2017-07-10 14:44:48.958 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  connection - Opened connection [connectionId{localValue:1, serverValue:12232}] to 114.115.147.192:30000
2017-07-10 14:44:48.967 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  cluster - Monitor thread successfully connected to server with description ServerDescription{address=114.115.147.192:30000, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 10]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=8029659, setName='shard1', canonicalAddress=192.168.1.8:30000, hosts=[192.168.1.8:30000], passives=[], arbiters=[], primary='192.168.1.8:30000', tagSet=TagSet{[]}, electionId=7fffffff000000000000000a, setVersion=1}
2017-07-10 14:44:48.968 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  cluster - Discovered cluster type of REPLICA_SET
2017-07-10 14:44:48.969 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  cluster - Adding discovered server 192.168.1.8:30000 to client view of cluster
2017-07-10 14:44:48.969 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  cluster - Server 114.115.147.192:30000 is no longer a member of the replica set.  Removing from client view of cluster.
2017-07-10 14:44:48.970 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-114.115.147.192:30000] INFO  cluster - Canonical address 192.168.1.8:30000 does not match server address.  Removing 114.115.147.192:30000 from client view of cluster
七月 10, 2017 2:44:49 下午 org.apache.hadoop.util.NativeCodeLoader <clinit>
警告: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-07-10 14:44:50.027 [job-0] INFO  JobContainer - jobContainer starts to do prepare ...
2017-07-10 14:44:50.028 [job-0] INFO  JobContainer - DataX Reader.Job [mongodbreader] do prepare work .
2017-07-10 14:44:50.029 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do prepare work .
2017-07-10 14:44:50.130 [job-0] INFO  HdfsWriter$Job - 由于您配置了writeMode append, 写入前不做清理工作, [/data/] 目录下写入相应文件名前缀  [testMongo] 的文件
2017-07-10 14:44:50.131 [job-0] INFO  JobContainer - jobContainer starts to do split ...
2017-07-10 14:44:50.132 [job-0] INFO  JobContainer - Job set Max-Byte-Speed to 104857600 bytes.
2017-07-10 14:44:50.147 [job-0] INFO  cluster - No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, all=[ServerDescription{address=192.168.1.8:30000, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2017-07-10 14:45:08.986 [cluster-ClusterId{value='596322604478372e02a1e84a', description='null'}-192.168.1.8:30000] INFO  cluster - Exception in monitor thread while connecting to server 192.168.1.8:30000
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongo-java-driver-3.2.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.2.2.jar:na]
	... 3 common frames omitted
2017-07-10 14:45:20.150 [job-0] ERROR JobContainer - Exception when job run
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=192.168.1.8:30000, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:201) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:206) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:53) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.Mongo.execute(Mongo.java:772) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.Mongo$2.execute(Mongo.java:759) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:185) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:165) ~[mongo-java-driver-3.2.2.jar:na]
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplitInterval(CollectionSplitUtil.java:55) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplit(CollectionSplitUtil.java:37) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.split(MongoDBReader.java:37) ~[mongodbreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2017-07-10 14:45:20.158 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2017-07-10 14:45:20.171 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=192.168.1.8:30000, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:201)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:206)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:53)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:185)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:165)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplitInterval(CollectionSplitUtil.java:55)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplit(CollectionSplitUtil.java:37)
	at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.split(MongoDBReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{**address=192.168.1.8:30000**, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:201)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:206)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:53)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:185)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:165)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplitInterval(CollectionSplitUtil.java:55)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplit(CollectionSplitUtil.java:37)
	at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.split(MongoDBReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=192.168.1.8:30000, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:201)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:206)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:53)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:185)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:165)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplitInterval(CollectionSplitUtil.java:55)
	at com.alibaba.datax.plugin.reader.mongodbreader.util.CollectionSplitUtil.doSplit(CollectionSplitUtil.java:37)
	at com.alibaba.datax.plugin.reader.mongodbreader.MongoDBReader$Job.split(MongoDBReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.doReaderSplit(JobContainer.java:732)
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:393)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
	... 3 more

> 链接的mongodb server ip 是外网IP，但是注意到日志显示变成了内网IP，是否和这个相关？是否是mongodb的问题？

**Comment by 2efPer** [comment]
**reader的配置**

"reader": {
          "name": "mongodbreader",
          "parameter": {
		    	"address": ["14.15.17.12:30000"],
			"userName": "",
                        "userPassword": "",
			"dbName": "nsdb",
			"collectionName": "ne.ahc.sens",
			"column": [
				{
					"name":"_id",
					"type":"string"
				},
				{
					"name":"_class",
					"type":"string"
				},
				{
					"name":"userId",
					"type":"string"
				},
				{
					"name":"userName",
					"type":"string"
				},
				{
					"name":"logonTime",
					"type":"date"
				},
				{
					"name":"logonHost",
					"type":"string"
				},
				{
					"name":"logonIp",
					"type":"string"
				},
				{
					"name":"lastBang",
					"type":"string"
				},
				{
					"name":"extraData",
					"type":"string"
				},
				{
					"name":"appName",
					"type":"string"
				},
				{
					"name":"userState",
					"type":"string"
				},
				{
					"name":"state",
					"type":"string"
				},
				{
					"name":"sessionGroup",
					"type":"string"
				},
				{
					"name":"stationId",
					"type":"string"
				},
				{
					"name":"inner",
					"type":"string"
				},
				{
					"name":"logoffTime",
					"type":"date"
				},
				{
					 "name": "'ed'",
					 "type": "string"
				},
			]
			
		  }
        }

**Comment by 2efPer** [comment]
经过鉴定，是[此处代码](https://github.com/alibaba/DataX/blob/master/mongodbreader/src/main/java/com/alibaba/datax/plugin/reader/mongodbreader/util/MongoUtil.java#L72)对URL处理之后就没法链接了
