### ISSUE TITLE
datax支持从一个数据源到多个目标数据库的数据传输吗

### ISSUE THREAD

**Issue by pxh520** [alibaba/DataX#232]
在一个json里面能不能配置多个writer，尝试配多个writer没有成功。有这方面成功场景的给个参考，谢谢

**Comment by pxh520** [comment]
om.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 您的配置文件中的列配置信息有误. 您要写入的目的端的表个数是:2 , 但是根据系统建议需要切分的份数是：1. 请检查您的配置并作出修改.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.WriterUtil.doSplit(WriterUtil.java:42) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.split(CommonRdbmsWriter.java:132) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.db2writer.Db2Writer$Job.split(Db2Writer.java:55) ~[db2writer-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]

**Comment by pxh520** [comment]
如果配置过个writer，则只有最后一个writer生效。datax的稳定或社区缺失

**Comment by yoranye** [comment]
是呀，我也郁闷了，怎么能写多张不同结构的表？
你解决了吗
