### ISSUE TITLE
 java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by WowCoder** [alibaba/DataX#246]
本来上一秒还是正常的，下一秒就是读取超时了，是什么原因呢？这个超时的时间可以自己控制吗？

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[OdpsReader-07], Description:[读取 odps 异常].  - java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
        at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
        at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:745)
 - java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
        at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
        at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:745)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
        at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:79)
        at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
        at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
        at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
        at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
        ... 3 more

**Comment by dingqizhou** [comment]
sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
连接异常 网络问题




yzyulin@sina.com
 
From: Leo
Date: 2017-08-01 15:54
To: alibaba/DataX
CC: Subscribed
Subject: [alibaba/DataX] java.net.SocketTimeoutException: Read timed out (#246)
本来上一秒还是正常的，下一秒就是读取超时了，是什么原因呢？这个超时的时间可以自己控制吗？
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[OdpsReader-07], Description:[读取 odps 异常]. - java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:170)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at java.io.FilterInputStream.read(FilterInputStream.java:107)
at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
at java.lang.Thread.run(Thread.java:745)
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:170)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at java.io.FilterInputStream.read(FilterInputStream.java:107)
at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
at java.lang.Thread.run(Thread.java:745)
 at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
 at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:79)
 at com.alibaba.datax.plugin.reader.odpsreader.OdpsReader$Task.startRead(OdpsReader.java:372)
 at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
 at java.lang.Thread.run(Thread.java:745)

Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:170)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
at java.io.FilterInputStream.read(FilterInputStream.java:107)
at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:702)
at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:110)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.aliyun.odps.tunnel.io.ProtobufRecordStreamReader.read(ProtobufRecordStreamReader.java:208)
at com.aliyun.odps.tunnel.io.TunnelRecordReader.read(TunnelRecordReader.java:34)
at com.alibaba.datax.plugin.reader.odpsreader.ReaderProxy.doRead(ReaderProxy.java:65)
... 3 more

**Comment by WowCoder** [comment]
可以设置一下重连或者延长等待时间吗

**Comment by dingqizhou** [comment]
本身没有这个配置 你这个治标不治本 还是要分析清楚 为什么会连接超时 我之前也遇到过 刚开始正常 抽取后来速度慢慢变为0 我的原因就是源库 对外访问策略限速 


yzyulin@sina.com
 
From: Leo
Date: 2017-08-01 16:21
To: alibaba/DataX
CC: dingqizhou; Comment
Subject: Re: [alibaba/DataX] java.net.SocketTimeoutException: Read timed out (#246)
可以设置一下重连或者延长等待时间吗

**Comment by WowCoder** [comment]
嗯嗯，好的，谢谢，我找一下原因
