### ISSUE TITLE
oracle单表数据导入另外一台oracle上报错。抛出异常：java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by kong3672757** [alibaba/DataX#262]
**job：**
{    
    "job": {    
        "content": [    
            {    
                 "reader": {  
                    "name": "oraclereader",  
                    "parameter": {  
                        "username": "zy_*",  
                        "password": "zy_*",  
                        "column": ["id","name"],  
                        "where": "",  
                        "connection": [  
                            {  
                                "querySql": [  
                                    "select id,name from sys_test"  
                                ],  
                                "jdbcUrl":"jdbc:oracle:thin:@10.60.1.87:1521:orcl" 
                            }  
                        ]  
                    }  
                },    
                "writer": {   
                    "name": "oraclewriter",   
                    "parameter": {  
                        "username": "fe_*",  
                        "password": "fe_*",  
                        "truncate": "true",  
                        "column": ["id","name"],  
                        "connection": [  
                            {  
                                  
                                "jdbcUrl": "jdbc:oracle:thin:@10.60.1.156:1521:orcl",  
                                "table": [  
                                    "sys_test_new"  
                                ]  
                            }  
                        ]  
                      }  
                }    
            }   
        ],    
        "setting": {    
            "speed": {    
                "channel": 6   
            }    
        }    
    }    
}    

**异常：**
DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2016, Alibaba Group. All Rights Reserved.

2017-08-30 08:40:08.064 [main] INFO  VMInfo - VMInfo# operatingSystem class => com.sun.management.UnixOperatingSystem
2017-08-30 08:40:08.074 [main] INFO  Engine - the machine info  => 

	osInfo:	Oracle Corporation 1.7 24.80-b11
	jvmInfo:	Linux amd64 2.6.32-431.el6.x86_64
	cpu num:	1

	totalPhysicalMemory:	0.96G
	freePhysicalMemory:	0.06G
	maxFileDescriptorCount:	4096
	currentOpenFileDescriptorCount:	67

	GC Names	[MarkSweepCompact, Copy]

	MEMORY_NAME                    | allocation_size                | init_size                      
	Tenured Gen                    | 682.69MB                       | 682.69MB                       
	Eden Space                     | 273.06MB                       | 273.06MB                       
	Code Cache                     | 48.00MB                        | 2.44MB                         
	Perm Gen                       | 82.00MB                        | 20.75MB                        
	Survivor Space                 | 34.13MB                        | 34.13MB                        

2017-08-30 08:40:08.134 [main] INFO  Engine - 
{
	"content":[
		{
			"reader":{
				"name":"oraclereader",
				"parameter":{
					"column":[
						"id",
						"name"
					],
					"connection":[
						{
							"jdbcUrl":"jdbc:oracle:thin:@10.60.1.87:1521:orcl",
							"querySql":[
								"select id,name from sys_test"
							]
						}
					],
					"password":"****",
					"username":"zy_*",
					"where":""
				}
			},
			"writer":{
				"name":"oraclewriter",
				"parameter":{
					"column":[
						"id",
						"name"
					],
					"connection":[
						{
							"jdbcUrl":"jdbc:oracle:thin:@10.60.1.156:1521:orcl",
							"table":[
								"sys_test_new"
							]
						}
					],
					"password":"****",
					"truncate":"true",
					"username":"fe_*"
				}
			}
		}
	],
	"setting":{
		"speed":{
			"channel":6
		}
	}
}

2017-08-30 08:40:08.217 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2017-08-30 08:40:08.220 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2017-08-30 08:40:08.220 [main] INFO  JobContainer - DataX jobContainer starts job.
2017-08-30 08:40:08.223 [main] INFO  JobContainer - Set jobId = 0
2017-08-30 08:40:08.264 [job-0] ERROR JobContainer - Exception when job run
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:84) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:59) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job.init(OracleReader.java:37) ~[oraclereader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2017-08-30 08:40:08.271 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2017-08-30 08:40:08.278 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:84)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:59)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job.init(OracleReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:84)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:59)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job.init(OracleReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:162)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.alibaba.datax.common.util.Configuration.getList(Configuration.java:426)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:84)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:59)
	at com.alibaba.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:33)
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:55)
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job.init(OracleReader.java:37)
	at com.alibaba.datax.core.job.JobContainer.initJobReader(JobContainer.java:673)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:303)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)

JDK1.8，试了好多办法，都没有解决，诚心求解！

**Comment by tankdeper** [comment]
oraclereader中的jdbcUrl值是数组，比如："jdbcUrl":["jdbc:oracle:thin:@10.60.1.87:1521:orcl"]
