### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server returned an incomplete response. The connection has been closed. ClientConnectionId:06fb692f-8e0d-4992-b890-3242e315e6d9".

### ISSUE THREAD

**Issue by goodsave** [alibaba/DataX#267]
2017-09-25 21:17:34.120 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2017-09-25 21:17:34.125 [main] INFO  Engine - the machine info  => 

	osInfo:	Oracle Corporation 1.8 25.121-b13
	jvmInfo:	Windows 7 x86 6.1
	cpu num:	8

	totalPhysicalMemory:	-0.00G
	freePhysicalMemory:	-0.00G
	maxFileDescriptorCount:	-1
	currentOpenFileDescriptorCount:	-1

	GC Names	[Copy, MarkSweepCompact]

	MEMORY_NAME                    | allocation_size                | init_size                      
	Eden Space                     | 273.06MB                       | 68.31MB                        
	Code Cache                     | 32.00MB                        | 0.16MB                         
	Survivor Space                 | 34.13MB                        | 8.50MB                         
	Metaspace                      | -0.00MB                        | 0.00MB                         
	Tenured Gen                    | 682.69MB                       | 170.69MB                       

2017-09-25 21:17:34.146 [main] INFO  Engine - 
{
	"content":[
		{
			"reader":{
				"name":"sqlserverreader",
				"parameter":{
					"column":[
						"[SFD_ID]",
						"[SIT_ID]",
						"[Seq]",
						"[SWD_ID]",
						"[FxNote_ID]",
						"[PCI_ID]",
						"[Dose]",
						"[AmendedDose]",
						"[FxThresholdFxDose]",
						"[MinimumInterval]",
						"[RowVers]"
					],
					"connection":[
						{
							"jdbcUrl":[
								"”
							],
							"table":[
								"[dbo].[Site_FractionDetails]"
							]
						}
					],
					"fetchSize":"500",
					"password":"********",
					"splitPk":"SFD_ID",
					"username":"ReadOnly",
					"where":"  [SFD_ID] in (1881372,1881373,1881374) "
				}
			},
			"writer":{
				"name":"sqlserverwriter",
				"parameter":{
					"column":[
						"[SFD_ID]",
						"[SIT_ID]",
						"[Seq]",
						"[SWD_ID]",
						"[FxNote_ID]",
						"[PCI_ID]",
						"[Dose]",
						"[AmendedDose]",
						"[FxThresholdFxDose]",
						"[MinimumInterval]",
						"[RowVers]"
					],
					"connection":[
						{
							"jdbcUrl":"",
							"table":[
								"[dbo].[Site_FractionDetails]"
							]
						}
					],
					"password":"****************",
					"postSql":[
						""
					],
					"preSql":[
						"delete from @table where  [SFD_ID] in (1881372,1881373,1881374)"
					],
					"username":"szrmyy"
				}
			}
		}
	],
	"setting":{
		"speed":{
			"byte":1048576
		}
	}
}

2017-09-25 21:17:34.162 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2017-09-25 21:17:34.163 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2017-09-25 21:17:34.163 [main] INFO  JobContainer - DataX jobContainer starts job.
2017-09-25 21:17:34.165 [main] INFO  JobContainer - Set jobId = 0
2017-09-25 21:17:39.554 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:sqlserver://172.16.100.1:1433;databaseName=MOSAIQ.
2017-09-25 21:17:39.594 [job-0] INFO  OriginalConfPretreatmentUtil - table:[[dbo].[Site_FractionDetails]] has columns:[SFD_ID,SIT_ID,Seq,SWD_ID,FxNote_ID,PCI_ID,Dose,AmendedDose,FxThresholdFxDose,MinimumInterval,RowVers].
2017-09-25 21:17:40.255 [job-0] INFO  OriginalConfPretreatmentUtil - table:[[dbo].[Site_FractionDetails]] all columns:[
SFD_ID,SIT_ID,Seq,SWD_ID,FxNote_ID,PCI_ID,Dose,AmendedDose,FxThresholdFxDose,MinimumInterval,RowVers
].
2017-09-25 21:17:40.630 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server returned an incomplete response. The connection has been closed. ClientConnectionId:06fb692f-8e0d-4992-b890-3242e315e6d9".
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server returned an incomplete response. The connection has been closed. ClientConnectionId:06fb692f-8e0d-4992-b890-3242e315e6d9".
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asConnException(RdbmsException.java:36) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:394) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:384) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.access$000(DBUtil.java:22) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:322) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30) [datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:319) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:303) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.JdbcConnectionFactory.getConnecttion(JdbcConnectionFactory.java:27) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:125) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:140) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:35) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:41) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.sqlserverwriter.SqlServerWriter$Job.init(SqlServerWriter.java:37) [sqlserverwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2017-09-25 21:17:41.630 [job-0] ERROR RetryUtil - Exception when calling callable, 即将尝试执行第1次重试.本次重试计划等待[1000]ms,实际等待[1000]ms, 异常Msg:[Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server returned an incomplete response. The connection has been closed. ClientConnectionId:06fb692f-8e0d-4992-b890-3242e315e6d9".]

**Comment by goodsave** [comment]
win 7系统 JRE 8 32位

**Comment by goodsave** [comment]
<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.1.0.jre8</version>
		</dependency>
