### ISSUE TITLE
插件[ftpreader,ftpWriter]加载失败，1s后重试... Exception:Code:[Framework-12]

### ISSUE THREAD

**Issue by Skyexu** [alibaba/DataX#280]
想用 datax 实现远程 ftp 文件存到 hdfs，在测试的时候报插件初始化错误，请问是什么原因。

```
2017-10-18 16:39:26.213 [main] WARN  ConfigParser - 插件[ftpreader,ftpWriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader] 
2017-10-18 16:39:27.232 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader]
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
```
发现网上也有同样错误的同学 http://www.oschina.net/question/2912685_2195792

**Comment by jiaomb** [comment]
网上的那个是odpswriter的package.xml里有个路径写成了reader
