### ISSUE TITLE
Hive表字段有大量null，识别字段数不同

### ISSUE THREAD

**Issue by duzhaoqi** [alibaba/DataX#306]
在使用datax过程中`hive同步到RDS`过程，hive有大量null字段，在导出时，有三十多个字段，显示只有9个字段，导致数据导出失败。

**Comment by duzhaoqi** [comment]
2019-03-22 09:01:56.930 [job-0] INFO HdfsReader$Job - [hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000005_0]是[text]类型的文件, 将该文件加入source files列表
2019-03-22 09:01:56.939 [job-0] INFO HdfsReader$Job - [hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000006_0]是[text]类型的文件, 将该文件加入source files列表
2019-03-22 09:01:56.945 [job-0] INFO HdfsReader$Job - [hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000007_0]是[text]类型的文件, 将该文件加入source files列表
2019-03-22 09:01:56.953 [job-0] INFO HdfsReader$Job - [hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000008_0]是[text]类型的文件, 将该文件加入source files列表
2019-03-22 09:01:56.953 [job-0] INFO HdfsReader$Job - 您即将读取的文件数为: [9], 列表为: [hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000003_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000004_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000007_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000000_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000006_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000001_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000008_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000002_0,hdfs://20.58.32.8:8020/user/hive/warehouse/jcjkdev.db/k_im_check_cons_det/000005_0]
2019-03-22 09:01:56.953 [job-0] INFO JobContainer - DataX Writer.Job [mysqlwriter] do prepare work .
2019-03-22 09:01:56.955 [job-0] INFO JobContainer - jobContainer starts to do split ...
2019-03-22 09:01:56.955 [job-0] INFO JobContainer - Job set Channel-Number to 20 channels.
2019-03-22 09:01:56.955 [job-0] INFO HdfsReader$Job - split() begin...
2019-03-22 09:01:56.958 [job-0] INFO JobContainer - DataX Reader.Job [hdfsreader] splits to [9] tasks.
2019-03-22 09:01:56.968 [job-0] INFO JobContainer - DataX Writer.Job [mysqlwriter] splits to [9] tasks.
2019-03-22 09:01:57.033 [job-0] INFO JobContainer - jobContainer starts to do schedule ...
2019-03-22 09:01:57.073 [job-0] INFO JobContainer - Scheduler starts [2] taskGroups.
2019-03-22 09:01:57.076 [job-0] INFO JobContainer - Running by standalone Mode.
... ...
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.]. - 列配置信息有错误. 因为您配置的任务中，源头读取字段数:3 与 目的表要写入的字段数:110 不相等. 请检查您的配置并作出修改.
at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:278) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78) ~[mysqlwriter-0.0.1-SNAPSHOT.jar:na]
at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
... ...
