### ISSUE TITLE
elasticsearchwriter不能用

### ISSUE THREAD

**Issue by Dior222** [alibaba/DataX#31]
运行报错：
Caused by: java.lang.IllegalArgumentException: Preemptive authentication set without credentials provider
	at io.searchbox.client.config.HttpClientConfig$Builder.build(HttpClientConfig.java:301)
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESClient.createClient(ESClient.java:65)
	at com.alibaba.datax.plugin.writer.elasticsearchwriter.ESWriter$Job.prepare(ESWriter.java:49)
	at com.alibaba.datax.core.job.JobContainer.prepareJobWriter(JobContainer.java:724)
	at com.alibaba.datax.core.job.JobContainer.prepare(JobContainer.java:309)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:115)
	... 3 more
本地的elasticsearch环境没有配置auth。
job相关配置如下：
"writer": {
          "name": "elasticsearchwriter",
          "parameter": {
            "endpoint": "http://localhost:9200",
            "index": "xxx",
            "type": "xxx",
            "accessId": "",
            "accessKey": "",
            "cleanup": true,
            "settings": {"index" :{"number_of_shards": 5, "number_of_replicas": 0}},
            "discovery": false,
            "batchSize": 1000,
            "splitter": ",",
……
}

**Comment by sunyaf** [comment]
"accessId": "",
"accessKey": "",
这两个参数设置个1不要空字符串

**Comment by zhaoweijing2003** [comment]
@sunyaf 楼上正解

            if (preemptiveAuthSetWithoutCredentials()) {
                throw new IllegalArgumentException("Preemptive authentication set without credentials provider");
            }
        private boolean preemptiveAuthSetWithoutCredentials() {
            return !preemptiveAuthTargetHosts.isEmpty() && credentialsProvider == null;
        }
