### ISSUE TITLE
频繁报：关闭的连接错误

### ISSUE THREAD

**Issue by doyus** [alibaba/DataX#393]
at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3921)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:361)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:291)

**Comment by tongYuSir** [comment]
老兄，你解决了嘛？使用的是哪个版本的Oracle啊？我也遇到这个问题了
