### ISSUE TITLE
datax对接hdfs，向orc表中追加数据，失败了，导致orc表在hdfss上的路径没了，从而造成了orc表中的原数据丢失了，这个怎么修复？

### ISSUE THREAD

**Issue by hywel-hu** [alibaba/DataX#399]

**Comment by hywel-hu** [comment]
七月 25, 2019 3:31:33 下午 org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer nextBlockOutputStream
信息: Abandoning BP-2077357693-172.20.235.108-1562310647661:blk_1073791216_50432
七月 25, 2019 3:31:33 下午 org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer nextBlockOutputStream
信息: Abandoning BP-2077357693-172.20.235.108-1562310647661:blk_1073791217_50433
七月 25, 2019 3:31:33 下午 org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer createBlockOutputStream
信息: Exception in createBlockOutputStream
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:57)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2278)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1318)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1237)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:449)
