### ISSUE TITLE
clickhouse branch error

### ISSUE THREAD

**Issue by JesseYaoLi** [alibaba/DataX#412]
1. when the master branch merge clickhouse feather, for example renrenche (https://github.com/renrenche/DataX)?
2. when I use renrenche sub branch test clickhouse,  blow errror happened?
   step1. load renrenche Datax-Master
   step2. copy the clickhouseReader and clickhousewriter from renrenche master folder to plugin datax master folder.
    setp3. create json file, load mysql table into clickhouse. Below is json code.
{
    "job": {
        "setting": {
            "speed": {
                 "channel": 3
            },
            "errorLimit": {
                "record": 0,
                "percentage": 0.02
            }
        },
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
					    "writeMode": "insert",
					    "username": "jesse",
                        "password": "jesse@123",
                        "column": [
						"taobao_so_no",
						"trade_status",
						],
						"connection": [
                            {
                                "table": [
                                    "f_taobao_sales"
                                ],
								"jdbcUrl": [
     "jdbc:mysql://10.225.81.220:11101/BDW?useUnicode=true&characterEncoding=utf8"
                                ]
                                
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "clickhousewriter",
                    "parameter": {
					    "writeMode": "insert",
					    "username": "jesse",
                        "password": "jesse+b3X",
                        "column": [
                        "taobao_so_no",
						"trade_status"
                        ],
						"session": [
                        	"set session sql_mode='ANSI'"
                        ],
                        "preSql": [
                            "delete from f_taobao_sales"
                        ],
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:clickhouse://10.226.81.256:8123/bdw",
                                "table": [
								    "f_taobao_sales"
								]
                            }
                        ],              
                    }
                }
            }
        ]
    }
}
   step 4:python datax.py f_taobao_sales.json
Error:
019-08-06 19:11:39.204 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2019-08-06 19:11:39.205 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2019-08-06 19:11:39.205 [main] INFO  JobContainer - DataX jobContainer starts job.
2019-08-06 19:11:39.206 [main] INFO  JobContainer - Set jobId = 0
2019-08-06 19:11:39.391 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://10.228.86.203:11101/BDW?useUnicode=true&characterEncoding=utf8&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.
2019-08-06 19:11:39.406 [job-0] INFO  OriginalConfPretreatmentUtil - table:
2019-08-06 19:11:39.409 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:176) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_211]
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	... 7 common frames omitted
2019-08-06 19:11:39.413 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2019-08-06 19:11:39.413 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Description:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
 - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:176)
	at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:93)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:691)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)
Caused by: java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:172)
	... 7 more

**Comment by admin1122339** [comment]
你好 请问下我编译源码 少这个Could not find artifact com.alibaba.data
x:simulator:jar:0.0.1-SNAPSHOT   怎么处理的   已解决

**Comment by dingxiaobo** [comment]
> 你好 请问下我编译源码 少这个Could not find artifact com.alibaba.data x:simulator:jar:0.0.1-SNAPSHOT 怎么处理的 已解决

fixed in 5891b49f5d389fa87cd6df5334d4326a423d189b
