### ISSUE TITLE
mysqlwriter取jdbcurl有bug

### ISSUE THREAD

**Issue by moiiom** [alibaba/DataX#42]
job.json配置jdbcUrl为数组，
mysqlwriter读取配置时，jdbcUrl未按数组处理报错。
详见/DataX-master/plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/util/OriginalConfPretreatmentUtil.java

**Comment by wangyuxiong** [comment]
mysqlwriter 的配置，jdbcUrl不支持数组的配置吧？

[文档](https://github.com/alibaba/DataX/blob/master/mysqlwriter/doc/mysqlwriter.md)里面有说明的。
_注意：1、在一个数据库上只能配置一个 jdbcUrl 值。这与 MysqlReader 支持多个备库探测不同，因为此处不支持同一个数据库存在多个主库的情况(双主导入数据情况)_

"jdbcUrl": "jdbc:mysql://127.0.0.1:3306/datax?useUnicode=true&characterEncoding=gbk",

**Comment by ExpressGit** [comment]
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-14], Description:[设置 session 失败.].  - session配置有误. 因为根据您的配置执行 session 设置失败. 上下文信息是:[jdbcUrl:[jdbc:mysql://rm-bp1l267g02qj8q579.mysql.rds.aliyuncs.com:3306/mysoft_log?useUnicode=true&characterEncoding=utf-8&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true], table:[msg_result]]. 请检查您的配置并作出修改. - Unknown system variable 'transaction'
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.doDealWithSessionConfig(DBUtil.java:728)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.dealWithSessionConfig(DBUtil.java:695)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.prepare(CommonRdbmsWriter.java:234)
	at com.alibaba.datax.plugin.writer.drdswriter.DrdsWriter$Task.prepare(DrdsWriter.java:77)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:50)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.sql.SQLException: Unknown system variable 'transaction'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:848)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:742)


drdswirter 并没有session参数配置，却包了session配置的错误？？？

**Comment by moiiom** [comment]
又测了一遍，确实是配置的原因。按照文档说明没问题。
失态+_+
