### ISSUE TITLE
datax连接teradata

### ISSUE THREAD

**Issue by yangql881012** [alibaba/DataX#436]
请问一下，现在的版本支持terdata吗，按照操作配置了找不到驱动
2019-09-10 17:28:15.228 [job-0] WARN  DBUtil - test connection of [jdbc:teradata://10.1.192.201/CLIENT_CHARSET=UTF8,TMODE=TERA,CHARSET=UTF8] failed, for Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: No suitable driver found for jdbc:teradata://10.1.192.201/CLIENT_CHARSET=UTF8,TMODE=TERA,CHARSET=UTF8.
2019-09-10 17:28:15.240 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$2.call(DBUtil.java:71) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$2.call(DBUtil.java:51) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]

**Comment by longfeizheng** [comment]
你用户名或者密码错误了吧，使用rdbmswriter就可以链接teradata数据库，
