### ISSUE TITLE
提示是 `您配置的文件在写入时出现IO异常.` 是因为DataX没权限访问这个节点么

### ISSUE THREAD

**Issue by yakirChen** [alibaba/DataX#45]
```shell
2016-05-27 14:16:40.995 [0-0-0-writer] INFO  HdfsWriter$Task - begin do write...
2016-05-27 14:16:40.995 [0-0-0-writer] INFO  HdfsWriter$Task - write to file : [hdfs://hmaster:9000/user/admin/warehouse/hdfswriter.db/trade_order__c477bf58_958b_47c0_90b2_cdcdc891f614/trade_order__d259c28e_5f0d_4287_a5d5_c2a7237346ae]
2016-05-27 14:16:41.425 [0-0-0-writer] ERROR HdfsWriter$Job - 写文件文件[hdfs://hmaster:9000/user/admin/warehouse/hdfswriter.db/trade_order__c477bf58_958b_47c0_90b2_cdcdc891f614/trade_order__d259c28e_5f0d_4287_a5d5_c2a7237346ae]时发生IO异常,请检查您的网络是否正常！
2016-05-27 14:16:41.425 [0-0-0-writer] INFO  HdfsWriter$Job - start delete tmp dir [hdfs://hmaster:9000/user/admin/warehouse/hdfswriter.db/trade_order__c477bf58_958b_47c0_90b2_cdcdc891f614] .
2016-05-27 14:16:41.431 [0-0-0-writer] INFO  HdfsWriter$Job - finish delete tmp dir [hdfs://hmaster:9000/user/admin/warehouse/hdfswriter.db/trade_order__c477bf58_958b_47c0_90b2_cdcdc891f614] .
2016-05-27 14:16:41.434 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. -  - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:351) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:356) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.lang.NullPointerException: null
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:449) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:340) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
	... 3 common frames omitted
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. -  - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:351)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:356)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:449)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:340)
	... 3 more
2016-05-27 14:16:50.806 [job-0] INFO  StandAloneJobContainerCommunicator - Total 32 records, 11594 bytes | Speed 1.13KB/s, 3 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2016-05-27 14:16:50.807 [job-0] ERROR JobContainer - 运行scheduler 模式[STANDALONE]出错.
2016-05-27 14:16:50.807 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. -  - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:351) ~[na:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:356) ~[na:na]
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92]
Caused by: java.lang.NullPointerException: null
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:449) ~[na:na]
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:340) ~[na:na]
	... 3 common frames omitted
2016-05-27 14:16:50.808 [job-0] INFO  StandAloneJobContainerCommunicator - Total 32 records, 11594 bytes | Speed 11.32KB/s, 32 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2016-05-27 14:16:50.912 [job-0] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. -  - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:41)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:351)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:356)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:449)
	at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:340)
	... 3 more
```

**Comment by Pengxijin** [comment]
@yakirChen 你好，我也遇到同样的问题，解决了么？

**Comment by yakirChen** [comment]
改了DataX的源码

**Comment by Pengxijin** [comment]
@yakirChen  可否告知一下你是怎么改的么，谢谢？ @huacnlee 希望能修复这个bug，以便完善datax，谢谢

**Comment by yakirChen** [comment]
@Pengxijin [https://github.com/alibaba/DataX/issues/46](https://github.com/alibaba/DataX/issues/46)

**Comment by SparkerYu** [comment]
能把HdfsWriter改完后的jar包发给我吗？万分感谢！
