### ISSUE TITLE
运行脚步失败,是我的打开方式有问题吗?

### ISSUE THREAD

**Issue by yanzhi008** [alibaba/DataX#50]
[root@master bin]# python datax.py ../job/testjob.json     

DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.

2018-03-27 03:36:51.264 [main] WARN  ConfigParser - 插件[ftpreader,ftpWriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader] 
2018-03-27 03:36:52.305 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader]
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
        at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
        at com.alibaba.datax.core.Engine.entry(Engine.java:137)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by Ryan-Miao** [comment]
解决了吗

**Comment by z2labplus** [comment]
我也遇到了这个问题，不知道解决了吗？

**Comment by Ryan-Miao** [comment]
我是配置文件写错误了

**Comment by z2labplus** [comment]
已经可以了吗？哥 我这边还是不可以

**Comment by yanzhi008** [comment]
已解决，插件模块中的配置文件的插件名称和json模板中的名称有一个大小写的区别 ，将两者改为一致即可

 

 

 

发件人: noreply@github.com <noreply@github.com> 代表 Ryan Miao
发送时间: 2018年10月27日 星期六 12:12
收件人: alibaba/DataX <DataX@noreply.github.com>
抄送: free <yz8518@163.com>; Author <author@noreply.github.com>
主题: Re: [alibaba/DataX] 运行脚步失败,是我的打开方式有问题吗? (#50)

 

解决了吗

**Comment by yanzhi008** [comment]
已解决，插件模块中的配置文件的插件名称和json模板中的名称有一个大小写的区别 ，将两者改为一致即可

 

 

大吉大利 今晚吃鸡!

 

发件人: noreply@github.com <noreply@github.com> 代表 herryzhang
发送时间: 2018年10月29日 星期一 16:37
收件人: alibaba/DataX <DataX@noreply.github.com>
抄送: free <yz8518@163.com>; Author <author@noreply.github.com>
主题: Re: [alibaba/DataX] 运行脚步失败,是我的打开方式有问题吗? (#50)

 

我也遇到了这个问题，不知道解决了吗？
