### ISSUE TITLE
[UnstructuredStorageReader-11], Description:[出现运行时异常

### ISSUE THREAD

**Issue by zhaojungithub** [alibaba/DataX#51]
14:26:24.499 ERROR c.a.d.c.t.runner.ReaderRunner[72] - Reader runner Received Exceptions:  
com.alibaba.datax.common.exception.DataXException: Code:[UnstructuredStorageReader-11], Description:[出现运行时异常, 请联系我们]. - 运行时异常 : null - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33) ~[datax-common-0.0.1-20160303.075158-2.jar:na]
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:297) ~[plugin-unstructured-storage-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:266) ~[hdfsreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
java.lang.NullPointerException: null
14:26:24.500 INFO  c.a.d.common.statistics.PerfRecord[108] - -1,1,9,READ_TASK_DESTROY,start,2016-06-20 14:26:24,-1,0,0,221.192.153.43  
14:26:24.500 INFO  c.a.d.common.statistics.PerfRecord[125] - -1,1,9,READ_TASK_DESTROY,end,2016-06-20 14:26:24,185330,0,0,221.192.153.43  
14:26:24.500 INFO  c.a.d.common.statistics.PerfRecord[133] - -1,1,9,WAIT_WRITE_TIME,end,2016-06-20 14:26:15,1179957852,0,0,221.192.153.43  
14:26:25.648 INFO  c.a.d.c.s.c.c.j.StandAloneJobContainerCommunicator[50] - Total 53184 records, 19625371 bytes | Speed 1.87MB/s, 5318 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.699s |  All Task WaitReaderTime 13.115s | Percentage 10.71%  
14:26:25.648 ERROR c.a.datax.core.job.JobContainer[529] - 运行scheduler 模式[STANDALONE]出错.  
14:26:25.649 ERROR c.a.datax.core.job.JobContainer[131] - Exception when job run  
com.alibaba.datax.common.exception.DataXException: Code:[UnstructuredStorageReader-11], Description:[出现运行时异常, 请联系我们]. - 运行时异常 : null - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33) ~[datax-common-0.0.1-20160303.075158-2.jar:na]
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:297) ~[plugin-unstructured-storage-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:266) ~[na:na]
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_25]
Caused by: java.lang.NullPointerException: null
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.transportOneRecord(UnstructuredStorageReaderUtil.java:313) ~[plugin-unstructured-storage-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:280) ~[plugin-unstructured-storage-util-0.0.1-SNAPSHOT.jar:na]
	... 3 common frames omitted
14:26:25.649 INFO  c.a.d.c.s.c.c.j.StandAloneJobContainerCommunicator[50] - Total 53184 records, 19625371 bytes | Speed 18.72MB/s, 53184 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.699s |  All Task WaitReaderTime 13.115s | Percentage 10.71%  
14:26:25.650 ERROR com.alibaba.datax.core.Engine[201] - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[UnstructuredStorageReader-11], Description:[出现运行时异常, 请联系我们]. - 运行时异常 : null - null
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:297)
	at com.alibaba.datax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:266)
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.transportOneRecord(UnstructuredStorageReaderUtil.java:313)
	at com.alibaba.datax.plugin.unstructuredstorage.reader.UnstructuredStorageReaderUtil.doReadFromStream(UnstructuredStorageReaderUtil.java:280)
	... 3 more

**Comment by zhaojungithub** [comment]
从hdfs同步到sqlserver，其中hdfs全部为string类型，sqlserver有3个text类型字段。怀疑是不是和这个有关系。请问这个错误是什么原因？
