### ISSUE TITLE
在测试使用ftp读写文件的时候报错!插件[ftpreader,ftpWriter]加载失败，1s后重试

### ISSUE THREAD

**Issue by yanzhi008** [alibaba/DataX#51]
有人遇到过这种情况吗?  别的测试都没有问题.就是在同步ftp文件时候出错
[root@master bin]# python datax.py ../job/testjob.json
DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
2018-03-27 03:21:35.675 [main] WARN ConfigParser - 插件[ftpreader,ftpWriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .]. - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader]
2018-03-27 03:21:36.704 [main] ERROR Engine -
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .]. - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader]
at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
at com.alibaba.datax.core.Engine.entry(Engine.java:137)
at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by yanzhi008** [comment]
问题已解决
git下来的源码和说明文档描述错误. 模版配置的插件名称与配置文件所配置的插件名称大小写不一致导致无法加载插件

**Comment by everl** [comment]
ftpWriter...
ftpwriter
