### ISSUE TITLE
支持informixreader吗，可以配置吗？

### ISSUE THREAD

**Issue by bringpp** [alibaba/DataX#515]
可以用rdbmsreader配置informix吗？
1、我在rdbmsreader的plugin.json中配置
    "drivers":["dm.jdbc.driver.DmDriver", "com.sybase.jdbc3.jdbc.SybDriver", "com.edb.Driver", "com.informix.jdbc.IfxDriver"]
2、libs下放了ifxjdbc.jar
3、job的配置如下
"reader": {
                    "name": "rdbmsreader",
                    "parameter": {
                        "username": "",
                        "password": "",
                        "connection": [{
                            "querySql": [
                                "select userid,departid from user_depart where userid=1;"
                            ],
                            "jdbcUrl": [
                                "jdbc:informix-sqli://ip:port/database:INFORMIXSERVER=;"
                            ]
                        }]
                    }
                },
4、运行job报错
 配置信息错误，您提供的配置文件xxxx/xxxxx/xxx/plugin.json不存在，请检查您的配置文件。
at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.common.util.Configuration.from(Configuration.java:95)
	at com.alibaba.datax.core.util.ConfigParser.parseOnePluginConfig(ConfigParser.java:153)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:125)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by arenaswan** [comment]
#720 原来不止我一个被迫进了informix数据库的深坑，可以尝试一下我这个 pull request，用法参照文档，我们已经上生产了，目前运行稳定。
