### ISSUE TITLE
插件[mysqlreader,mysqlwriter]加载失败

### ISSUE THREAD

**Issue by itwhat126** [alibaba/DataX#551]
2019-12-23 18:54:14.798 [main] WARN  ConfigParser - 插件[mysqlreader,mysqlwriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[mysqlwriter, mysqlreader] 
2019-12-23 18:54:15.806 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[mysqlwriter, mysqlreader]
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by itwhat126** [comment]
已解决，数据库是mysql8.0.11,datax默认驱动不支持，去mysql官网下载新的驱动更换即可

**Comment by zhbdesign** [comment]
我换了驱动包还是不行，还需要其他操作吗

**Comment by xuefengchang** [comment]
https://github.com/alibaba/DataX/issues/1657
单进程内不可以开启多个任务，否则会报该错误。
针对每个任务可以开启一个独立的子进程进行处理，就可以避免该问题。
