### ISSUE TITLE
单表数据同步多表数据问题

### ISSUE THREAD

**Issue by brucelpt** [alibaba/DataX#588]
# 错误信息
asks.
2020-02-06 19:53:22.507 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 您的配置文件中的列配置信息有误. 您要写入的目的端的表个数是:2 , 但是根据系统建议需要切分 的份数是：1. 请检查您的配置并作出修改.
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.writer.util.WriterUtil.doSplit(WriterUtil.java:42) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.split(CommonRdbmsWriter.java:132) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Job.split(MysqlWriter.java:44) ~[mysqlwriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-02-06 19:53:22.514 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2020-02-06 19:53:22.518 [job-0] ERROR Engine -

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 您的配置文件中的列配置信息有误. 您要写入的目的端的表个数是:2 , 但是根据系统建议需要切分 的份数是：1. 请检查您的配置并作出修改.
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.plugin.rdbms.writer.util.WriterUtil.doSplit(WriterUtil.java:42)
        at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.split(CommonRdbmsWriter.java:132)
        at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Job.split(MysqlWriter.java:44)
        at com.alibaba.datax.core.job.JobContainer.doWriterSplit(JobContainer.java:750)
        at com.alibaba.datax.core.job.JobContainer.split(JobContainer.java:397)
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:117)
        at com.alibaba.datax.core.Engine.start(Engine.java:92)
        at com.alibaba.datax.core.Engine.entry(Engine.java:171)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)

# json

{
  "job": {
    "setting": {
      "speed": {
        "channel": 2
      }
    },
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "XXX",
            "password": "XXX",
            "column": [
			  "id",
              "realId",
              "name",
			  "memo",
			  "action",
			  "time"
            ],
			"where": "time>=DATE_SUB(NOW(),INTERVAL 10 MINUTE)",
			"splitPk": "id",
            "connection": [
              {
                "table": [
                  "test2_temp_source"
                ],
                "jdbcUrl": [
				  "jdbc:mysql://XXX:XXX/testcodedb"
				]
              }
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "writeMode": "insert",
            "username": "XXX",
            "password": "XXX",
            "column": [
			  "id",
              "realId",
              "name",
			  "memo",
			  "action",
			  "time"
            ],
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://XXX:3306/testcodedb",
                "table": [
                  "test2_temp",
				  "test2_temp2"
                ]
              }
            ]
          }
        }
      }
    ]
  }
}

当我只同步单张表的时候他能正常同步数据，但是当我同步到多张表的时候出现上面的报错

**Comment by lzhao-1** [comment]
只能多对多，按顺序导数据

**Comment by dongb0** [comment]
如果需要把一张表的数据复制到两张表里，得分成两个一对一的Job执行

**Comment by jimmy-bj** [comment]
> 只能多对多，按顺序导数据

试过多对多吗？
reader:
……
"querySql": ["select * from table_a",""select * from table_b""]

writer:
……
"table": ["table_a","table_b"]

这样配置吗？

**Comment by brucelpt** [comment]
> > 只能多对多，按顺序导数据
> 
> 试过多对多吗？
> reader:
> ……
> "querySql": ["select * from table_a",""select * from table_b""]
> 
> writer:
> ……
> "table": ["table_a","table_b"]
> 
> 这样配置吗？

很感谢你的回答，我已经解决了这个问题，在读取插件中查询多次即可实现我这个需求

**Comment by meifu2027** [comment]
> > > 只能多对多，按顺序导数据
> > 
> > 
> > 试过多对多吗？
> > reader:
> > ……
> > "querySql": ["select * from table_a",""select * from table_b""]
> > writer:
> > ……
> > "table": ["table_a","table_b"]
> > 这样配置吗？
> 
> 很感谢你的回答，我已经解决了这个问题，在读取插件中查询多次即可实现我这个需求

多对多的情况下如何将reader和writer的column进行匹配？

**Comment by Common-zhou** [comment]
> > > > 只能多对多，按顺序导数据
> > > 
> > > 
> > > 试过多对多吗？
> > > reader:
> > > ……
> > > "querySql": ["select * from table_a",""select * from table_b""]
> > > writer:
> > > ……
> > > "table": ["table_a","table_b"]
> > > 这样配置吗？
> > 
> > 
> > 很感谢你的回答，我已经解决了这个问题，在读取插件中查询多次即可实现我这个需求
> 
> 多对多的情况下如何将reader和writer的column进行匹配？

Job里面有一个split()方法，可以重写split方法，或者调用原有的split后，再对得到的List<Confiruration> 进行修改即可一一对应。
