### ISSUE TITLE
hdfsreader.md中  "nullFormat":"\N" 说明有误

### ISSUE THREAD

**Issue by alanzhang211** [alibaba/DataX#65]
hdfsreader中配置nullFormat，如下：
` "nullFormat":"\N"`

报错：
`
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误. 您提供的配置信息不是合法的JSON格式: unclosed string : N . 请按照标准json格式提供配置信息. 
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.common.util.Configuration.<init>(Configuration.java:1066)
        at com.alibaba.datax.common.util.Configuration.from(Configuration.java:79)
        at com.alibaba.datax.core.util.ConfigParser.parseJobConfig(ConfigParser.java:75)
        at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:26)
        at com.alibaba.datax.core.Engine.entry(Engine.java:137)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)`

解决：
修改为：
` "nullFormat":"\\N"`

**Comment by Galthen** [comment]
我也遇到这个问题了，确实如此。
