### ISSUE TITLE
mysql2hdfs问题

### ISSUE THREAD

**Issue by UnderElm** [alibaba/DataX#663]
各位大佬好，
调度机使用datax 将 mysql 写入阿里云 emr hdfs，报以下错，master 9000端口已开，会是什么问题呢？两个 worker 均报 [connection-pending remote=/worker-1/2:50010]，是否需要向调度机开放 50010 端口

信息: Exception in createBlockOutputStream
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - org.apache.hadoop.net.ConnectTimeoutException: 60000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=/worker-1:50010]
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:534)
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.createSocketForPipeline(DFSOutputStream.java:1508)
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1284)
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1237)
[2020-04-29 02:15:38,686] {bash_operator.py:126} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:449)

**Comment by UnderElm** [comment]
解决了 同样需要开放 50010 （如果调度机在同一内网情况下）
