### ISSUE TITLE
在 mac 上编译运行报错,您提供的配置文件[/Users/XXX/Downloads/datax/plugin/reader/.DS_Store/plugin.json]不存在

### ISSUE THREAD

**Issue by theseusyang** [alibaba/DataX#77]
在 mac 上编译运行报错如下:

2016-08-24 15:45:42.693 [main] WARN  ConfigParser - 插件[mysqlreader,mysqlwriter]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/Users/XXX/Downloads/datax/plugin/reader/.DS_Store/plugin.json]不存在. 请检查您的配置文件. 
2016-08-24 15:45:43.698 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/Users/XXX/Downloads/datax/plugin/reader/.DS_Store/plugin.json]不存在. 请检查您的配置文件.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.common.util.Configuration.from(Configuration.java:95)
	at com.alibaba.datax.core.util.ConfigParser.parseOnePluginConfig(ConfigParser.java:153)
	at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:125)
	at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
	at com.alibaba.datax.core.Engine.entry(Engine.java:137)
	at com.alibaba.datax.core.Engine.main(Engine.java:204)

请问这个bug 如何纠正?

**Comment by binaryWorld** [comment]
删除 /Users/XXX/Downloads/datax/plugin/reader/.DS_Store 文件

**Comment by theseusyang** [comment]
牛!
