### ISSUE TITLE
数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确

### ISSUE THREAD

**Issue by daiwei233** [alibaba/DataX#815]
数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确
java.sql.SQLSyntaxErrorException: Access denied for user 'root'@'10.18.34.205' to database 'datax'

连接mysql报错，填的完全没有问题,， 10.18.34.205日志中打印的ip地址确实是本机的ip，但是我在配置文件中写的是127，就非常奇怪，在命令行中用root'@'10.18.34.205' 连接也是没有问题。
mysql版本5.7
配置文件
```
{
    "job": {
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
                        "column": [""],
                        "connection": [
                            {
                                "jdbcUrl": ["jdbc:mysql://127.0.0.1:3306/datax"],
                                "table": ["user"]
                            }
                        ],
                        "password": "password",
                        "username": "root",
                        "where": ""
                    }
                },
                "writer": {
                    "name": "mysqlwriter",
                    "parameter": {
                        "column": [""],
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:mysql://10.18.34.193:3306/datax",
                                "table": ["user"]
                            }
                        ],
                        "password": "password",
                        "preSql": [],
                        "session": [],
                        "username": "root",
                        "writeMode": ""
                    }
                }
            }
        ],
        "setting": {
            "speed": {
                "channel": ""
            }
        }
    }
}
```
错误日志:
2020-09-01 17:09:55.622 [main] INFO  Engine -
{
	"content":[
		{
			"reader":{
				"name":"mysqlreader",
				"parameter":{
					"column":[
						""
					],
					"connection":[
						{
							"jdbcUrl":[
								"jdbc:mysql://localhost:3306/datax"
							],
							"table":[
								"user"
							]
						}
					],
					"password":"********",
					"username":"root",
					"where":""
				}
			},
			"writer":{
				"name":"mysqlwriter",
				"parameter":{
					"column":[
						""
					],
					"connection":[
						{
							"jdbcUrl":"jdbc:mysql://10.18.34.193:3306/datax",
							"table":[
								"user"
							]
						}
					],
					"password":"********",
					"preSql":[],
					"session":[],
					"username":"root",
					"writeMode":""
				}
			}
		}
	],
	"setting":{
		"speed":{
			"channel":""
		}
	}
}

2020-09-01 17:09:55.645 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2020-09-01 17:09:55.648 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2020-09-01 17:09:55.648 [main] INFO  JobContainer - DataX jobContainer starts job.
2020-09-01 17:09:55.650 [main] INFO  JobContainer - Set jobId = 0
2020-09-01 17:09:56.138 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://localhost:3306/datax?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.
2020-09-01 17:09:56.161 [job-0] INFO  OriginalConfPretreatmentUtil - table:[user] has columns:[id,last_name,first_name,sex,age,phone,address,password,create_time].
2020-09-01 17:09:56.466 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[MYSQLErrCode-01], Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确].  - 该数据库用户名为：root 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'root'@'10.18.34.205' to database 'datax'
com.alibaba.datax.common.exception.DataXException: Code:[MYSQLErrCode-01], Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确].  - 该数据库用户名为：root 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'root'@'10.18.34.205' to database 'datax'
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asConnException(RdbmsException.java:21) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:394) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:384) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.access$000(DBUtil.java:22) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:322) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:319) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30) [datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:319) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:303) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.util.JdbcConnectionFactory.getConnecttion(JdbcConnectionFactory.java:27) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:105) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:140) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:35) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:41) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Job.init(MysqlWriter.java:31) [mysqlwriter-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-09-01 17:09:57.468 [job-0] ERROR RetryUtil - Exception when calling callable, 即将尝试执行第1次重试.本次重试计划等待[1000]ms,实际等待[1000]ms, 异常Msg:[Code:[MYSQLErrCode-01], Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确].  - 该数据库用户名为：root 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'root'@'10.18.34.205' to database 'datax']
2020-09-01 17:09:59.473 [job-0] ERROR RetryUtil - Exception when calling callable, 即将尝试执行第2次重试.本次重试计划等待[2000]ms,实际等待[2000]ms, 异常Msg:[Code:[MYSQLErrCode-01], Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确].  - 该数据库用户名为：root 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'root'@'10.18.34.205' to database 'datax']

```

**Comment by daiwei233** [comment]
请各位大佬帮忙看一下，谢谢🙏

**Comment by daiwei233** [comment]
解决了
原因是数据库权限的问题，给193的writer的mysql数据库赋权时候用了GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'xxxxx' WITH GRANT OPTION;
导致jdbc还是无法远程访问（这里命令行是ok的），把%改成本机的ip就可以了。

**Comment by CakeWenYx** [comment]
请问是什么意思！！！！求教

**Comment by daiwei233** [comment]
时间过去太久了，有点忘记了，似乎是把root改成目标数据库的ip

GRANT ALL PRIVILEGES ON . TO 'root'@'%' IDENTIFIED BY 'xxxxx' WITH GRANT OPTION;
改成
GRANT ALL PRIVILEGES ON . TO '10.18.34.193'@'%' IDENTIFIED BY 'xxxxx' WITH GRANT OPTION; @CakeWenYx

**Comment by CakeWenYx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
