### ISSUE TITLE
No enum constant com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.STRING

### ISSUE THREAD

**Issue by wengad82** [alibaba/DataX#816]
从mysql抽数到hive，报如下错误，什么情况呢？ 另外，能支持的从mysql里面抽VARCHAR型的最大长度是多少？
com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. - java.lang.IllegalArgumentException: No enum constant com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.STRING,
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.valueOf(SupportHiveDataType.java:3)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:495)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:323)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.textFileStartWrite(HdfsHelper.java:306)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:360)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.IllegalArgumentException: No enum constant com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.STRING,
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.valueOf(SupportHiveDataType.java:3)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:495)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:323)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.textFileStartWrite(HdfsHelper.java:306)
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:360)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
        at java.lang.Thread.run(Thread.java:748)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.textFileStartWrite(HdfsHelper.java:317) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:360) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: No enum constant com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.STRING,
        at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_221]
        at com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.valueOf(SupportHiveDataType.java:3) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:495) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.transportOneRecord(HdfsHelper.java:323) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.hdfswriter.HdfsHelper.textFileStartWrite(HdfsHelper.java:306) ~[hdfswriter-0.0.1-SNAPSHOT.jar:na]
        ... 3 common frames omitted

**Comment by wengad82** [comment]
![图片](https://user-images.githubusercontent.com/19250813/91919102-7dcebf00-ecf7-11ea-90a9-5bd67b5ec61f.png)
类型里面多了个逗号，一直过不去！  这个报错还是要改善改善，不然在什么疲劳的时候，根本看不出来。

**Comment by nkuflk** [comment]
Caused by: java.lang.IllegalArgumentException: No enum constant com.alibaba.datax.plugin.writer.hdfswriter.SupportHiveDataType.STRING,

这个报错还不够明显吗。。。
