### ISSUE TITLE
datax 读 （AnalyticDB MySQL 版) 写hdfs 报错，出现了多个字段的值粘到了一起。

### ISSUE THREAD

**Issue by fuqiangma** [alibaba/DataX#824]
datax 同步AnalyticDB  数据时，用的mysqlreader 。同步数据时发现多个字段的值粘到了一起。
也就是说 resultSet.getString(1) 获取到的内容是index 为1，2，3，4，5 粘到了一起。
报错信息如下：

2020-09-13 19:06:06.127 [0-0-0-reader] ERROR StdoutPluginCollector -
com.alibaba.datax.common.exception.DataXException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String[19348712
                                                                                                                                                ������������10.00.4824.215225900
15669021174.]不能转为Long .
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.common.element.LongColumn.<init>(LongColumn.java:35) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.buildRecord(CommonRdbmsReader.java:274) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.transportOneRecord(CommonRdbmsReader.java:237) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:209) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:81) [mysqlreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) [datax-core-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2020-09-13 19:06:06.129 [0-0-0-reader] ERROR StdoutPluginCollector - 脏数据:
{"exception":"Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String[\u000019348712\f������������\u000410.0\u00040.48\u000524.21\u00015\u000522590\u00010\n1566902117\u00044.]不能转为Long .","record":[],"type":"reader"}

**Comment by fuqiangma** [comment]
已经解决了，是因为在执行同步时，sql 被杀死了。
