### ISSUE TITLE
datax 从odps到mysql 获取不到odps字段名

### ISSUE THREAD

**Issue by keer123456789** [alibaba/DataX#826]
Exception in thread "taskGroup-0" com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 列配置信息有错误. 因为您配置的任务中，源头读取字段数:0 与 目的表要写入的字段数:9 不相等. 请检查您的配置并作出修改.
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:278)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319)
	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
	at java.lang.Thread.run(Thread.java:748)

配置文件：
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "odpsreader",
          "parameter": {
            "odpsServer": "http://service.odps.aliyun.com/api",
            "project": "cetc15_huitan",
            "table": "zhongfahuitan",
            "accessId": "******************",
            "accessKey": "********************",
            "column": [
              "url",
              "topic",
              "keywords",
              "title",
              "author_name",
              "contents",
              "rksj"
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://192.168.12.***:3306/test",
                "table": [
                  "aaa"
                ]
              }
            ],
            "username": "******",
            "password": "******",
            "column": [
              "url",
              "topic",
              "keywords",
              "title",
              "author_name",
              "contents",
              "rksj"
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": "1"
      }
    }
  }
}

**Comment by fuqiangma** [comment]
问题已经找到了，是因为在同步过程中。这条sql 被杀死导致的。

**Comment by SpringStudent** [comment]
怎么解决的大佬
