### ISSUE TITLE
mysql数据同步到influxdb有bug

### ISSUE THREAD

**Issue by hegphegp** [alibaba/DataX#891]
* mysql数据同步到influxdb有bug
* mysql转influxdb的插件下载地址是  https://tsdbtools.oss-cn-hangzhou.aliyuncs.com/datax_mysql_2_influxdb.tar.gz
```
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
    at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:147)
    at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
    at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:808)
    at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:463)
    at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22)
    at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:340)
    at org.influxdb.impl.BatchProcessor.flush(BatchProcessor.java:391)
    at org.influxdb.impl.InfluxDBImpl.flush(InfluxDBImpl.java:824)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.batchWriterRDB(InfluxDBWriter.java:295)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.batchWriter(InfluxDBWriter.java:251)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.startWrite(InfluxDBWriter.java:230)
    at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
    at java.lang.Thread.run(Thread.java:748)

Nov 23, 2020 1:30:20 PM org.influxdb.impl.BatchProcessor write
SEVERE: Batch could not be sent. Data will be lost
org.influxdb.InfluxDBException$UnableToParseException: unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
```

问题01）同步时字段缺失
问题02）timestamp字段有问题
* mysql的脚本样例数据
```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `st_pptn_r`;
CREATE TABLE `st_pptn_r`  (
  `STCD` char(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TM` datetime(0) NOT NULL,
  `DRP` decimal(5, 1) NULL DEFAULT NULL,
  `INTV` decimal(5, 2) NOT NULL DEFAULT 0.05,
  `PDR` decimal(5, 2) NULL DEFAULT NULL,
  `DYP` decimal(5, 1) NULL DEFAULT NULL,
  `WTH` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ID` decimal(18, 0) NULL DEFAULT NULL,
  `WRTM` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`STCD`, `TM`, `INTV`) USING BTREE,
  INDEX `createtime_index`(`WRTM`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `data`.`st_pptn_r`(`STCD`, `TM`, `DRP`, `INTV`, `PDR`, `DYP`, `WTH`, `ID`, `WRTM`) VALUES ('12345678', '2020-08-13 18:35:00', 0.0, 0.00, 0.00, 0.0, NULL, 0, '2020-08-18 10:23:58');
INSERT INTO `data`.`st_pptn_r`(`STCD`, `TM`, `DRP`, `INTV`, `PDR`, `DYP`, `WTH`, `ID`, `WRTM`) VALUES ('12345678', '2020-08-13 18:40:00', 0.0, 0.00, 0.00, 0.0, NULL, 0, '2020-08-18 10:23:58');
INSERT INTO `data`.`st_pptn_r`(`STCD`, `TM`, `DRP`, `INTV`, `PDR`, `DYP`, `WTH`, `ID`, `WRTM`) VALUES ('12345678', '2020-08-13 18:45:00', 0.0, 0.00, 0.00, 0.0, NULL, 0, '2020-08-18 10:23:58');
INSERT INTO `data`.`st_pptn_r`(`STCD`, `TM`, `DRP`, `INTV`, `PDR`, `DYP`, `WTH`, `ID`, `WRTM`) VALUES ('12345678', '2020-08-13 18:50:00', 0.0, 0.00, 0.00, 0.0, NULL, 0, '2020-08-18 10:23:58');
INSERT INTO `data`.`st_pptn_r`(`STCD`, `TM`, `DRP`, `INTV`, `PDR`, `DYP`, `WTH`, `ID`, `WRTM`) VALUES ('12345678', '2020-08-13 18:55:00', 0.0, 0.00, 0.00, 0.0, NULL, 0, '2020-08-18 10:23:58');
```

* 任务的json配置信息
```
{
  "job": {
    "content": [{
      "reader": {
        "name": "mysqlreader",
        "parameter": {
          "column": [
            "STCD",
            "TM",
            "DRP",
            "INTV",
            "PDR",
            "DYP",
            "WTH",
            "ID",
            "WRTM"
          ],
          "connection": [{
            "jdbcUrl": [ "jdbc:mysql://172.18.0.1:3306/data" ],
            "table": [ "st_pptn_r" ]
          }],
          "password": "root",
          "username": "root"
        }
      },
      "writer": {
        "name": "influxdbwriter",
        "parameter": {
          "column": [
            "id",
            "time",
            "HoursRain",
            "INTV",
            "PDR",
            "DYP",
            "WTH",
            "ID",
            "WRTM"
          ],
          "columnType": [
            "tag",
            "timestamp",
            "number_field",
            "number_field",
            "number_field",
            "number_field",
            "string_field",
            "number_field",
            "timestamp"
          ],
          "sourceDbType": "RDB",
          "endpoint": "http://172.18.0.1:8086",
          "username": "test",
          "password": "test",
          "database": "database",
          "createDatabase": true,
          "batchSize": 100,
          "measurement": "HoursRain"
        }
      }
    }],
    "setting": {
      "speed": {
        "channel": 1
      }
    }
  }
}
```

* 错误信息
```
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
    at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:147)
    at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
    at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:808)
    at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:463)
    at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22)
    at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:340)
    at org.influxdb.impl.BatchProcessor.flush(BatchProcessor.java:391)
    at org.influxdb.impl.InfluxDBImpl.flush(InfluxDBImpl.java:824)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.batchWriterRDB(InfluxDBWriter.java:295)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.batchWriter(InfluxDBWriter.java:251)
    at com.alibaba.datax.plugin.writer.influxdbwriter.InfluxDBWriter$Task.startWrite(InfluxDBWriter.java:230)
    at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56)
    at java.lang.Thread.run(Thread.java:748)

Nov 23, 2020 1:30:20 PM org.influxdb.impl.BatchProcessor write
SEVERE: Batch could not be sent. Data will be lost
org.influxdb.InfluxDBException$UnableToParseException: unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
unable to parse 'HoursRain,id=12345678 HoursRain=0.0,INTV=0.0 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
```

![image](https://user-images.githubusercontent.com/26202719/99932099-05c1e380-2d92-11eb-9317-5c815a220613.png)

**Comment by yilovezy** [comment]
确实遇到了这个问题，对于mysql中datetime和timstamp类型的时间，同步到influxdb是不能正确解析的，总显示超出范围。但是mysql中存储的unix_timestamp的int型的时间戳就可以同步过去。

**Comment by hegphegp** [comment]
我改成SQL同步就可以了，好像时间类型不能直接同步到influxDB，要改成select unix_timestamp(时间字段) AS time字段就可以了。
