### ISSUE TITLE
mysql同步数据报： Could not retrieve transation read-only status server

### ISSUE THREAD

**Issue by ghost** [alibaba/DataX#900]
报错
`2020-12-02 16:23:44 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param:
2020-12-02 16:23:44 [BuildCommand.buildDataXParam-100] ------------------Command parameters:
2020-12-02 16:23:44 [ExecutorJobHandler.execute-57] ------------------DataX process id: 14132
2020-12-02 16:23:44 [ProcessCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.
2020-12-02 16:23:44 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:44 [AnalysisStatistics.analysisStatisticsLog-53] DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
2020-12-02 16:23:44 [AnalysisStatistics.analysisStatisticsLog-53] Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
2020-12-02 16:23:44 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:44 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.675 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.709 [main] INFO  Engine - the machine info  => 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	osInfo:	Oracle Corporation 1.8 25.241-b07
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	jvmInfo:	Linux amd64 3.10.0-1127.el7.x86_64
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	cpu num:	4
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	totalPhysicalMemory:	-0.00G
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	freePhysicalMemory:	-0.00G
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	maxFileDescriptorCount:	-1
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	currentOpenFileDescriptorCount:	-1
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	GC Names	[PS MarkSweep, PS Scavenge]
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	MEMORY_NAME                    | allocation_size                | init_size                      
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Eden Space                  | 256.00MB                       | 256.00MB                       
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	Code Cache                     | 240.00MB                       | 2.44MB                         
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Survivor Space              | 42.50MB                        | 42.50MB                        
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	PS Old Gen                     | 683.00MB                       | 683.00MB                       
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	Metaspace                      | -0.00MB                        | 0.00MB                         
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.788 [main] INFO  Engine - 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] {
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	"content":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"reader":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mysqlreader",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`id`",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`ip`",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`name`"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"connection":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							"jdbcUrl":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 								"jdbc:mysql://192.168.1.206:3306/test01"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							"table":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 								"ip"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							]
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"****************",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"splitPk":"",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"root"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			},
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"writer":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mysqlwriter",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`id`",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`ip`",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						"`name`"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"connection":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							"jdbcUrl":"jdbc:mysql://192.168.1.221:3306/test01",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							"table":[
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 								"ip"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 							]
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"****************",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"root",
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 					"writeMode":"insert"
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 				}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	],
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	"setting":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		"errorLimit":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"percentage":0.02,
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"record":0
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		},
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		"speed":{
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"byte":1048576,
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 			"channel":3
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 	}
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] }
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.861 [main] WARN  Engine - prioriy set to 0, because NumberFormatException, the value is: null
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.868 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.870 [main] INFO  JobContainer - DataX jobContainer starts job.
2020-12-02 16:23:46 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:46.877 [main] INFO  JobContainer - Set jobId = 0
2020-12-02 16:23:48 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:48.225 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://192.168.1.206:3306/test01?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.
2020-12-02 16:23:48 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:48.286 [job-0] INFO  OriginalConfPretreatmentUtil - table:[ip] has columns:[id,ip,name].
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.141 [job-0] INFO  OriginalConfPretreatmentUtil - table:[ip] all columns:[
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] id,ip,name
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] ].
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.205 [job-0] INFO  OriginalConfPretreatmentUtil - Write data [
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] insert INTO %s (`id`,`ip`,`name`) VALUES(?,?,?)
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] ], which jdbcUrl like:[jdbc:mysql://192.168.1.221:3306/test01?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.207 [job-0] INFO  JobContainer - jobContainer starts to do prepare ...
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.216 [job-0] INFO  JobContainer - DataX Reader.Job [mysqlreader] do prepare work .
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.217 [job-0] INFO  JobContainer - DataX Writer.Job [mysqlwriter] do prepare work .
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.219 [job-0] INFO  JobContainer - jobContainer starts to do split ...
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.222 [job-0] INFO  JobContainer - Job set Max-Byte-Speed to 1048576 bytes.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.233 [job-0] INFO  JobContainer - DataX Reader.Job [mysqlreader] splits to [1] tasks.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.235 [job-0] INFO  JobContainer - DataX Writer.Job [mysqlwriter] splits to [1] tasks.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.288 [job-0] INFO  JobContainer - jobContainer starts to do schedule ...
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.302 [job-0] INFO  JobContainer - Scheduler starts [1] taskGroups.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.309 [job-0] INFO  JobContainer - Running by standalone Mode.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.338 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.368 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.368 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.483 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[0] attemptCount[1] is started
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.505 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select `id`,`ip`,`name` from ip 
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] ] jdbcUrl:[jdbc:mysql://192.168.1.206:3306/test01?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true].
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.574 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select `id`,`ip`,`name` from ip 
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] ] jdbcUrl:[jdbc:mysql://192.168.1.206:3306/test01?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true].
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.646 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:Could not retrieve transation read-only status server
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.715 [0-0-0-writer] ERROR StdoutPluginCollector - 
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] java.sql.SQLException: Could not retrieve transation read-only status server
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:902) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:892) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3607) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3576) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.PreparedStatement.checkReadOnlySafeStatement(PreparedStatement.java:1114) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1134) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:382) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:362) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:297) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:319) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Task.startWrite(MysqlWriter.java:78) [mysqlwriter-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.sql.SQLException: Unknown system variable 'tx_read_only'
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3601) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 	... 10 common frames omitted
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.745 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: 
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] {"exception":"Could not retrieve transation read-only status server","record":[{"byteSize":1,"index":0,"rawData":1,"type":"LONG"},{"byteSize":11,"index":1,"rawData":"192.168.1.1","type":"STRING"},{"byteSize":2,"index":2,"rawData":"李广","type":"STRING"}],"type":"writer"}
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.799 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] taskId[0] is successed, used[360]ms
2020-12-02 16:23:49 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:49.801 [taskGroup-0] INFO  TaskGroupContainer - taskGroup[0] completed it's tasks.
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:59.379 [job-0] INFO  StandAloneJobContainerCommunicator - Total 1 records, 14 bytes | Speed 1B/s, 0 records/s | Error 1 records, 14 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:59.381 [job-0] ERROR JobContainer - 运行scheduler 模式[standalone]出错.
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:59.382 [job-0] ERROR JobContainer - Exception when job run
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] com.alibaba.datax.common.exception.DataXException: Code:[Framework-14], Description:[DataX传输脏数据超过用户预期，该错误通常是由于源端数据存在较多业务脏数据导致，请仔细检查DataX汇报的脏数据日志信息, 或者您可以适当调大脏数据阈值 .].  - 脏数据条数检查不通过，限制是[0]条，但实际上捕获了[1]条.
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.util.ErrorRecordChecker.checkRecordLimit(ErrorRecordChecker.java:58) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:89) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.schedule(JobContainer.java:535) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:119) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:59.386 [job-0] INFO  StandAloneJobContainerCommunicator - Total 1 records, 14 bytes | Speed 14B/s, 1 records/s | Error 1 records, 14 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 2020-12-02 16:23:59.387 [job-0] ERROR Engine - 
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 经DataX智能分析,该任务最可能的错误原因是:
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] com.alibaba.datax.common.exception.DataXException: Code:[Framework-14], Description:[DataX传输脏数据超过用户预期，该错误通常是由于源端数据存在较多业务脏数据导致，请仔细检查DataX汇报的脏数据日志信息, 或者您可以适当调大脏数据阈值 .].  - 脏数据条数检查不通过，限制是[0]条，但实际上捕获了[1]条.
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.util.ErrorRecordChecker.checkRecordLimit(ErrorRecordChecker.java:58)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:89)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.schedule(JobContainer.java:535)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:119)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.start(Engine.java:92)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.entry(Engine.java:171)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.core.Engine.main(Engine.java:204)
2020-12-02 16:23:59 [AnalysisStatistics.analysisStatisticsLog-53] 
2020-12-02 16:23:59 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null]
2020-12-02 16:23:59 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.`

mysql事务级别也都改成：READ-COMMITTED
mysql> SHOW VARIABLES LIKE '%iso%';
+-----------------------+----------------+
| Variable_name         | Value          |
+-----------------------+----------------+
| transaction_isolation | READ-COMMITTED |
+-----------------------+----------------+
1 row in set (0.00 sec)

**Comment by ghost** [comment]
修改主题

**Comment by xfdFan** [comment]
> Could not retrieve transation read-only status serve

看日志你这是写入数据报错，MySQL服务器为只读状态服务器，该错误查询说1是MySQL JDBC依赖与实际的MySQL服务版本不一致；检查一下pom依赖跟服务版本是否对应

**Comment by red-fox-yj** [comment]
http://mjvvv.cn/blogBrowse?blogId=63 
问题2
