### ISSUE TITLE
Null File can not check to support when export hdfs to mysql

### ISSUE THREAD

**Issue by zhengqiangtan** [alibaba/DataX#905]
Hi  when I using  an orc table and One of the partition‘s file is null like this ：
```
dfs -ls -h hdfs://nameservice1/user/hive/warehouse/bi.db/bi_kids_9_9_hf/pt=2020120713;  

Found 1 items
-rwxrwxrwx   3 zm_app_prd hive          0 2020-12-07 14:47 hdfs://nameservice1/user/hive/warehouse/bi.db/bi_kids_9_9_hf/pt=2020120713/000000_0
```

and export to mysql met error  like this ：

```shell

2020-12-07 14:54:08.602 [job-0] ERROR HdfsReader$Job - 检查文件[hdfs://nameservice1/user/hive/warehouse/bi.db/bi_kids_9_9_hf/pt=2020120713/000000_0]类型失败，目前支持ORC,SEQUENCE,RCFile,TEXT,CSV五种格式的文件,请检查您文件类型和文件是否正确。
2020-12-07 14:54:08.624 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[HdfsReader-10], Description:[读取文件出错].  - 检查文件[hdfs://nameservice1/user/hive/warehouse/bi.db/bi_kids_9_9_hf/pt=2020120713/000000_0]类型失败，目前支持ORC,SEQUENCE,RCFile,TEXT,CSV五种格式的文件,请检查您文件类型和文件是否正确。 - java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
	at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.isORCFile(DFSUtil.java:580)
	at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.checkHdfsFileType(DFSUtil.java:547)
	at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.addSourceFileByType(DFSUtil.java:184)
Caused by: java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:540) ~[na:1.8.0_152]
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139) ~[na:1.8.0_152]
	at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.isORCFile(DFSUtil.java:580) ~[hdfsreader-0.0.1-SNAPSHOT.jar:na]
	at com.alibaba.datax.plugin.reader.hdfsreader.DFSUtil.checkHdfsFileType(DFSUtil.java:547) ~[hdfsreader-0.0.1-SNAPSHOT.jar:na]
	... 11 common frames omitted

```

So I found that the datax push  failed because the datax source failed to check the type of the empty file .

**Comment by zhengqiangtan** [comment]
Fix : 添加过滤逻辑
```java
    /**
     * 过滤空文件
     * @param f
     */
    private void addSourceFileIfNotEmpty(FileStatus f) {
        if (f.isFile()) {
            String filePath = f.getPath().toString();
            if (f.getLen() > 0) {
                addSourceFileByType(filePath);
            } else {
                LOG.warn(String.format("文件[%s]长度为0，将会跳过不作处理！", filePath));
            }
        }
    }
```

**Comment by Flutemr** [comment]
> Fix : 添加过滤逻辑
> 
> ```java
>     /**
>      * 过滤空文件
>      * @param f
>      */
>     private void addSourceFileIfNotEmpty(FileStatus f) {
>         if (f.isFile()) {
>             String filePath = f.getPath().toString();
>             if (f.getLen() > 0) {
>                 addSourceFileByType(filePath);
>             } else {
>                 LOG.warn(String.format("文件[%s]长度为0，将会跳过不作处理！", filePath));
>             }
>         }
>     }
> ```

there hava other error :  com.alibaba.datax.common.exception.DataXException: Code:[HdfsReader-08], Description:[您尝试读取的文件目录为空.]. - 未能找到待读取的文件,请确认您的配置项path。
Do you have this error ，And then solve this error?
