### ISSUE TITLE
datax是不是不能以update的方式往ADB做增量同步

### ISSUE THREAD

**Issue by wtlihao** [alibaba/DataX#913]
datax是不是不能以update的方式往ADB做增量同步

**Comment by wtlihao** [comment]
![image](https://user-images.githubusercontent.com/30258468/102308479-abd3c880-3fa1-11eb-8092-ceef954fcb3a.png)

**Comment by wtlihao** [comment]
![image](https://user-images.githubusercontent.com/30258468/102308514-c017c580-3fa1-11eb-8f31-b26ba9e924f8.png)

**Comment by wtlihao** [comment]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: [13000, 2020121613200401011100816703453916688] do not support `insert on duplicate key` currently.
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_251]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_251]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_251]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_251]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.34.jar:5.1.34]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:382) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
2020-12-16 13:20:04 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:362) [plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]

**Comment by xiuhongquan** [comment]
ADB2.0不支持update
