### ISSUE TITLE
mysql_reader报错，超时timeout

### ISSUE THREAD

**Issue by xc1989xc** [alibaba/DataX#992]
具体错误信息为：java.sql.SQLException: [32005, 2021040919565301001603002603151283989] : Query exceeded maximum time limit of 7200000.00ms
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:81)
        at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:220)
        at com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:81)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:748)

应该设置哪里？或者配置mysq哪个参数？

**Comment by fuchanghai** [comment]
![image](https://user-images.githubusercontent.com/33984497/114646562-0db4fc80-9d0e-11eb-9add-b2c72c3123b0.png)

![image](https://user-images.githubusercontent.com/33984497/114646499-ee1dd400-9d0d-11eb-854e-303abe39dc0a.png)
![image](https://user-images.githubusercontent.com/33984497/114646533-0392fe00-9d0e-11eb-8a9d-c2978316550a.png)
220 行的报错应该只有这个了。记得修改之后package 到 dataxHome里

**Comment by xc1989xc** [comment]
代码里是172800，但是我报错是7200秒啊

**Comment by xc1989xc** [comment]
这个超时是怎么产生的呢？和数据源是adb有关系么？但是原来源用mysql貌似也出现过

**Comment by fuchanghai** [comment]
您的版本可能和我不一样吧，我是down 的 master 分支上的



从代码上看 这个是建立tcp 连接的时候 超时了。 你可以开启mysql 的慢查询日志，然后去看看是不是超时了，或者直接放到navicat里跑一下。如果你是手写sql 的话，最好explain 确保走索引


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] mysql_reader报错，超时timeout (#992)





 
这个超时是怎么产生的呢？和数据源是adb有关系么？但是原来源用mysql貌似也出现过

**Comment by xc1989xc** [comment]
我说明情下：1 我这边用的程序是主页中下载地址的那个编译好的。我这边也是直接download的master，里边的代码里是172800，

**Comment by xc1989xc** [comment]
我说明情下：1 我这边用的程序是主页中下载地址的那个编译好的。2 在download的master的代码里，超时时间是172800。3 我这边现在将超时时间设置为0了，有了测试结果，我再同步到这儿。4 谢谢你，撒花！！！

**Comment by wxwwt** [comment]
这个应该不是dataX的超时时间的问题，我也遇到了类似的问题，原因是对接的数据库是adb的mysql版本，adb默认限制了单次查询时间不能超过30分钟。
adb解决方式：
select前面加hint
/*+query_timeout=7200000*/ select XXX
或者配置
set adb_config query_timeout=xxx;
